- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/junits/IgniteCompatibilityAbstractTest.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridJavaProcess.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/GridAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/IgniteProcessProxy.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/JavaVersionCommand.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/JavaVersionCommandParser.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/JavaVersionCommandParserTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite.java
https://issues.apache.org/jira/browse/IGNITE-17805 …
> IGNITE-17805 Fail a test if it tries to launch remote JVM with different major Java version

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/CacheExchangeMergeTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/GridAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-17837
The problem is that, if a grid fails to start (for instance, due to PME), then the test times out, then afterTest() is called which calls stopAllGrids(), which, in turn, waits for all grids to be started, so it hangs as well, this time forever (as the timeout is not applied to afterTest()).
We try to solve the problem by using the variation of stopAllGrids() that does not wait for the grids to start and tries to stop them regargless of their state.
The following pattern must be used: `IGNITE-XXXX …
> IGNITE-17837 CacheExchangeMergeTest.testConcurrentStartServers sometimes hangs forever

- modules/core/src/test/java/org/apache/ignite/testframework/junits/GridAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-17847 …
> IGNITE-17847 Dump threads if afterTest() times out

- modules/core/src/test/java/org/apache/ignite/internal/ThreadNameValidationTest.java
https://issues.apache.org/jira/browse/IGNITE-17863 …
> IGNITE-17863 ThreadNameValidationTest fails if run alone (or first in suite)

- docs/_docs/tools/control-script.adoc
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/consistency/ConsistencyCommand.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyCountersTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyRepairCorrectnessTransactionalTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/KillCommandsCommandShTest.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/consistency/VisorConsistencyRepairTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/consistency/VisorConsistencyRepairTaskArg.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/DataGenerationApplication.java
- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/cache.py
- modules/ducktests/tests/ignitetest/tests/control_utility/consistency_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/in_memory_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/persistent_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/util.py
- modules/ducktests/tests/ignitetest/tests/util.py
> IGNITE-17736 Consistency repair should support multiply partitions

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/IgniteReleasedVersion.java
> IGNITE-17854 Update IgniteReleasedVersion with 2.14.0

- modules/calcite/pom.xml
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessor.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/ExecutionServiceImpl.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/AbstractMultiStepPlan.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/DynamicParamTypeExtractor.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/FieldsMetadata.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/FieldsMetadataImpl.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/IgniteRelRexNodeShuttle.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/MultiStepDmlPlan.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/MultiStepPlan.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/MultiStepQueryPlan.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/PrepareServiceImpl.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/schema/CacheTableDescriptorImpl.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/QueryMetadataIntegrationTest.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/jdbc/JdbcQueryTest.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/planner/PlannerTest.java
- modules/calcite/src/test/java/org/apache/ignite/testsuites/IntegrationTestSuite.java
- modules/core/src/main/java/org/apache/ignite/internal/jdbc2/JdbcPreparedStatement.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/jdbc/JdbcParameterMeta.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/jdbc/JdbcRequestHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/jdbc/JdbcRequestHandlerWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/odbc/OdbcRequestHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/odbc/OdbcRequestHandlerWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/NoOpQueryEngine.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryEngine.java
> IGNITE-17598 SQL Calcite: Implement jdbc metadata.

- modules/ducktests/tests/ignitetest/tests/control_utility/consistency_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/in_memory_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/persistent_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/util.py
> IGNITE-17912 Ducktape tests fix

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/RebalanceIteratorLargeEntriesOOMTest.java
https://issues.apache.org/jira/browse/IGNITE-17807 …
> IGNITE-17807 OutOfMemoryException in RebalanceIteratorLargeEntriesOOMTest on TC

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheOperationContext.java
- modules/urideploy/src/test/java/org/apache/ignite/spi/deployment/uri/GridUriDeploymentConfigSelfTest.java
…TOMIC_OPS_IN_TX
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviatio …
> IGNITE-17916 Deprecate IGNITE_ALLOW_ATOMIC_OPS_IN_TX

- modules/core/src/main/java/org/apache/ignite/configuration/ClientConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientBinaryMarshaller.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientChannelConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientInternalBinaryConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ReliableChannel.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpIgniteClient.java
- modules/core/src/main/java/org/apache/ignite/logger/NullLogger.java
- modules/core/src/test/java/org/apache/ignite/client/BinaryConfigurationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/AbstractThinClientTest.java
* Add `ClientConfiguration.logger`
* Log connection attempts, configuration adjustments, errors
> IGNITE-17351 Java thin: Add logging

- modules/kubernetes/pom.xml
> IGNITE-17572 update dependency mockserver-netty

- parent/pom.xml
> IGNITE-17926 Update jetty dependency

- modules/core/src/test/java/org/apache/ignite/platform/PlatformWaitForRebalanceTask.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/PartitionLossTest.cs
Add `PlatformWaitForRebalanceTask` to wait for rebalance reliably.
> IGNITE-17946 .NET: Fix PartitionLossTest flakiness

- bin/include/jvmdefaults.bat
- bin/include/jvmdefaults.sh
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryClassDescriptor.java
- modules/core/src/main/java/org/apache/ignite/internal/marshaller/optimized/OptimizedClassDescriptor.java
- modules/core/src/main/java/org/apache/ignite/internal/util/FeatureChecker.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/GridMultipleVersionsDeploymentSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/IgniteExplicitImplicitDeploymentSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/PlainSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/p2p/GridP2PRemoteClassLoadersSelfTest.java
- parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-17962 …
> IGNITE-17962 Fix serializable lambda serialization with Java17

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotFutureTask.java
> IGNITE-17613 Copy of binary metadata added

- modules/core/src/test/java/org/apache/ignite/testframework/GridTestUtils.java
> IGNITE-17937 Fixed initialization of test home path for non Ignite projects

- modules/core/src/main/java/org/apache/ignite/internal/processors/query/stat/IgniteStatisticsConfigurationManager.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/stat/StatisticsConfigurationTest.java
> IGNITE-17964 Potential deadlock in discovery thread while updating SQL statistics.

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/IdleVerifyResultV2.java
> IGNITE-17995 Idle_verify must print broken partitions list

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/CommandHandler.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerAbstractTest.java
- modules/core/src/main/java/org/apache/ignite/internal/logger/IgniteLoggerEx.java
- modules/core/src/main/java/org/apache/ignite/logger/java/JavaLogger.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/logger/GridTestLog4jLogger.java
- modules/log4j2/src/main/java/org/apache/ignite/logger/log4j2/Log4J2Logger.java
> IGNITE-18062 Fix Log4j2Logger output to console

- modules/ml/pom.xml
- parent/pom.xml
> IGNITE-18108 Updated Jackson Databind dependency to 2.14.0

- modules/calcite/pom.xml
- modules/platforms/cpp/thin-client-test/src/ssl_test.cpp
> IGNITE-18107 C++: Fix tests for openssl 3.0, fix odbc with calcite engine

- modules/ducktests/tests/checks/utils/check_ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/templates/log4j2.xml.j2
- Fix console output of the control.sh in context of ducktest running in development mode as described at IGNITE-18112
- Fix control.sh logging - now control-utility.log is included into the ducktest result zip package
- Fix logging of the ignite-aware application & service: 
- no records from IgniteAwareApplicationService are missed any more
- do not duplicate both to ignite.log and console.log
------------------
(see [the Maintainers …
> IGNITE-18112 [ducktests] Fix logging of control.sh and ignite-aware application

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/AbstractReducer.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridReduceQueryExecutor.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/ReducePartitionMapper.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/Reducer.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/SortedReducer.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/UnsortedBaseReducer.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/IgniteSqlSegmentedIndexSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/IgniteSqlSinglePartitionMultiParallelismTest.java
… queries
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules …
> IGNITE-18114 Changing default QueryParallelism leads to crush ordered queries

- modules/core/src/main/java/org/apache/ignite/ssl/SslContextFactory.java
…xtFactory
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rule …
> IGNITE-18130 Increate visibility of methods and variables of SslContextFactory

- parent/pom.xml
> IGNITE-18142 update postgresql dependency

- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Memory/PlatformMemoryUtils.cs
* Remove unnecessary reflection from `PlatformMemoryUtils` to enable thick and thin API usage in Native AOT mode.
> IGNITE-18178 .NET: Add support for Native AOT

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/test/java/org/apache/ignite/failure/IoomFailureHandlerTest.java
https://issues.apache.org/jira/browse/IGNITE-18169 …
> IGNITE-18169 Fix IoomFailureHandlerTest.testIoomErrorPdsHandling fails

- modules/platforms/cpp/core-test/src/ignition_test.cpp
- modules/platforms/cpp/core/src/ignition.cpp
Added java options to make it possible to start Apache Ignite node on Java 15+ from Ignite C++.
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guideline …
> IGNITE-17708: Add support for Java 15+ to Ignite C++

- modules/core/src/main/java/org/apache/ignite/cdc/CdcConsumer.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/WalRecordsConsumer.java
> IGNITE-18249 Check for CDC consumer liveness added

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyCountersTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/PartitionUpdateCounterTrackingImpl.java
> IGNITE-17908 Fix incorrect counters set during binary restore

- modules/core/src/main/java/org/apache/ignite/cache/QueryEntity.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ValidationOnNodeJoinUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryField.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QuerySchema.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryUtils.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/QueryEntityAliasesTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteCacheQuerySelfTestSuite6.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTest.Base.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTest.Misc.cs
> IGNITE-17041 Fixed SQL query entity aliases validation.

- modules/core/src/test/java/org/apache/ignite/internal/metric/IoStatisticsSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-15737
> IGNITE-15737 IoStatisticsSelfTest#testPersistentIOGlobalStat failure.

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/LocalDateTimeSupportTest.java
> IGNITE-18303 Calcite: Fix nanoseconds flakiness in LocalDateTimeSupportTest. Speed up this test.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/aware/SegmentCurrentStateStorage.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/file/IgnitePdsThreadInterruptionTest.java
https://issues.apache.org/jira/browse/IGNITE-17719
> IGNITE-17719 IgnitePdsThreadInterruptionTest#testInterruptsOnWALWrite hangs

- modules/core/src/test/java/org/apache/ignite/internal/processors/database/IgniteDbPutGetAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-18334 …
> IGNITE-18334 Make IgniteDbPutGetAbstractTest#testRandomRemove() actually use random order

- .github/workflows/commit-check.yml
> IGNITE-18353 Add specific version of tox in order to fix strange behaviour of new version

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/aware/SegmentArchiveSizeStorage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/aware/SegmentAware.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/WalDeletionArchiveAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/aware/SegmentAwareTest.java
https://issues.apache.org/jira/browse/IGNITE-18364
> IGNITE-18364 Forcibly released the reservation of the WAL segments required by the checkpoint

- modules/core/src/main/java/org/apache/ignite/internal/LongJVMPauseDetector.java
> Revert "IGNITE-17945 Change message in case watchdog thread observes freeze"

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcNonDefaultWorkDirTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite2.java
> IGNITE-18403 Fix usage of explicit work dir for CDC

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/IdleVerify.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- Save output to control-utility.log
- Create dump file if conflicts are existed (not only in exception case) …
> IGNITE-17384 Print partition conflicts into control-utility.log

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/startup/cmdline/CdcCommandLineStartup.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcNonDefaultWorkDirTest.java
> IGNITE-18404 Stop CDC consumer in shutdown hook

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
> IGNITE-18436 Skip deleting snpshot files on client nodes

- modules/ducktests/tests/docker/ducker-ignite
Run the extra setup script not only on the 1st docker node, but on all ones.
It's needed say if some extra python packages need to be installed on all nodes.
-----------
- [How to …
> IGNITE-18459 [ducktests] Run extra setup script on all docker nodes

- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/docker/requirements-dev.txt
- modules/ducktests/tests/docker/requirements.txt
- modules/ducktests/tests/ignitetest/utils/version.py
- modules/ducktests/tests/setup.py
Update version of pytest and ducktape packages
Update LATEST ignite version upto 2.14.0
------
- [Coding …
> IGNITE-18460 [ducktests] Bump python packages and LATEST ignite versions

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
> IGNITE-18463 Fixed cancel a snapshot if one snapshot path is configured for several nodes

- modules/core/src/main/java/org/apache/ignite/startup/cmdline/CdcCommandLineStartup.java
> IGNITE-18473 Add InterruptedException handling in CdcCommandLineStartup#main

- modules/compress/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotCompressionBasicTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
> IGNITE-18199 Implement punching holes in snapshot restoration process.

- docs/_docs/monitoring-metrics/system-views.adoc
> IGNITE-18519 Change parameter name in the SQL Query view docs

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/DynamicCacheChangeRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/PlatformCacheManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/callback/PlatformCallbackGateway.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheP2pUnmarshallingNearErrorTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/near/GridCacheNearDynamicStartTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/eviction/paged/PageEvictionMultinodeAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/eviction/paged/Random2LruNearEnabledPageEvictionMultinodeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/eviction/paged/RandomLruNearEnabledPageEvictionMultinodeTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite2.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Platform/PlatformCacheTopologyChangeTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/Platform/PlatformCacheManager.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/UnmanagedCallbacks.cs
> IGNITE-18494 Fix ignoring near cache configuration while starting cache not from affinity node

- docs/_docs/sql-reference/operational-commands.adoc
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/query/KillCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/query/KillSubcommand.java
- modules/control-utility/src/test/java/org/apache/ignite/testsuites/IgniteControlUtilityTestSuite.java
- modules/control-utility/src/test/java/org/apache/ignite/util/KillCommandsControlShTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/sql/SqlCommandProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/sql/SqlKeyword.java
- modules/core/src/main/java/org/apache/ignite/internal/sql/SqlParser.java
- modules/core/src/main/java/org/apache/ignite/internal/sql/command/SqlKillClientCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/client/VisorClientConnectionDropTask.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/QueryParser.java
- modules/indexing/src/test/java/org/apache/ignite/util/KillCommandsMXBeanTest.java
- modules/indexing/src/test/java/org/apache/ignite/util/KillCommandsSQLTest.java
- modules/indexing/src/test/java/org/apache/ignite/util/KillCommandsTests.java
> IGNITE-18533 Management API to kill client connection

- modules/ducktests/tests/docker/requirements.txt
ducktape 0.11.x do not depend on 'filelock' any more, so 'filelock' dependency should be specified explicitely.
----------------------
- [How to …
> IGNITE-18568 [ducktests] Add explicit filelock package dependency

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinaryStructureTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Metadata/BinaryType.cs
> IGNITE-18438 .NET: Fix marshalling of nested binarizable structures with different schemas.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/util/distributed/DistributedProcess.java
- modules/core/src/main/java/org/apache/ignite/internal/util/distributed/InitMessage.java
- modules/core/src/test/java/org/apache/ignite/internal/util/DistributedProcessClientAwaitTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteUtilSelfTestSuite.java
> IGNITE-18573 DistributedProcess should have an option to await client node results

- modules/compress/src/main/java/org/apache/ignite/internal/processors/compress/CompressionProcessorImpl.java
- modules/compress/src/test/java/org/apache/ignite/internal/processors/compress/CompressionProcessorTest.java
- modules/platforms/cpp/core/src/jni/os/linux/utils.cpp
- modules/platforms/cpp/core/src/jni/os/win/utils.cpp
> IGNITE-18584 Enlarge compression buffer in order to provide sufficient space for compressors.

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/cdc/CountingCdcConsumer.java
- modules/ducktests/tests/ignitetest/services/utils/cdc/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/cdc/ignite_cdc.py
- modules/ducktests/tests/ignitetest/services/utils/ducktests_service.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/data_storage.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py
- modules/ducktests/tests/ignitetest/services/utils/jvm_utils.py
- modules/ducktests/tests/ignitetest/services/utils/templates/bean.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/client_configuration_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/ignite.xml.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/ignite_configuration_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/misc_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/thin_client_config.xml.j2
- modules/ducktests/tests/ignitetest/tests/cdc/__init__.py
- modules/ducktests/tests/ignitetest/tests/cdc/cdc_test.py
- modules/ducktests/tests/ignitetest/tests/control_utility/consistency_test.py
- modules/ducktests/tests/ignitetest/tests/snapshot_test.py
- modules/ducktests/tests/ignitetest/utils/bean.py
* Add a basic smoke test for CDC
* Make changes in configuration files templates to be able to create tests for CDC extensions
****
- [How to …
> IGNITE-18387 [ducktests] Added basic test for the CDC

- modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcSelfTest.java
> IGNITE-14450 Add Maximum CDC directory size configuration parameter

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/WalRecordsConsumer.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/cdc/CdcIndexRebuildTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite3.java
> IGNITE-18652 Fix segments not removed from CDC in case no DataEntry

- modules/tools/pom.xml
> IGNITE-18335 update dependency Ant

- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerMetrics.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerNioListener.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/odbc/ClientListenerMetricsTest.java
> IGNITE-17554 Fixed the metric for the number of active client sessions.

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
> IGNITE-18724 Fixed broken JavaDoc because of incorrect CFG_VIEW link.

- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/IndexQueryCriteriaClosure.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryInCriterionTest.java
> IGNITE-18725 Fix skips criteria check after first IN clause

- docs/_docs/net-specific/net-java-services-execution.adoc
> IGNITE-18779 Fixed a typo in doc

- docs/_docs/net-specific/net-platform-interoperability.adoc
> IGNITE-18780 Remove note in docs about Services being unsupported in mixed-platform clusters

- modules/compress/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotCompressionBasicTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreSelfTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/common/GridCommonAbstractTest.java
> IGNITE-18764 Restore marshaller data from snapshot

- modules/core/src/main/java/org/apache/ignite/internal/IgniteComputeHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteComputeImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/closure/GridClosureProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformCompute.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformFullTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformFutureUtils.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/ComputeApiTest.cs
> IGNITE-18750 .NET: Fix task options not being reset after task execution

- modules/clients/src/test/java/org/apache/ignite/common/RunningQueryInfoCheckInitiatorTest.java
- modules/clients/src/test/java/org/apache/ignite/internal/jdbc2/JdbcConnectionSelfTest.java
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinConnectionSelfTest.java
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinDataSourceSelfTest.java
- modules/clients/src/test/java/org/apache/ignite/qa/query/WarningOnBigQueryResultsTest.java
- modules/core/src/main/java/org/apache/ignite/cache/query/SqlFieldsQuery.java
- modules/core/src/main/java/org/apache/ignite/internal/jdbc/thin/ConnectionPropertiesImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/jdbc2/JdbcConnection.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite2.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite3.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite4.java
> IGNITE-18719 Deprecate SqlFieldsQuery#lazy and set default to true.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotFutureTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotRestoreTest.java
> IGNITE-18150 Incremental snapshot restores binary and marshaller meta

- modules/opencensus/src/test/java/org/apache/ignite/internal/processors/monitoring/opencensus/OpenCensusSqlNativeTracingTest.java
> IGNITE-18825 Fixed OpenCensusSqlNativeTracingTest#testDistributedJoin test.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/CacheStripedExecutor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/AbstractIncrementalSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotRestoreTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteIncrementalSnapshotRestoreWithIndexingTest.java
> IGNITE-18837 CacheStripedExecutor should handle execution error

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/io/gridnioserver/GridNioClientConnectionMultiplexer.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientPartitionAwarenessUnstableTopologyTest.java
> IGNITE-18826 Java thin client: fixed the pending requests race on close

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotAwareMessage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotMarkWalFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxHandler.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/AbstractIncrementalSnapshotBlockingTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotJoiningClientTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotRestoreTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IncrementalSnapshotsTestSuite.java
> IGNITE-18109 ConsistentCut ignores joining nodes 

- modules/core/src/main/java/org/apache/ignite/internal/managers/systemview/walker/SnapshotViewWalker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotMetadata.java
- modules/core/src/main/java/org/apache/ignite/spi/systemview/view/SnapshotView.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
> IGNITE-18876 Add incremental snapshots to snapshot view

- modules/core/src/main/java/org/apache/ignite/cache/store/jdbc/CacheAbstractJdbcStore.java
- modules/core/src/main/java/org/apache/ignite/cache/store/jdbc/JdbcTypesDefaultTransformer.java
- modules/core/src/test/java/org/apache/ignite/cache/store/jdbc/CacheJdbcPojoStoreTest.java
- modules/core/src/test/java/org/apache/ignite/cache/store/jdbc/model/Logo.java
- modules/core/src/test/java/org/apache/ignite/cache/store/jdbc/model/LogoKey.java
Added proper data type handling when CLOB and BLOB data types used in CacheJdbcPojoStore.
- [Coding …
> IGNITE-18849 Add LOB and BLOB fields support to CacheJdbcPojoStore

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotMXBeanImpl.java
- modules/core/src/main/java/org/apache/ignite/mxbean/SnapshotMXBean.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotMXBeanTest.java
> IGNITE-18934 Restore incremental snapshot with SnapshotMXBean

- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/jvm_utils.py
> IGNITE-18936 [ducktests] Fix parsing of the control.sh baseline command output and store JVM error file

- docs/_docs/tools/control-script.adoc
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheClear.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheCommandList.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheSubcommands.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClearCachesTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClearCachesTaskArg.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClearCachesTaskResult.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_cache_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_cache_help.output
> IGNITE-18546 Add cache clear command to control.sh

- modules/clients/src/test/java/org/apache/ignite/common/AbstractEventSecurityContextTest.java
- modules/clients/src/test/java/org/apache/ignite/common/CacheCreateDestroyEventSecurityContextTest.java
- modules/clients/src/test/java/org/apache/ignite/common/CacheEventSecurityContextTest.java
- modules/clients/src/test/java/org/apache/ignite/common/ComputeTaskRemoteSecurityContextTest.java
- modules/clients/src/test/java/org/apache/ignite/jdbc/JdbcAuthorizationTest.java
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinConnectionAdditionalSecurityTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityProcessor.java
- modules/core/src/main/java/org/apache/ignite/plugin/security/SecurityPermission.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/AbstractSecurityTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/InvalidServerTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestCertificateSecurityProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityContext.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityData.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityProcessor.java
- modules/core/src/test/java/org/apache/ignite/platform/PlatformStartIgniteUtils.java
- modules/indexing/src/test/java/org/apache/ignite/internal/systemview/SystemViewSecurityTest.java
- modules/rest-http/src/test/java/org/apache/ignite/internal/processors/rest/protocols/http/jetty/RestProcessorAuthorizationTest.java
> IGNITE-18923 Added authorization of user management operations.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotFutureTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotMetadata.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotMetadataVerificationTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotCheckBeforeRestoreTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotRestoreTest.java
> IGNITE-18967 Fix inc snapshot directories structure

- modules/compress/pom.xml
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/IgnitePdsWithTtlExpirationOnDeactivateTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite.java
> IGNITE-18935 Fix late stopping of TTL workers during deactivation leads to corrupted PDS

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheClear.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
> IGNITE-18546 Add confirmation for control.sh cache clear command

- modules/direct-io/pom.xml
> IGNITE-18988 Add missing test dependencies to direct-io

- modules/yardstick/config/benchmark-inc-snapshot.properties
- modules/yardstick/config/ignite-config-incremental-snapshots.xml
- modules/yardstick/src/main/java/org/apache/ignite/yardstick/cache/IgniteIncrementalSnapshotsBenchmark.java
> IGNITE-18877 Add yardstick benchmark for incremental snapshots

- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAbstractSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/GridRestProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/GridRestCommandHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/GridRestCommandHandlerAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/cluster/GridBaselineCommandHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/cluster/GridChangeClusterStateCommandHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/cluster/GridChangeStateCommandHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/cluster/GridClusterNameCommandHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/user/UserActionCommandHandler.java
- modules/rest-http/src/test/java/org/apache/ignite/internal/processors/rest/protocols/http/jetty/RestProcessorAuthorizationTest.java
> IGNITE-18980 Fixed REST status code in case of failed request

- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/odbc/OdbcUtils.java
- modules/platforms/cpp/odbc-test/src/meta_queries_test.cpp
> IGNITE-18993 ODBC: Fix handling of single quotes

- modules/clients/src/test/java/org/apache/ignite/common/ComputeTaskPermissionsTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/resource/GridResourceProxiedIgniteInjector.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/GridSecurityProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurity.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/NoOpIgniteSecurityProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/SecurityUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/GridTaskProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/GridTaskWorker.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityProcessor.java
> IGNITE-18910 Added ability for Security Plugin to extend pool of Ignite system types.

- docs/_docs/monitoring-metrics/new-metrics.adoc
- docs/_docs/tools/control-script.adoc
specified hitrate metrics in /monitoring-metrics/new-metrics
added info about metric name in tools/control-script
> Fix metric configuration documentation

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotStreamerTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/AbstractIncrementalSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotCheckBeforeRestoreTest.java
> IGNITE-19060 Fixed snapshot operation NPE on a client node

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
> IGNITE-19052 Introduce IncrementalSnapshotProcessor

- .asf.yaml
* Disallow force pushes.
* Require linear history (no merge commits).
* Require review approval.
More info: https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
> IGNITE-19123 Enable master branch protection

- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/Snapshots.java
- docs/_docs/monitoring-metrics/system-views.adoc
- docs/_docs/snapshots/snapshots.adoc
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> IGNITE-18927 Add incremental snapshot docs

- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/path.py
Fix modules classpaths in dev-mode.
Add more extension abilities for 3rd party modules via 3rd party specs.
---
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribut …
> IGNITE-19140 [ducktests] Fix classpaths for modules in IgniteSpec

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/CommandHandler.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotRestoreCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotRestoreCommandOption.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotVerificationTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotHandlerContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotHandlerRestoreTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotMXBeanImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyTaskArg.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyTaskResult.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotRestoreTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotRestoreTaskArg.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotCheckBeforeRestoreTest.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output
> IGNITE-19144 Check flag for snapshot restore implemented

- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
> IGNITE-19175 [ducktests] Add logging support to NONE service type

- modules/tools/src/main/java/org/apache/ignite/tools/surefire/testsuites/OrphanedTestCollection.java
> IGNITE-19236 orphaned_tests.txt location calculation simplification

- modules/ducktests/pom.xml
- modules/sqlline/pom.xml
- parent/pom.xml
> IGNITE-19237 Dependency copying should happed on package phase instead of test-compile

- modules/tools/src/main/java/org/apache/ignite/tools/surefire/testsuites/OrphanedTestCollection.java
> IGNITE-19253 [Missing Tests] check fails on windows agents

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotRestoreTest.java
> IGNITE-19252 The incremental snapshot restore operation fails if there is a node not from the baseline.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotTest.java
> IGNITE-19248 Fixed snapshot restore hanging if the prepare stage fails.

- .github/workflows/sonar-branch.yml
- .github/workflows/sonar-pr-from-fork.yml
> IGNITE-19266 Use maven_opts for sonar analysis

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheIoManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheMessage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCachePartitionExchangeManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTransactionalCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridDhtAtomicCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/colocated/GridDhtColocatedCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearAtomicCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTransactionalCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheDistributedQueryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxEntry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/dht/IgniteCacheRecreateTest.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/GridCacheMessageSelfTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheRestartTestSuite2.java
> IGNITE-19115 Fixed handling cache messages for recreated cache

- modules/core/src/main/java/org/apache/ignite/internal/cluster/IgniteClusterImpl.java
- modules/core/src/main/java/org/apache/ignite/plugin/security/SecurityPermission.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/cluster/ClusterNodeOperationPermissionTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityContext.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
…erations. (#10644)
(cherry picked from commit f5e69ba922c80ce059658db7483fb3dee584e978)
- [Coding …
> Added authorization of Ignite Cluster Node start/stop operations.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotTest.java
> IGNITE-19257 Fixed snapshot restore rollback if start cache stage failed.

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessorTest.java
- modules/core/src/main/java/org/apache/ignite/cache/query/SqlFieldsQuery.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
- modules/indexing/src/test/java/org/apache/ignite/client/FunctionalQueryTest.java
> IGNITE-19350 Fixed assertion error in case of empty SQL query

- docs/_docs/tools/control-script.adoc
- modules/control-utility/pom.xml
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheCreate.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheSubcommands.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/control-utility/src/test/resources/config/cache/cache-create-correct.xml
- modules/control-utility/src/test/resources/config/cache/cache-create-no-configs.xml
- modules/core/src/main/java/org/apache/ignite/internal/visor/cache/VisorCacheCreateTask.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_cache_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_cache_help.output
> IGNITE-19379 Control.sh: added the cache create command

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> IGNITE-19380 Fixed NPE on snapshot create operation for in-memory cluster

- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerNioListener.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/ListLogger.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientTestBase.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/Log/dotnet-log4j.xml
> IGNITE-19421 Added extended debug logging of client connections

- .github/workflows/commit-check.yml
> IGNITE-19463 Checkout pull request HEAD commit instead of merge commit on GitHub actions check

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxStateImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridIntList.java
> IGNITE-19445 NPE during transaction recovery

- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/communication.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/data_storage.py
- modules/ducktests/tests/ignitetest/services/utils/templates/datastorage_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/transaction_macro.j2
> IGNITE-19554 [ducktests] Add more config params for communication and data storage

- modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityProcessor.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/DiscoveryNotification.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
- modules/core/src/test/java/org/apache/ignite/NodeSecurityContextTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/IgniteSecurityProcessorTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/NodeSecurityContextPropagationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/client/ClientReconnectTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryImpl.java
> IGNITE-19410 Fixed node crash due to SecurityContext not being found during discovery message processing.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotMetricsTest.java
> IGNITE-19564 : Snapshot restoration metric is not always assigned when an error occurs.

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotStreamerTest.java
> IGNITE-19607 : Flaky test fix - testStreamingIntoInMemoryDoesntAffectSnapshot()

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/QueryRegistryImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheDistributedQueryFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheDistributedQueryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/performancestatistics/PerformanceStatisticsProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridRunningQueryInfo.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/RunningQueryManager.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridReduceQueryExecutor.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/performancestatistics/PerformanceStatisticsQueryTest.java
(cherry picked from commit 9eaae91e0a54bd984db542354d190643d56d2b0d) …
> IGNITE-19628 Add IndexQuery to performance statistics

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/io/gridnioserver/GridNioClientConnectionMultiplexer.java
> IGNITE-19715 Thin client socket#open timeout changed to ClientConfiguration#timeout property.

- modules/core/src/main/java/org/apache/ignite/cache/query/IndexQuery.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ProtocolBitmaskFeature.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheProxyImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientBitmaskFeature.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheIndexQueryRequest.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryLimitTest.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryTestSuite.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/ThinClientIndexQueryTest.java
> IGNITE-16619 IndexQuery should support limit

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/control-utility/src/test/resources/config/cache/cache-create-with-spel.xml
- modules/core/src/main/java/org/apache/ignite/internal/util/spring/IgniteSpringHelper.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/cache/VisorCacheCreateTask.java
- modules/spring/src/main/java/org/apache/ignite/internal/util/spring/IgniteSpringHelperImpl.java
> IGNITE-19742 Disabled Spring expressions in the cache create command.

- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinMetadataSelfTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/SystemViewCommandTest.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/systemview/SystemViewMBean.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/systemview/walker/ServiceViewWalker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/service/ServiceInfo.java
- modules/core/src/main/java/org/apache/ignite/spi/systemview/view/ServiceView.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/JmxExporterSpiTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/metric/SqlViewExporterSpiTest.java
> IGNITE-19766 Added topology snapshot info to services system view

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxLocalAdapter.java
> IGNITE-19845 IgniteTxLocalAdapter.sndTransformedVals field removal

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxLocal.java
> IGNITE-19874 GridDhtTxLocal initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxDataConsistencyOnCommitFailureTest.java
> IGNITE-19873 GridNearTxLocal initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxLocalAdapter.java
> IGNITE-19872 IgniteTxLocalAdapter initial cleanup

- RELEASE_NOTES.txt
> IGNITE-17651 Update Ignite 2.14 release notes

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/cdc/CdcBuffer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/cdc/CdcBufferConsumer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/cdc/CdcProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/cdc/CdcWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FileHandleManagerFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FileHandleManagerImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FileWriteHandleImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FsyncFileHandleManagerImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FsyncFileWriteHandle.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/cdc/RealtimeCdcBufferDedicatedWorkerTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/cdc/RealtimeCdcBufferSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/cdc/RealtimeCdcBufferTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/cdc/RealtimeCdcBufferWalMmapDisabledTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite2.java
> IGNITE-19622 Add realtime CDC buffer

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/RealtimeCdcRecord.java
- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/RealtimeCdcStopRecord.java
- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/WALRecord.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/cdc/CdcBuffer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/cdc/CdcProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/cdc/CdcWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordDataV1Serializer.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/cdc/RealtimeCdcBufferTest.java
> IGNITE-19639 Add realtime CDC records

- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinConnectionSSLTest.java
- modules/core/src/main/java/org/apache/ignite/ssl/AbstractSslContextFactory.java
- modules/core/src/main/java/org/apache/ignite/ssl/SslContextFactory.java
> IGNITE-19975 Introduced abstract SSL Context Factory.

- modules/core/src/main/java/org/apache/ignite/internal/management/performancestatistics/PerformanceStatisticsRotateCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/management/performancestatistics/PerformanceStatisticsStartCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/management/performancestatistics/PerformanceStatisticsStopCommand.java
- modules/ducktests/tests/ignitetest/services/utils/path.py
- modules/ducktests/tests/ignitetest/tests/control_utility/perf_stat_test.py
control.sh --performance-statistics subcommands (start, stop, rotate) are fixed to print operation status after completion.
----
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE …
> IGNITE-19746 Print result of the control.sh performance statistics subcommands

- docs/_docs/restapi.adoc
> IGNITE-20008 FIxed awkward code boxes in rest docs

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientCacheAffinityContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCachePartitionAwarenessGroup.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientPartitionAwarenessStableTopologyTest.java
> IGNITE-20038 [Thin Clients] Fixed broken ClientCachePartitionAwarenessGroup serialization.

- modules/ducktests/pom.xml
- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/jvm_utils.py
- modules/ducktests/tests/ignitetest/services/utils/templates/ignite_configuration_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/misc_macro.j2
* To test the new calcite sql query engine the sqlConfiguration field in ignite configuration should be added.
* Add ability to run arbitrary control.sh subcommand.
* It appears that `pgrep` on some linuxes (centos) cuts long command lines (say with long list of jars in classpath), so ducktape fails to detect the PID of the service java process. Rewrite via the `ps`.
* One of the source of long command lines was a bug that IgniteSpec adds modules to service modules list each time the new node started. So say the 6th node gets command line with jar modules mentioned 6 times.
---
The description explains _WHAT_ and …
> IGNITE-19729 [ducktests] Add calcite support and ability to run arbitrary control.sh subcommand, fix PID detection

- docs/_docs/configuring-caches/configuration-overview.adoc
> IGNITE-19647 Cleared up Cache Template docs

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxRemoteAdapter.java
> IGNITE-20084 GridDistributedTxRemoteAdapter initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTransactionalCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxRemote.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxEnlistFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxQueryResultsEnlistFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxHandler.java
> IGNITE-20088 GridDhtTxRemote initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxImplicitSingleStateImpl.java
> IGNITE-20112 IgniteTxImplicitSingleStateImpl initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxStateImpl.java
> IGNITE-20113 IgniteTxStateImpl initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxHandler.java
> IGNITE-20123 IgniteTxHandler initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/util/GridIntList.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridLongList.java
> IGNITE-20143 GridIntList initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/colocated/GridDhtColocatedLockFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearLockFuture.java
> IGNITE-20141 Transaction will never become finished on timeout when deadlock detection is disabled.

- modules/core/src/main/java/org/apache/ignite/internal/util/future/GridCompoundFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/util/future/GridFutureAdapter.java
> IGNITE-20173 GridCacheCompoundIdentityFuture and it's ancestors initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/CacheDistributedGetFutureAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridPartitionedGetFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearGetFuture.java
> IGNITE-20174 CacheDistributedGetFutureAdapter and it's descendants initial cleanup

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTransactionalCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxAbstractEnlistFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxEnlistFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxQueryAbstractEnlistFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxQueryEnlistFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxQueryResultsEnlistFuture.java
> IGNITE-20176 GridNearTxAbstractEnlistFuture and it's descendants initial cleanup

- parent/pom.xml
> IGNITE-20145 Update surefire version

- modules/core/src/main/java/org/apache/ignite/internal/management/api/CommandUtils.java
> IGNITE-20228 Fix connectable nodes list for control.sh

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/RexImpTable.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/IgniteSqlToRelConvertor.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/schema/CacheTableDescriptorImpl.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/TableDmlIntegrationTest.java
> IGNITE-20253 SQL Calcite: Replace placeholder values from ModifyNode (backport of IGNITE-19096)

- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/GridMetricManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/impl/MetricUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/MetricConfigurationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/MetricsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite2.java
> IGNITE-20201 Fix availability to set configuration for unregistered metrics

- .github/workflows/sonar-pr-from-fork.yml
> IGNITE-20274 github action must rely on environment variables to run agains the source code

- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
> IGNITE-18830 Optimize log in GridQueryProcessor

- docs/_docs/includes/java9.adoc
> IGNITE-20314 Updated opens for Java 17

- parent/pom.xml
> IGNITE-20407 Update Ignite dependency: Snappy-java to 1.1.10.3

- parent/pom.xml
> IGNITE-20413 Update ignite dependency: zstd

- docs/_data/toc.yaml
- docs/_docs/installation/upgrades.adoc
> IGNITE-20431 Added basic info on version upgrade

- docs/_docs/installation/kubernetes/generic-configuration.adoc
- docs/_docs/restapi.adoc
> IGNITE-20440 Add docs for REST probe

- docs/_docs/installation/upgrades.adoc
> IGNITE-20460 Added license to file

- parent/pom.xml
> IGNITE-20490 Update the snappy dependency up to the latest 1.1.10.4

- parent/pom.xml
> IGNITE-20517 Update Ignite dependency: Jetty

- modules/core/src/main/java/org/apache/ignite/internal/mem/file/MappedFile.java
> IGNITE-20515 Fix MappedFile.map for JDK 14 and newer.

- bin/include/jvmdefaults.bat
- bin/include/jvmdefaults.sh
- deliveries/docker/apache-ignite/run.sh
- modules/core/src/main/java/org/apache/ignite/internal/util/FeatureChecker.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java
- modules/platforms/cpp/core/src/ignition.cpp
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/Jvm.cs
- parent/pom.xml
> IGNITE-20532 Fix JavaNioAccess handling in JDK 14 and later.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/sandbox/AbstractSandboxTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/sandbox/CacheStoreFactorySandboxTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
> IGNITE-20543 Wrap CacheStore creation to sandbox

- parent/pom.xml
> IGNITE-20581 Update ignite dependency: Spring

- modules/opencensus/pom.xml
- parent/pom.xml
> IGNITE-20583 add test scope ignite dependency: opencensus

- modules/calcite/pom.xml
- modules/cassandra/store/pom.xml
- modules/core/pom.xml
- parent/pom.xml
> IGNITE-20571 Update ignite dependency: guava

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/EncryptedSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
> IGNITE-20601 Support custom location for cache dumps

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/CacheScanTask.java
> IGNITE-20602 Fixed cache scan command page size to meet the limit argument

- parent/pom.xml
> IGNITE-20626 updated jetty version

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/dump/DumpUtility.java
- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/services/utils/dump_utility.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/tests/dump_test.py
Add ducktest for cache dump functionality
*** …
> IGNITE-20470 [ducktests] Add test for the cache dump

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryEventBuffer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/continuous/GridContinuousProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/continuous/TestCacheConrinuousQueryUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/continuous/ContinuousQueryBuffersCleanupTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite13.java
> IGNITE-11970 Fixed cleanup of CQ entry buffers.

- modules/ducktests/tests/ignitetest/tests/control_utility/perf_stat_test.py
> IGNITE-20689 [ducktests] Fix a ﬂaky perf_stat_test

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/DataGenerationApplication.java
- modules/ducktests/tests/ignitetest/tests/rebalance/in_memory_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/persistent_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/util.py
- modules/ducktests/tests/ignitetest/tests/util.py
> IGNITE-20682 [ducktests] Add the extention point to the rebalance tests

- modules/core/src/main/java/org/apache/ignite/dump/DumpReader.java
- modules/core/src/main/java/org/apache/ignite/dump/DumpReaderConfiguration.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelfTest.java
> IGNITE-20708 Support cacheGroupNames for DumpReader

- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/UsingScanQueries.java
The modification of the code before this point will lead to an NotSerializableException. I have placed the process of creating a Map in the code outside instead of using an anonymous class.
> IGNITE-20552 Fix ScanQuery code snippet.

- modules/core/src/main/java/org/apache/ignite/internal/processors/datastructures/GridCacheLockImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/IgniteLockAbstractSelfTest.java
> IGNITE-20730 Fix IgniteLock cannot be acquired after release on JDK 17

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexForceRebuildTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexRebuildStatusTest.java
- modules/core/src/main/java/org/apache/ignite/cache/CacheMetrics.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/IndexForceRebuildTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/IndexRebuildStatusInfoContainer.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/IndexRebuildStatusTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheGroupMetricsImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheMetricsImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheMetricsSnapshot.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheMetricsSnapshotV2.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/impl/IntMetricImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaIndexCachePartitionWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaIndexCacheVisitorImpl.java
- modules/core/src/test/java/org/apache/ignite/platform/PlatformCacheWriteMetricsTask.java
> IGNITE-20627 Added number of partitions processed by the index worker to the output of the index_rebuild_status command.

- modules/core/src/main/java/org/apache/ignite/internal/IgniteKernal.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneIgnitePluginProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
> IGNITE-20744 StandaloneContext should not load plugins from classpath

- modules/compress/src/test/java/org/apache/ignite/internal/processors/cache/transform/CacheObjectCompressionConsumptionTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCachePutAllConflictRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheRemoveAllConflictRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/streamer/ClientDataStreamerAddDataRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/streamer/ClientDataStreamerReader.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/streamer/ClientDataStreamerStartRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformUtils.java
> IGNITE-20746 Cache objects transformation never happen on TcpIgniteClient.putAllConflict()

- parent/pom.xml
> IGNITE-20711 Update Ignite dependency: Apache Commons Codec to 1.16.0

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/io/gridnioserver/GridNioClientConnectionMultiplexer.java
https://issues.apache.org/jira/browse/IGNITE-20740
> IGNITE-20740 Fix SocketChannel leak when connection fails

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/ducktests/tests/ignitetest/services/utils/cdc/ignite_cdc.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/metrics/metrics.py
- modules/ducktests/tests/ignitetest/services/utils/templates/ignite.xml.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/misc_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/opencensus_metrics_beans_macro.j2
- modules/ducktests/tests/ignitetest/utils/bean.py
> IGNITE-20719 [ducktests] Allow CDC tests work with opencensus HTTP metrics exporter

- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/MetricsConfigurationTest.java
> IGNITE-18434 : Сustom histogram buckets not applied after restart

- docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc
> IGNITE-20804 Support custom conflict resolver at CDC based datacenter replication

- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/SecurityContext.java
- modules/core/src/main/java/org/apache/ignite/plugin/security/SecuritySubject.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/cluster/NodeJoinPermissionsTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityPluginProvider.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityProcessor.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/ZookeeperDiscoverySpiTestSuite4.java
> IGNITE-19807 Deprecated legacy authorization approach through Security Context.

- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/SecurityContext.java
- modules/core/src/main/java/org/apache/ignite/plugin/security/SecuritySubject.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/cluster/NodeJoinPermissionsTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityPluginProvider.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityProcessor.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/ZookeeperDiscoverySpiTestSuite4.java
(cherry picked from commit aba0aaa5b8dd36ac7ff1329bd99c7753cea1dcde) …
> IGNITE-19807 Deprecated legacy authorization approach via Security Context. (#10800)

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/AbstractWalRecordsIterator.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/SingleSegmentLogicalRecordsIterator.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIterator.java
> IGNITE-20822 Filter by higherBound in AbstractWalRecordsIterator

- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
- modules/core/src/main/java/org/apache/ignite/internal/util/nio/ssl/BlockingSslHandler.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/GridNioServerWrapper.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/TcpHandshakeExecutor.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/GridTcpCommunicationSpiAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/TcpCommunicationHandshakeTimeoutTest.java
>  IGNITE-20759 Fix writing post-handshake message on server

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/BinaryMetadataFileStore.java
> IGNITE-20572 BinaryMeta file atomic creation

- docs/_config.yml
- docs/_docs/code-snippets/java/pom.xml
- modules/checkstyle/pom.xml
- modules/core/src/main/resources/ignite.properties
- modules/dev-utils/ignite-modules-test/build.gradle
- modules/ducktests/tests/ignitetest/__init__.py
- modules/platforms/cpp/CMakeLists.txt
- modules/platforms/dotnet/SharedAssemblyInfo.cs
- parent/pom.xml
> IGNITE-20929 Update Ignite version to 2.17.0-SNAPSHOT

- docs/_config.yml
- docs/_docs/code-snippets/java/pom.xml
- modules/checkstyle/pom.xml
- modules/core/src/main/resources/ignite.properties
- modules/dev-utils/ignite-modules-test/build.gradle
- modules/ducktests/tests/ignitetest/__init__.py
- modules/platforms/cpp/CMakeLists.txt
- modules/platforms/dotnet/SharedAssemblyInfo.cs
- parent/pom.xml
> IGNITE-20928 Update ignite-2.16 branch version to 2.16.0

- packaging/deb/changelog
- packaging/rpm/apache-ignite.spec
> IGNITE-20932 Update Linux packages version to 2.16

- bin/include/jvmdefaults.bat
- bin/include/jvmdefaults.sh
> IGNITE-20947 Fix misprint in add-opens of sun.util.calendar for java 15+

- modules/core/src/main/java/org/apache/ignite/dump/DumpEntry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/CreateDumpFutureTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/DumpEntrySerializer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/IdleVerifyUtility.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
> IGNITE-20917 Add entry version to DumpEntry

- docs/_docs/includes/java9.adoc
> IGNITE-20748 Updated java opens

- modules/clients/src/test/java/org/apache/ignite/common/AbstractEventSecurityContextTest.java
- modules/clients/src/test/java/org/apache/ignite/common/ClusterStateChangeEventSecurityContextTest.java
- modules/clients/src/test/java/org/apache/ignite/internal/client/suite/IgniteClientTestSuite.java
- modules/core/src/main/java/org/apache/ignite/events/ClusterStateChangeStartedEvent.java
- modules/core/src/main/java/org/apache/ignite/events/EventType.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
> IGNITE-21015 Add the security subject ID to the cluster state change event

- modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/SecurityCommandHandlerPermissionsTest.java
- modules/control-utility/src/test/java/org/apache/ignite/testsuites/IgniteControlUtilityTestSuite2.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/CacheCreateTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/CacheScanTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/CacheStopTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClearCachesTask.java
> IGNITE-21021 Removed ADMIN_OPS permissions check for cache operations executed via Control Utility.

- parent/pom.xml
> IGNITE-21029 Update Ignite dependency log4j2

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/CreateDumpFutureTask.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
> IGNITE-21042 Move CreateDumpFutureTask#toLong to utils

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/FilteredRecord.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIterator.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordV1Serializer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordV2Serializer.java
> IGNITE-21041 Make FilteredRecord instance singleton for RecordSerializer

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/WalRecordsConsumer.java
> IGNITE-17700 Make WalRecordsConsumer inheritable

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/CacheObjectBinaryProcessorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cacheobject/IgniteCacheObjectProcessor.java
…tProcessor
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rul …
> IGNITE-21046 Move binaryMetadataUpdateListener to basic interface

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/DumpEntrySerializer.java
> IGNITE-21056 Use thread local buffer for encrypted dump

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/cache/affinity/rendezvous/ClusterNodeAttributeAffinityBackupFilter.java
- modules/core/src/main/java/org/apache/ignite/internal/commandline/cache/distribution/CacheDistributionTask.java
- modules/core/src/main/java/org/apache/ignite/internal/commandline/cache/distribution/CacheDistributionTaskResult.java
- modules/core/src/main/java/org/apache/ignite/spi/metric/jmx/MetricRegistryMBean.java
- modules/core/src/main/java/org/apache/ignite/spi/metric/jmx/ReadOnlyDynamicMBean.java
- modules/core/src/test/java/org/apache/ignite/cache/affinity/AffinityFunctionBackupFilterAbstractSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/GridMBeansTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/LogExporterSpiTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridEvictionPolicyMBeansTest.java
> IGNITE-14823 Attribute abbrevation

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/compress/src/main/java/org/apache/ignite/internal/processors/compress/CompressionProcessorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataStorageMetricsImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/ByteBufferExpander.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/streamer/ClientDataStreamerStartRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/util/io/GridFilenameUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheMetricsCacheSizeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/IgniteThrottlingUnitTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PageMemoryImplTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/database/inlinecolumn/InlineIndexColumnTest.java
- modules/urideploy/src/main/java/org/apache/ignite/spi/deployment/uri/GridUriDeploymentJarVerifier.java
> IGNITE-14823 Buffer abbrevation

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/RexImpTable.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/RexToLixTranslator.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/externalize/RelJson.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/codegen/src/main/java/org/apache/ignite/codegen/SystemViewRowAttributeWalkerGenerator.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/GridDeploymentClassLoader.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsFullMessage.java
- modules/core/src/test/java/org/apache/ignite/ClassPathContentLoggingTest.java
- modules/core/src/test/java/org/apache/ignite/internal/MarshallerContextLockingSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryMarshallerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryObjectToStringTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/context/IgniteCacheAbstractExecutionContextTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/tostring/GridToStringBuilderSelfTest.java
- modules/core/src/test/java/org/apache/ignite/marshaller/MarshallerContextSelfTest.java
- modules/core/src/test/java/org/apache/ignite/p2p/DeploymentClassLoaderCallableTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/GridAbstractTest.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/P2PClassLoadingProblems.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/AbstractSchemaSelfTest.java
- modules/tools/src/main/java8/org/apache/ignite/tools/javadoc/IgniteLinkTaglet.java
> IGNITE-14823 Class abbrevation

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/clients/src/test/java/org/apache/ignite/internal/client/rest/GridProbeCommandTest.java
- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAbstractSelfTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/util/MavenUtils.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/CommandHandler.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerFactoryAbstractTest.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridJavaProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/rest/handlers/log/GridLogCommandHandlerTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/rest/handlers/query/GridQueryCommandHandlerTest.java
> IGNITE-14823 Command abbrevation

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/IgnitePlanner.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/compress/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotCompressionBasicTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClusterCachesInfo.java
- modules/core/src/test/java/org/apache/ignite/cache/store/jdbc/CacheJdbcPojoWriteBehindConnectionLeakTest.java
- modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
- modules/core/src/test/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManagerAttributesSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheFastNodeLeftForTransactionTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheGetCustomCollectionsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsCacheConfigurationFileConsistencyCheckTest.java
- modules/core/src/test/java/org/apache/ignite/p2p/P2PClassLoadingFailureHandlingTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractQuerySelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/stat/StatisticsViewsTest.java
> IGNITE-14823 Config abbrevation

- modules/calcite/pom.xml
> IGNITE-21085 Fixed the update versions script fails on ignite-calcite module.

- examples/pom-standalone-lgpl.xml
- examples/pom-standalone.xml
- examples/pom.xml
> IGNITE-21096 Fix standalone examples compilation

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/RexImpTable.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/defragmentation/CachePartitionDefragmentationManager.java
- modules/core/src/test/java/org/apache/ignite/internal/ThreadNameValidationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/AtomicLongTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheDataRegionConfigurationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteDiscoDataHandlingInNewClusterTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsDiscoDataHandlingInNewClusterTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/checkpoint/CheckpointListenerForRegionTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/IgniteSqlCreateTableTemplateTest.java
- modules/spring/src/test/java/org/apache/ignite/cluster/ClusterStateXmlPropertiesTest.java
> IGNITE-14823 Default abbrevation

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/RexToLixTranslator.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinConnectionSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/GridDeploymentClassLoader.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManagerImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheProxyImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/PlatformCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformUtils.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/ClientExceptionsUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheConcurrentGetCacheOnClientTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/GridCacheAbstractDataStructuresFailoverSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/IgniteLockAbstractSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteBaselineAffinityTopologyActivationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsCheckpointMapSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/IgniteWALTailIsReachedDuringIterationOverArchiveTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/crc/IgniteAbstractWalIteratorInvalidCrcTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/future/GridFutureAdapterSelfTest.java
- modules/core/src/test/java/org/apache/ignite/p2p/P2PClassLoadingFailureHandlingTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryNodeJoinAndFailureTest.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
> IGNITE-14823 Exception abbrevation

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/WalRecordsConsumer.java
- modules/core/src/test/java/org/apache/ignite/cdc/AbstractCdcTest.java
> IGNITE-21123 Add CDC event capture metric

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/AbstractWalRecordsIterator.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIterator.java
- modules/web/src/test/java/org/apache/ignite/internal/websession/WebSessionSelfTest.java
> IGNITE-14823 Header abbrevation

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcManagerTest.java
> IGNITE-21135 Fix contention between CdcManager methods

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtPartitionTopologyImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/MetricsClusterActivationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheExchangeMessageDuplicatedStateTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteMarshallerCacheClientRequestsMappingTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/CacheBaselineTopologyTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/file/IgnitePdsCheckpointSimulationWithRealCpDisabledTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/QueryDataPageScanTest.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryImpl.java
> IGNITE-14823 Initialize abbrevation

- modules/benchmarks/src/main/java/org/apache/ignite/internal/benchmarks/jmh/tree/BPlusTreeBenchmark.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexingTest.java
- modules/core/src/main/java/org/apache/ignite/cache/CachingProvider.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/TransactionMetricsAdapter.java
- modules/core/src/test/java/org/apache/ignite/internal/GridCollisionManagerLoggingSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheMetricsManageTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCachePeekModesAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/rebalancing/GridCacheRebalancingWithAsyncClearingTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/IgnitePdsWithTtlTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/checkpoint/LightweightCheckpointTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/defragmentation/LinkMapTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxWithKeyContentionSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/database/BPlusTreeReuseSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/database/CacheFreeListSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/database/IndexStorageSelfTest.java
> IGNITE-14823 Manager abbrevation

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/IgniteReleasedVersion.java
> IGNITE-20927 Update IgniteReleasedVersion for compatibility tests to 2.16.0

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/internal/plugin/IgniteLogInfoProviderImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/managers/communication/GridIoManagerFileTransmissionSelfTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryNetworkIssuesTest.java
> IGNITE-14823 Network abbrevation

- .idea/inspectionProfiles/Project_Default.xml
- modules/benchmarks/src/main/java/org/apache/ignite/internal/benchmarks/jmh/notify/JmhWaitStategyBenchmark.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/CommandHandlerParsingTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/ShutdownPolicy.java
- modules/core/src/main/java/org/apache/ignite/cache/eviction/fifo/FifoEvictionPolicyFactory.java
- modules/core/src/main/java/org/apache/ignite/cache/eviction/lru/LruEvictionPolicyFactory.java
- modules/core/src/main/java/org/apache/ignite/cache/eviction/sorted/SortedEvictionPolicyFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/IgnitionEx.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/services/PlatformServices.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/stat/StatisticsUsageState.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheLoadRebalanceEvictionSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/dht/GracefulShutdownTest.java
> IGNITE-14823 Parameter abbrevation

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteMarshallerCacheClientRequestsMappingTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/GridCacheAtomicReferenceApiSelfAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
> IGNITE-14823 Receive abbrevation

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/clients/src/test/java/org/apache/ignite/internal/client/rest/GridProbeCommandTest.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/GridDeploymentClassLoader.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/GridEncryptionManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCachePartitionExchangeManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/running/RunningQueryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/protocols/tcp/GridTcpRestNioListener.java
- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/events/FakeIgniteServer.java
- modules/core/src/test/java/org/apache/ignite/p2p/ClassLoadingProblemExceptionTest.java
- modules/core/src/test/java/org/apache/ignite/p2p/GridP2PScanQueryWithTransformerTest.java
> IGNITE-14823 Request, response abbrevation

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/ExecutionPlan.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/FragmentSplitter.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/QueryTemplate.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/Splitter.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/jdbc/JdbcConnectionContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/odbc/OdbcConnectionContext.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/dml/DmlUtils.java
> IGNITE-14823 Sender abbrevation

- modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/SecurityUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
> IGNITE-21216 Excluded tasks that are not included in the Ignite package from system tasks.

- docs/_docs/code-snippets/k8s/stateless/deployment-template.yaml
- docs/_docs/installation/kubernetes/generic-configuration.adoc
> IGNITE-17780 Updated deployment example to StatefulSet

- parent/pom.xml
> IGNITE-18242 upgrade kafka dependency

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientClusterGroupImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/ClusterGroupClusterRestartTest.java
- modules/indexing/src/test/java/org/apache/ignite/client/ClientTestSuite.java
> IGNITE-21001 Java Thin Client: Fixed stale client cluster group data after cluster restart.

- modules/opencensus/src/test/java/org/apache/ignite/internal/processors/monitoring/opencensus/AbstractTracingTest.java
- parent/pom.xml
> IGNITE-20752 Bump opencensus version to latest 0.31.1

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/WALRecord.java
- modules/core/src/test/java/org/apache/ignite/testframework/wal/record/RecordUtils.java
https://issues.apache.org/jira/browse/IGNITE-21280 …
> IGNITE-21280 Reserved new WAL record type

- docs/_docs/restapi.adoc
> IGNITE-21212 Removed cacheName parameter from rest api

- examples/src/main/java/org/apache/ignite/examples/servicegrid/ServiceMiddlewareExample.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessor.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/KillCommandDdlIntegrationTest.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/sql/SqlCustomParserTest.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/internal/managers/IgniteMBeansManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/service/IgniteServiceProcessor.java
- modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/IgniteSemaphoreAbstractSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/service/GridServiceDeployClusterReadOnlyModeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/p2p/P2PClassLoadingFailureHandlingTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryClientSuspensionSelfTest.java
- modules/core/src/test/java/org/apache/ignite/startup/servlet/GridServletLoaderTest.java
- modules/web/src/test/java/org/apache/ignite/internal/websession/WebSessionSelfTest.java
> IGNITE-14823 Service abbrevation

- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/job/GridJobProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/GridTaskProcessor.java
- modules/web/src/test/java/org/apache/ignite/internal/websession/WebSessionSelfTest.java
> IGNITE-14823 Session abbrevation

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/RexImpTable.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/RexToLixTranslator.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/metadata/ColocationGroup.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/FragmentSplitter.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/IgniteSqlToRelConvertor.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/IgniteSqlValidator.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/Splitter.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rel/AbstractIgniteJoin.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/CommandHandlerParsingTest.java
- modules/core/src/main/java/org/apache/ignite/internal/jdbc/thin/JdbcThinSSLUtil.java
- modules/core/src/main/java/org/apache/ignite/internal/util/io/GridReversedLinesFileReader.java
- modules/core/src/test/java/org/apache/ignite/cache/store/jdbc/CacheJdbcPojoWriteBehindStoreWithCoalescingTest.java
- modules/core/src/test/java/org/apache/ignite/client/ConnectionTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePersistentStoreDataStructuresTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/service/ServiceHotRedeploymentViaDeploymentSpiTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/EchoServer.java
- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/TcpCommunicationHandshakeTimeoutTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/DiscoveryClientSocketTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpClientDiscoveryUnresolvedHostTest.java
> IGNITE-14823 Sequence, socket, source abbrevations

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/StatisticsCommandDdlIntegrationTest.java
- modules/checkstyle/src/main/resources/abbrevations.csv
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/JavaThinCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/JdbcThinCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/IndexTypesCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/InlineJavaObjectCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/PersistenceBasicCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/util/MavenUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteMessagingImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/mem/file/MappedFile.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClusterCachesInfo.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FileWriteHandleImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/tree/mvcc/search/MvccFirstRowTreeClosure.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformProcessorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/stat/IgniteGlobalStatisticsManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/stat/StatisticsUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/stat/hll/HLL.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/stat/hll/serialization/SchemaVersionOne.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/stat/hll/serialization/SerializationUtil.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/ServiceAwarenessTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/IgniteProcessProxy.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/JavaVersionCommand.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/JavaVersionCommandParser.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/control_utility/LongRunningTransactionsGenerator.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/stat/StatisticsAbstractTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/stat/hll/FullHLLTest.java
> IGNITE-14823 Version, subject abbrevations

- modules/opencensus/pom.xml
- parent/pom.xml
> IGNITE-21342 Update guava and grpc in OpenCensus dependency

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2Table.java
> IGNITE-21366 AssertionError during the execution of the request

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/BufferedFileIO.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelfTest.java
> IGNITE-21449 Avoid excessive invocation of channel.position()

- modules/clients/src/test/java/org/apache/ignite/common/CacheEventSecurityContextTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
> IGNITE-14317 Fix IgniteCache.removeAsync(key,val) failure inside an optimistic transaction

- modules/core/src/main/java/org/apache/ignite/internal/LongJVMPauseDetector.java
…eDetector
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rule …
> IGNITE-21475 Replacing currentTimeMillis with nanoTime in LongJVMPauseDetector

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/management/StateCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/management/baseline/AbstractBaselineCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/management/baseline/BaselineTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/baseline/BaselineTaskResult.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/baseline/VisorBaselineViewTask.java
> IGNITE-21102 Use ClusterState enum for baseline control.sh commands output

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/Dump.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
> IGNITE-21570 Add buffer for reading files while checking cache dumps

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientCacheAffinityContext.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ReliableChannel.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientPartitionAwarenessUnstableTopologyTest.java
> IGNITE-21266 Java Thin Client: Fixed PA after cluster restart with the same topology version.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridDhtAtomicCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridNearAtomicAbstractUpdateFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridNearAtomicSingleUpdateFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridNearAtomicUpdateFuture.java
> IGNITE-21586 Removed orphaned rawRetVal flag.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/evict/Random2LruPageEvictionTracker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/evict/RandomLruPageEvictionTracker.java
> IGNITE-21637 Fix integer overflow in page eviction trackers

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneSpiContext.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcPushMetricsExporterTest.java
> IGNITE-21678 Fix Cdc error with ignite to ignite streamer in case BinaryConfiguration is specified in config

- modules/core/src/main/java/org/apache/ignite/internal/processors/affinity/GridAffinityAssignmentCache.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/affinity/GridHistoryAffinityAssignmentTest.java
> IGNITE-21478 OOM crash with unstable topology

- parent/pom.xml
> IGNITE-21796 Update grpc-context version from 1.61.0 to 1.62.2 in opencensus module

- docs/_docs/code-snippets/xml/wal-compress.xml
- docs/_docs/persistence/native-persistence.adoc
> IGNITE-21223 Add xml example in WAL Records Compression section of Ignite documentation

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexingTest.java
- modules/core/src/main/java/org/apache/ignite/internal/MarshallerContextImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/MarshallerMappingFileStore.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/BinaryMetadataFileStore.java
> IGNITE-21900 Remove meta command need to remove marshaller data

- modules/core/src/main/java/org/apache/ignite/internal/processors/port/GridPortProcessor.java
> IGNITE-13114 : 65535 is the **inclusive** upper bound for port numbers

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/AbstractFileIO.java
> IGNITE-21770 extended logging for the AbstractFileIO#fully() method

- docs/_docs/data-rebalancing.adoc
> IGNITE-21994 Fix broken link

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheIoManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheIoManagerRetryTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite13.java
> IGNITE-22026 Fix incorrect retry logic in GridCacheIoManager send method

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
> IGNITE-22173

- docs/_data/toc.yaml
- docs/_docs/security/security-model.adoc
> IGNITE-21542 Add documentation on Ignite Security Model

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryManager.java
> IGNITE-22219 Remove useless SqlQuery code

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManager.java
> IGNITE-21823 Add proper logging of default pageSize

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/TableDmlIntegrationTest.java
> IGNITE-22439 Add tests for duplicate keys in Calcite

- parent/pom.xml
> IGNITE-22419 Removed unused dependencies

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessor.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/thin/MultiLineQueryTest.java
- modules/calcite/src/test/java/org/apache/ignite/testsuites/IntegrationTestSuite.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryProperties.java
> IGNITE-21491 SQL Calcite: Fix assertion error for multiline statements in thin client

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/IdleVerifyTaskV2.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/VerifyBackupPartitionsTaskV2.java
When you call control.sh --cache idle_verify on inactive cluster with persistence, control script hangs and no actions are performed. As you can see below in 'rest' thread dump, VerifyBackupPartitionsTaskV2 waits for checkpoint start in GridCacheDatabaseSharedManager#waitForCheckpoint.
It seems, that we can interrupt task execution and print message in control script output, that IdleVerify can't work on inactive cluster.
[TCbot2](https://tcbot2.sbt-ignite-dev.ru/pr.html?serverId=apache&suiteId=IgniteTests24Java8_RunAll&branchForTc=pull/11377/head&action=Latest)
___________________________________
The description …
> ignite-17383 IdleVerify hangs when called on inactive cluster with persistence

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/ComputeTaskSessionTest.cs
> IGNITE-22586 .NET: Fix build failure due to ComputeTaskSessionTest

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/oom/IgniteQueryOOMTestSuite.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/oom/OOMLeadsTest.java
> IGNITE-22604 OOM caught internally in H2 does not call failure handler

- docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc
> IGNITE-22536 Conflict resolver docs update

- parent/pom.xml
> IGNITE-22683 Update Ignite dependency: PostgreSQL JDBC

- modules/calcite/pom.xml
> IGNITE-22684 Update Ignite dependency json-path

- .github/workflows/commit-check.yml
> IGNITE-22726 Add Github CI check for javadocs

- docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc
> IGNITE-18372 CDC metrics documentation update

- parent/pom.xml
> IGNITE-22731 update zookeeper

- parent/pom.xml
> IGNITE-22734 update jetty

- modules/rest-http/README.txt
Now it's not enogh to copy libs/optional/ignite-rest-http folder to libs to enable REST API.
New ignite-json module should be copied as well.
------------
- [How to …
> IGNITE-22749 Mention ignite-json as dependency in the REST API module README.txt

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/dns_failure_test/BlockingNameService.java
- modules/ducktests/tests/ignitetest/tests/dns_failure_test.py
Support test for JDK 9 and above.  In particular JDK17
--- …
> IGNITE-22756 Fix dns_failure ducktest to work with jdk 17

- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/ignitetest/tests/cdc/cdc_test.py
- modules/ducktests/tests/ignitetest/utils/version.py
> IGNITE-22763 [ducktests] Ignore test_cdc_start_stop for version before 2.17.0

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/sql/GridSqlQuerySplitter.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/sql/SqlAstTraverser.java
- modules/indexing/src/test/java/org/apache/ignite/sqltests/BaseSqlTest.java
- modules/indexing/src/test/java/org/apache/ignite/sqltests/ReplicatedSqlCustomPartitionsTest.java
> IGNITE-22789 Throw an exception when join is used for partitioned cache with affinity key and replicated cache with different partitions count

- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheIndexQueryRequest.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/thin_client_query_test/ThinClientQueryTestApplication.java
- modules/ducktests/tests/ignitetest/tests/thin_client_query_test.py
> IGNITE-20943 Fix deserializing cache entries for IndexQuery on server

- .github/workflows/commit-check.yml
- .github/workflows/sonar-branch.yml
- .github/workflows/sonar-pr-from-fork-build.yml
- .github/workflows/sonar-pr-from-fork-scan.yml
> IGNITE-20466 Support Sonar checks for PRs from external forks

- docs/_docs/SQL/distributed-joins.adoc
> IGNITE-22875 Added limitations for colocated joins

- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/GridDeploymentCommunication.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
https://issues.apache.org/jira/browse/IGNITE-22952 …
> IGNITE-22952 Fix lambda classname parsing in deployment for Java 21+

- modules/log4j2/src/main/java/org/apache/ignite/logger/log4j2/Log4J2Logger.java
> IGNITE-14726 Add starting square bracket in default log4j2 pattern

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtLockFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtLockRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTransactionalCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTransactionalCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxRemote.java
`GridDhtLockRequest#addNearKey(KeyCacheObject)` usage was removed in commit in February 2015 [1]. Thus, this method seems to be useless.
Some related code in `GridDhtTransactionalCacheAdapter`, `GridNearTransactionalCache`, etc. was removed too because it became redundant.
1. https://github.com/apache/ignite/commit/212293eb2bede9cca6610e7c43e870ab386bd3f8#diff-86a6708705e89463e914e03aff750e5bd7e5641eb568b9d0a7bbd9e62e7c81c4L944
---
(see [the …
> IGNITE-22917 Remove GridDhtLockRequest#nearKeys

- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/LongDestroyDurableBackgroundTaskTest.java
> IGNITE-22998 Fix ValidateIndexesTaskResult initialization

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/util/MavenUtils.java
> IGNITE-23094 Added support of redefined Maven settings file path for all commands in Compatibility tests.

- docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc
* Kafka consumer/producer timeouts documentation …
> IGNITE-18574

- docs/README.adoc
- docs/_docs/includes/cpp-prerequisites.adoc
- docs/_docs/includes/dotnet-prerequisites.adoc
- docs/_docs/includes/prereqs.adoc
- docs/_docs/monitoring-metrics/new-metrics-system.adoc
- docs/_docs/net-specific/net-cross-platform-support.adoc
- docs/_docs/net-specific/net-troubleshooting.adoc
- docs/_docs/perf-and-troubleshooting/memory-tuning.adoc
- docs/_docs/quick-start/java.adoc
- docs/_docs/restapi.adoc
- docs/_docs/security/sandbox.adoc
- docs/_docs/security/tde.adoc
- docs/_docs/tools/control-script.adoc
- docs/_docs/tools/informatica.adoc
- examples/README.md
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinConnectionSSLTest.java
- modules/numa-allocator/README.md
- modules/platforms/dotnet/examples/README.md
- parent/pom.xml
> IGNITE-22997 Remove mention of Java 1.8 from docs

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/WALRecord.java
- modules/core/src/test/java/org/apache/ignite/testframework/wal/record/RecordUtils.java
> IGNITE-23151 Reserve WAL record index for further improvements

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtLockResponse.java
> IGNITE-22918 Remove GridDhtLockResponse#nearEvicted

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
- modules/core/src/test/java/org/apache/ignite/internal/RemoveEntryProcessorTransactionTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheAbstractFullApiSelfTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite.java
… EntryProcessor in optimistic transaction …
> IGNITE-23211 Fix AssertionError on IgniteCache#get

- docs/_docs/data-rebalancing.adoc
> IGNITE-23149 Updated rebalance thread pool doc

- modules/calcite/pom.xml
> IGNITE-23249 update janino

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/AbstractBasicIntegrationTest.java
> Compilation fix

- parent/pom.xml
> IGNITE-23247 update spring dependency

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/AbstractBasicIntegrationTransactionalTest.java
> Fix complication

- docs/Gemfile
> IGNITE-23332 jekyll-sass-converter version changed from 3.0 to 2.2

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheGroupMetricsImpl.java
Now it waits initialization of CacheGroupContext topology before calculating metrics …
> IGNITE-23355 Fix testClientNodePds

- .github/workflows/commit-check.yml
- DEVNOTES.txt
- examples/DEVNOTES.txt
- modules/platforms/dotnet/build.ps1
- modules/yardstick/DEVNOTES.txt
- pom.xml
- scripts/build-module.sh
- scripts/build.sh
> IGNITE-23382 Change summary: the all-scala profile has now been removed from usages

- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/tests/thin_client_query_test.py
IGNITE-23016 ducktape tests for dev branch implicitly use direct-io
- Ignored the direct-io module through EXCLUDE_MODULES env, which checks if direct-io is present in modules
- Updated envs method in IgniteNodeSpecExcludeDucktests to accommodate changes
the `green visa` attached to the JIRA ticket (see …
> IGNITE-23016 Fixed to prevent implicit use of the direct-io on a dev branch

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/ddl/DdlSqlToCommandConverter.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/TableDmlIntegrationTest.java
> IGNITE-23426 : Calcite. 'CREATE TABLE' fails if 'DEFAULT' is null.

- parent/pom.xml
> IGNITE-23427 Update ignite dependency commons-io

- docs/_docs/monitoring-metrics/system-views.adoc
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinMetadataSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/systemview/walker/SnapshotViewWalker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotMetadata.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotMetadata.java
- modules/core/src/main/java/org/apache/ignite/spi/systemview/view/SnapshotView.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotCheckBeforeRestoreTest.java
> IGNITE-18979 Add snapshot creation time in SnapshotView

- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinDefaultTimeoutTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/GridTestUtils.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/distributed/near/IgniteCacheDistributedQueryDefaultTimeoutSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/SqlSystemViewsSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/IgniteSqlQueryStartFinishListenerTest.java
…s but not the System
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbrev …
> IGNITE-23478 Fix flaky test SqlSystemViewsSelfTest.testQueryHistoryMetricsModes

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheTtlManagerLoadTest.java
> IGNITE-23521 fixed test GridCacheTtlManagerLoadTest with pds=true

- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
The corresponding socket exception is caught and ignored. …
> IGNITE-23535 Fix IgniteUtilsUnitTest.shouldNotProduceWarningsWhenClosingAnAlreadyClosedSocket

- modules/ducktests/pom.xml
> IGNITE-23679 [ducktests] Use dependencies from the ignite instance under test in test runtime

- parent/pom.xml
> IGNITE-23709 Update Ignite dependency jetty

- parent/pom.xml
> IGNITE-23710 Update Ignite dependency snappy

- modules/core/src/main/java/org/apache/ignite/internal/commandline/cache/distribution/CacheDistributionTaskResult.java
> IGNITE-23705 Add partition column to control.sh --cache distribution output

- modules/core/src/main/java/org/apache/ignite/internal/util/GridLongList.java
- modules/core/src/test/java/org/apache/ignite/util/GridLongListSelfTest.java
> IGNITE-12678 Fix zero size GridLongList#add

- modules/core/src/main/java/org/apache/ignite/internal/IgniteFeatures.java
- modules/opencensus/src/test/java/org/apache/ignite/internal/processors/monitoring/opencensus/OpenCensusTracingSpiTest.java
> MINOR: Cleanup dead IgniteFeatures entries

- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/CacheScanPartitionQueryFallbackSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheNoClassQuerySelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/IgniteSqlDefaultValueTest.java
> IGNITE-23875 Remove setForceServerMode from indexing tests

- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractQuerySelfTest.java
> IGNITE-23887 Remove setForceServerMode from IgniteCacheAbstractQuerySelfTest

- modules/core/src/test/java/org/apache/ignite/internal/processors/affinity/GridAffinityProcessorAbstractSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/IndexingSpiQueryTxSelfTest.java
- modules/core/src/test/java/org/apache/ignite/messaging/IgniteMessagingWithClientTest.java
> IGNITE-23897 Remove setForceServerMode from GridAffinityProcessorAbstractSelfTest and other tests

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteCacheManyClientsTest.java
> IGNITE-23913 Remove setForceServerMode from IgniteCacheManyClientsTest

- modules/core/src/test/java/org/apache/ignite/internal/managers/discovery/IgniteTopologyPrintFormatSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheAtomicSingleMessageCountSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheStopAndDestroySelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheMixedPartitionExchangeSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCachePutAllFailoverSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheConfigurationTemplateTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheNearLockValueSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteDynamicCacheStartSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/binary/GridCacheClientNodeBinaryObjectMetadataMultinodeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/binary/GridCacheClientNodeBinaryObjectMetadataTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/GridCacheMixedModeSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteCacheClientNodePartitionsExchangeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteCacheClientReconnectTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteCacheNearRestartRollbackSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/near/GridCacheRendezvousAffinityClientSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/eviction/lru/LruNearOnlyNearEvictionPolicySelfTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpClientDiscoverySpiMulticastTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryFailedJoinTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/ipfinder/vm/TcpDiscoveryVmIpFinderSelfTest.java
> IGNITE-23922 Remove setForceServerMode from simple core tests

- modules/core/src/test/java/org/apache/ignite/internal/GridTaskFailoverAffinityRunTest.java
> IGNITE-23932 Remove setForceServerMode from GridTaskFailoverAffinityRunTest

- modules/core/src/test/java/org/apache/ignite/internal/ClusterGroupAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/internal/GridReleaseTypeSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheAtomicMessageCountSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheReturnValueTransferSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractStopBusySelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/GridCacheAbstractDataStructuresFailoverSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridCacheAtomicInvalidPartitionHandlingSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/expiry/IgniteCacheExpiryPolicyAbstractTest.java
> IGNITE-23941 Remove setForceServerMode from simple core tests - 2

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/near/GridCacheNearOnlyTopologySelfTest.java
…SelfTest
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules …
> IGNITE-23954 Remove setForceServerMode from GridCacheNearOnlyTopologySelfTest

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteCacheClientNodeChangingTopologyTest.java
> IGNITE-23966 Remove setForceServerMode from IgniteCacheClientNodeChangingTopologyTest

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheAffinityCallSelfTest.java
> IGNITE-23990 Remove setForceServerMode from CacheAffinityCallSelfTest

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/Dynamic/dynamic-client.xml
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationSerializerTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationTest.cs
> IGNITE-24028 Remove setForceServerMode from .NET tests

- docs/_docs/perf-and-troubleshooting/sql-tuning.adoc
> IGNITE-24039 Fixing wrong comment in code example

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientRequestHandler.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/SecurityContextInternalFuturePropagationTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
> IGNITE-23958 Fixed security context propagation for async transactional operations

- docs/_config.yml
- docs/_docs/code-snippets/java/pom.xml
- modules/checkstyle/pom.xml
- modules/core/src/main/resources/ignite.properties
- modules/dev-utils/ignite-modules-test/build.gradle
- modules/ducktests/tests/ignitetest/__init__.py
- modules/platforms/cpp/CMakeLists.txt
- modules/platforms/dotnet/SharedAssemblyInfo.cs
- parent/pom.xml
> IGNITE-23762 Update ignite-2.17 branch version to 2.17.0

- packaging/deb/changelog
- packaging/rpm/apache-ignite.spec
> IGNITE-23766 Update Linux packages version to 2.17

- .github/workflows/commit-check.yml
- modules/ducktests/tests/tox.ini
…ithub action
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+R …
> IGNITE-23460 [ducktests] Use python 3.8 and 3.9 in the commit-check github action

- modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py
> IGNITE-24125 [ducktests] Fix JMXClient to read MBeans with names containing spaces

- modules/ducktests/tests/ignitetest/tests/jdbc_thin_test.py
> IGNITE-24126 [ducktests] Fix flacky jdbc_thin_test

- modules/core/src/main/java/org/apache/ignite/internal/cluster/IgniteClusterImpl.java
> IGNITE-24083 Remove MIN_BLT_SUPPORTING_VER

- modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/GridEncryptionManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
> IGNITE-24085 Remove CACHE_ENCRYPTION_SINCE

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClusterCachesInfo.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
> IGNITE-24086 Remove V_MERGE_CONFIG_SINCE

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
> IGNITE-24087 Remove PRELOAD_PARTITION_SINCE

- modules/compress/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotCompressionBasicTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerCheckIncrementalSnapshotTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerInterruptCommandTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/CacheFilterEnum.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/CacheIdleVerifyCancelTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/CacheIdleVerifyCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/IdleVerifyException.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/IdleVerifyResult.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/IdleVerifyTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/NoMatchingCachesException.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/VerifyBackupPartitionsDumpTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/VerifyBackupPartitionsTask.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cache/VerifyBackupPartitionsTaskV2.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotVerificationTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyTaskResult.java
- modules/core/src/main/resources/META-INF/classnames.properties
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheFastNodeLeftForTransactionTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/HistoricalRebalanceCheckpointTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotConsistencyTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotRestoreFromRemoteTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxRollbackOnTimeoutOnePhaseCommitTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxWithSmallTimeoutAndContentionOneKeyTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/common/GridCommonAbstractTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckWithIndexesTest.java
> IGNITE-24084 Remove VerifyBackupPartitionsTaskV2#V2_SINCE_VER

- modules/core/src/main/java/org/apache/ignite/internal/direct/stream/DirectByteBufferStream.java
> IGNITE-24168 Fixed performance drop caused by IGNITE-22375

- .github/workflows/commit-check.yml
- modules/ducktests/tests/tox.ini
> IGNITE-24214 [ducktests] Use python3.8 for ducktest checkstyle

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtPartitionsStateValidator.java
> IGNITE-24099 Remove SIZES_VALIDATION_AVAILABLE_SINCE

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryManager.java
> IGNITE-24100 Remove NOT_NULLS_SUPPORT_VER

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ValidationOnNodeJoinUtils.java
> IGNITE-24092 Remove PRECISION_SCALE_SINCE_VER

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheProxyImpl.java
> IGNITE-24091 Remove CONT_QRY_WITH_TRANSFORMER_SINCE

- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ipfinder/multicast/TcpDiscoveryMulticastIpFinder.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpClientDiscoverySpiMulticastTest.java
> IGNITE-24256 Fixed NullPointerException during stop of TcpDiscoveryMulticastIpFinder.

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/ExpiredEntriesIntegrationTest.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineTreeFilterClosure.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
> IGNITE-24135 BPlusTree reuses lastRow from closure to fill buffer

- modules/calcite/pom.xml
> IGNITE-24376 Add missing commons-text runtime dependency

- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/transaction.py
> IGNITE-24451 [ducktests] Allow to configure TransactionConfiguration#setTxAwareQueriesEnabled

- docs/_docs/tools/control-script.adoc
> IGNITE-24430 Added documentation about migration of the control utility to the thin client protocol

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/SnapshotFileTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/CreateDumpFutureTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/Dump.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotHandlerTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotWalRecordTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IncrementalSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/PlainSnapshotTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotCheckBeforeRestoreTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotRestoreTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/GridAbstractTest.java
> IGNITE-24481 Migration to snapshot file tree in tests

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/IgniteIndexReader.java
- modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/indexreader/IgniteIndexReaderTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FilePageStoreManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/SnapshotFileTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotFutureTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/Dump.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsCorruptedStoreTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsDefragmentationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/PagesPossibleCorruptionDiagnosticTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/IgnitePdsDataRegionMetricsTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotDeltaTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/GridIndexRebuildTest.java
> IGNITE-24575 Move SnapshotFileTree constants to private

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/IgniteReleasedVersion.java
> IGNITE-23761 Update IgniteReleasedVersion for compatibility tests to 2.17.0

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotCheckProcess.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotChecker.java
> Fix snp. refactoring master merdge

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/rel/Outbox.java
> IGNITE-24666 Optimize Outbox#flush method

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/PlannerPhase.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/planner/CorrelatedNestedLoopJoinPlannerTest.java
> IGNITE-24688 Add FilterCorrelate rule into HEP planner phase

- modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py
> IGNITE-24725 [ducktests] Add ability to run operations via JMX

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite master)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.17)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.16)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.15)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.14)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.13)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.12)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.11.1)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.11)

- docs/_layouts/default.html
> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.10)

- modules/core/src/main/java/org/apache/ignite/internal/processors/performancestatistics/FilePerformanceStatisticsReader.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/performancestatistics/FilePerformanceStatisticsWriter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/performancestatistics/OperationType.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/performancestatistics/ForwardReadQueryPropertyTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicWithPersistenceTestSuite.java
> IGNITE-24777 Fix reading cached strings

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/schema/CacheTableDescriptorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheProxyImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/CacheObjectBinaryProcessorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/management/SortedIndexDescriptorFactory.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/dml/DmlUtils.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/dml/UpdatePlan.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/dml/UpdatePlanBuilder.java
> IGNITE-15803 Remove always true GridCacheContext#binaryMarshaller method

- modules/core/src/test/java/org/apache/ignite/internal/util/nio/TcpCommunicationSpiSslVolatilePayloadTest.java
> IGNITE-24913 Fixed flaky TcpCommunicationSpiSslVolatilePayloadTest test.

- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioWorker.java
> IGNITE-24945 Fixed node failure with CancelledKeyException on session close with SSL enabled.

- modules/core/src/main/java/org/apache/ignite/internal/IgniteKernal.java
- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringBuilder.java
- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringFieldDescriptor.java
- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/ReflectionToStringFieldDescriptor.java
- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/UnsafeToStringFieldDescriptor.java
> IGNITE-25012 Extract GridToStringBuilder Unsafe code to interface

- modules/commons/pom.xml
> [MINOR] Deploy ignite-commons to staging

- modules/benchmarks/pom.xml
- modules/calcite/pom.xml
- modules/control-utility/pom.xml
- modules/dev-utils/pom.xml
- modules/extdata/p2p/pom.xml
- modules/extdata/uri/pom.xml
- modules/indexing/pom.xml
- modules/json/pom.xml
- modules/log4j2/pom.xml
- modules/rest-http/pom.xml
- modules/spring/pom.xml
- modules/web/pom.xml
This reverts commit 2d3400e05c5a76fa9e7b55ad00b1aa81ce2d019f. …
> [MINOR] Add ignite-binary-api provided dependency

- modules/core/src/main/java/org/apache/ignite/internal/util/lang/GridFunc.java
> IGNITE-22846 Fix typo in Javadoc description for GridFunc#firstEntry

- modules/commons/src/main/java/org/apache/ignite/internal/util/typedef/T1.java
- modules/commons/src/main/java/org/apache/ignite/internal/util/typedef/T2.java
- modules/commons/src/main/java/org/apache/ignite/internal/util/typedef/T3.java
- modules/commons/src/main/java/org/apache/ignite/internal/util/typedef/T4.java
- modules/commons/src/main/java/org/apache/ignite/internal/util/typedef/T5.java
- modules/commons/src/main/java/org/apache/ignite/internal/util/typedef/T6.java
> [MINOR] Move T* aliases to ignite-commons

- modules/core/src/main/java/org/apache/ignite/internal/IgniteKernal.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryEnumCache.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/GridAbstractTest.java
> IGNITE-25143 Move BinaryEnumCache to package-private

- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinConnectionSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryNoopMetadataHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryContextPredefinedTypesTest.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/GridBinaryWildcardsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/binary/GridBinaryCacheEntryMemorySizeSelfTest.java
> IGNITE-25145 Move BinaryNoopMetadataHandler to package-private

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryArrayIdentityResolver.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryObjectTestUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/builder/BinaryObjectBuilderAdditionalSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/binary/GridCacheBinaryObjectsAbstractSelfTest.java
> IGNITE-25170 Move BinaryArrayIdentityResolver to package-private

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/management/meta/MetaRemoveCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/BinaryMetadataFileStore.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsBinaryMetadataOnClusterRestartTest.java
…me to NodeFileTree
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbrevia …
> IGNITE-25132 Move BinaryUtils#typeId and BinaryUtils#binaryMetaFileName to NodeFileTree

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
> IGNITE-25131 Remove IGNITE_BINARY_DONT_WRAP_TREE_STRUCTURES

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinarySchemaRegistry.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/builder/BinaryObjectBuilderImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformContextImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformUtils.java
> IGNITE-25156 Make BinarySchemaRegistry package private

- modules/control-utility/src/test/java/org/apache/ignite/util/PerformanceStatisticsCommandTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/performancestatistics/SystemViewFileWriter.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/performancestatistics/AbstractPerformanceStatisticsTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/performancestatistics/PerformanceStatisticsSystemViewTest.java
> IGNITE-24287 Ignore node.attributes system view to record in PerfStat

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryReaderHandles.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/GridBinaryMarshaller.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/builder/BinaryBuilderReader.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientBinaryMarshaller.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/jdbc/thin/JdbcThinTcpIo.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformContextImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/events/FakeIgniteServer.java
> IGNITE-25195 Make BinaryReaderHandles package private

- modules/core/src/main/java/org/apache/ignite/cache/store/jdbc/CacheAbstractJdbcStore.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryArrayIdentityResolver.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryEnumObjectImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryObjectEx.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryWriterExImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/builder/BinaryBuilderSerializer.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/builder/BinaryObjectBuilderImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientBinary.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/CacheObjectBinaryProcessorImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryEnumsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheEnumOperationsAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/replicated/preloader/GridCacheReplicatedPreloadSelfTest.java
- modules/json/src/main/java/org/apache/ignite/internal/binary/BinaryObjectImplSerializer.java
> IGNITE-25243 Make BinaryEnumObjectImpl package private

- modules/yardstick/pom.xml
> [MINOR] Using property for groupId

- docs/_docs/data-structures/atomic-types.adoc
> IGNITE-25293 Fix doc in default backup number of atomic-types

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCachePartitionExchangeManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cluster/ClusterStateChangeOnNodeJoinTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteKernalSelfTestSuite.java
https://issues.apache.org/jira/browse/IGNITE-13348 …
> IGNITE-13348 Fix joining node to the cluster that is in transition state

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/SnapshotFileTree.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/filename/AbstractDataRegionRelativeStoragePathTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/filename/DataRegionRelativeStoragePathTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/filename/SnapshotCreationNonDefaultStoragePathTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite8.java
…Path set
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules …
> IGNITE-25383 Fix snapshot creation if DataRegionConfiguration#storagePath set

- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/TooManyOpenFilesTcpCommunicationSpiTest.java
> IGNITE-25419 Fix flaky test TooManyOpenFilesTcpCommunicationSpiTest

- assembly/dependencies-apache-ignite-lgpl.xml
- assembly/dependencies-apache-ignite-slim.xml
- assembly/dependencies-apache-ignite.xml
> [MINOR] Exclude new modules from release

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
> IGNITE-25169 Fix possible NPE in BinaryUtils#binaryMetadata

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ValidationOnNodeJoinUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/filename/CustomCacheStorageConfigurationSelfTest.java
> IGNITE-25461 Fixed validation of cache storage path on a client node

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcConsumerState.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcUtilityActiveCdcManager.java
- modules/core/src/main/java/org/apache/ignite/internal/management/cdc/CdcDeleteLostSegmentsTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/test/java/org/apache/ignite/cdc/AbstractCdcTest.java
> IGNITE-25427 Move CdcConsumerState file logic to NodeFileTree

- modules/core/src/main/java/org/apache/ignite/internal/maintenance/MaintenanceFileStore.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsDefragmentationTest.java
> [MINOR] Move maintenance file to NodeFileTree

- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoverySpiTestBase.java
- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryTopologyChangeAndReconnectTest.java
> IGNITE-25455 Reduce memory requirements of largeUserAttributes* tests

- modules/control-utility/src/test/java/org/apache/ignite/util/GridPersistenceCommandsTest.java
- modules/core/src/main/java/org/apache/ignite/configuration/CacheConfiguration.java
- modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
- modules/core/src/main/java/org/apache/ignite/dump/DumpReaderConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/IgnitionEx.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ValidationOnNodeJoinUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/SnapshotFileTree.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/filename/CacheConfigStoragePathTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/filename/CustomCacheStorageConfigurationSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
> [MINOR] Spell fix pathes -> paths

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
> IGNITE-25130 Use JDK11 Set#of, Map#of in BinaryUtils

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
> [MINOR] Update NodeFileTree javadoc for CDC files

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/SnapshotCompatibilityTest.java
> IGNITE-24535 Restore snapshot with custom path

- modules/core/src/main/java/org/apache/ignite/dump/DumpEntry.java
- modules/core/src/main/java/org/apache/ignite/dump/DumpReader.java
- modules/core/src/main/java/org/apache/ignite/dump/DumpReaderConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/Dump.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/DumpEntrySerializer.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpFilterTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteSnapshotTestSuite3.java
> IGNITE-25554 Dump reader - cache names filter added

- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryPendingMessageDeliveryTest.java
> IGNITE-25539 Await PME to close a race in test code

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/NodeFileTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/IgniteNodeStoppedDuringDisableWALTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/WalOnNodeStartTest.java
> IGNITE-25634 Move WAL temp file constants to NodeFileTree

- modules/control-utility/src/test/java/org/apache/ignite/util/KillCommandsControlShTest.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ReliableChannel.java
- modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
- modules/indexing/src/test/java/org/apache/ignite/util/KillCommandsMXBeanTest.java
- modules/indexing/src/test/java/org/apache/ignite/util/KillCommandsSQLTest.java
> IGNITE-23856 channel connection retry in ASYNC case

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/AuthorizationIntegrationTest.java
- modules/core/src/main/java/org/apache/ignite/client/ClientAuthorizationException.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientRequestHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/IgniteClientException.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheSqlFieldsQueryRequest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/SecurityContextInternalFuturePropagationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/cluster/ClusterStatePermissionTest.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientSecurityPermissionsTest.cs
> IGNITE-25609 WIP

- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySelfTest.java
> IGNITE-25599 Wait for pending messages to be sent before checks

- modules/compatibility/pom.xml
- modules/direct-io/pom.xml
- modules/extdata/pluggable/pom.xml
- modules/extdata/uri/modules/uri-dependency/pom.xml
- modules/jcl/pom.xml
- modules/jta/pom.xml
- modules/kubernetes/pom.xml
- modules/numa-allocator/pom.xml
- modules/schedule/pom.xml
- modules/slf4j/pom.xml
- modules/spring/pom.xml
- modules/web/pom.xml
- modules/zookeeper/pom.xml
> [MINOR] Add provided dependencies to a few modules

- docs/_docs/extensions-and-integrations/ignite-for-spark/overview.adoc
> IGNITE-25809 Add more spark-ext versions

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/junits/IgniteCompatibilityAbstractTest.java
> IGNITE-25852 Fix jar-hell in compatibility tests

- assembly/dependencies-apache-ignite.xml
> IGNITE-25888 Remove excess libs from a release dir

- modules/bom/pom.xml
- modules/core/pom.xml
> [MINOR] Make ignite-codegen2 provided

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/SessionChannelMessage.java
> IGNITE-25944 Use MessageSerializer for SessionChannelMessage

- modules/codegen2/src/main/java/org/apache/ignite/internal/MessageProcessor.java
- modules/codegen2/src/main/java/org/apache/ignite/internal/MessageSerializerGenerator.java
- modules/codegen2/src/main/java/org/apache/ignite/internal/Order.java
- modules/core/src/main/java/org/apache/ignite/internal/GridDirectTransient.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheEntryInfo.java
- modules/core/src/test/resources/codegen/TestMessage.java
- modules/core/src/test/resources/codegen/TestMessageSerializer.java
> IGNITE-25950 Code-generated serializer for GridCacheEntryInfo message

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/authentication/IgniteAuthenticationProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/authentication/UserAuthenticateRequestMessage.java
> IGNITE-25946 Use MessageSerializer for UserAuthenticateRequestMessage

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/authentication/UserAuthenticateResponseMessage.java
> IGNITE-25960 Use MessageSerializer for UserAuthenticateResponseMessage

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/SqlListenerUtils.java
> [MINOR] Minify visibility of BinaryUtils doReadXXXArray methods

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/version/GridCacheVersion.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/version/GridCacheVersionEx.java
> IGNITE-25992 Use MessageSerializer for GridCacheVersion and GridCacheVersionEx

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionExchangeId.java
> IGNITE-25993 Use MessageSerializer for GridDhtPartitionExchangeId

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/TcpInverseConnectionResponseMessage.java
> IGNITE-26045 Use MessageSerializer for TcpInverseConnectionResponseMessage

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
> [MINOR] BinaryContext remove MarshallerUtils dependency

- modules/core/src/main/java/org/apache/ignite/configuration/CacheConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/CacheObjectBinaryProcessorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/IgniteMock.java
> [MINOR] Move affinityFieldName to GridCacheUtils

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/latch/LatchAckMessage.java
> IGNITE-26079 Use MessageSerializer for LatchAckMessage

- modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
> IGNITE-26130 RetryPolicy tests fails

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/spi/collision/jobstealing/JobStealingRequest.java
> IGNITE-26040 Use MessageSerializer for JobStealingRequest

- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioFinishedFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioFutureImpl.java
> IGNITE-25999 Remove GridNioFuture#onAckReceived

- modules/core/src/test/java/org/apache/ignite/internal/util/future/IgniteFutureImplTest.java
> IGNITE-26047 Fix IgniteFutureImplTest#testChainAsync: add threadName parameter

- parent/pom.xml
> IGNITE-26153 Fix MessageProcessorTest on JDK 17

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/WalStateAckMessage.java
> IGNITE-25969 Remove IgniteCodeGeneratingFail annotation from WalStateAckMessage

- modules/tools/src/main/java/org/apache/ignite/tools/classgen/ClassesGenerator.java
> IGNITE-26278 Fix handling of class files loaded from JAR archives

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/messages/GridQueryNextPageResponse.java
> IGNITE-26321 Use MessageSerializer for GridQueryNextPageResponse

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotRestoreTest.java
> IGNITE-26333 Fix testRestoreFromSecondAttempt

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheGroupContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheGroupRecoveryState.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheJoinNodeDiscoveryData.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheNodeCommonDiscoveryData.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClusterCacheGroupRecoveryData.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClusterCachesInfo.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCachePartitionExchangeManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/CachePartitionFullCountersMap.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsSingleMessage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridClientPartitionTopology.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtPartitionTopology.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtPartitionTopologyImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/BaselineTopology.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/IGridClusterStateProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteLostPartitionsRecoveryTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite12.java
> IGNITE-26168 Add support of partition loss detection after cluster restart

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridCacheTxRecoveryRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridCacheTxRecoveryResponse.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedBaseMessage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedLockRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedLockResponse.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxFinishRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxPrepareRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxPrepareResponse.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedUnlockRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtLockRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtLockResponse.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxFinishRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxPrepareRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxPrepareResponse.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtUnlockRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearLockRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearLockResponse.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxFinishRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxPrepareRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxPrepareResponse.java
> IGNITE-26386 Remove candsByIdxBytes field from GridDistributedBaseMessage

- docs/_docs/monitoring-metrics/intro.adoc
> IGNITE-26412 Fix a broken link to JMX metrics

- modules/core/src/main/java/org/apache/ignite/cache/query/SqlFieldsQuery.java
> IGNITE-26267 Mark SqlFieldsQuery#setLazy/isLazy with @Deprecated

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/service/ServiceSingleNodeDeploymentResultBatch.java
> IGNITE-26056 Use MessageSerializer for ServiceSingleNodeDeploymentResultBatch

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsAbstractMessage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsSingleRequest.java
> IGNITE-26423 Use MessageSerializer for GridDhtPartitionsSingleRequest

- modules/codegen2/src/main/java/org/apache/ignite/internal/MessageSerializerGenerator.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/IgniteIndexReader.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteCodeGeneratingFail.java
- modules/core/src/main/java/org/apache/ignite/internal/direct/DirectMessageReader.java
- modules/core/src/main/java/org/apache/ignite/internal/direct/DirectMessageWriter.java
- modules/core/src/main/java/org/apache/ignite/internal/direct/stream/DirectByteBufferStream.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridDhtAtomicDeferredUpdateResponse.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridDhtAtomicUpdateRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridNearAtomicFullUpdateRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/CacheDataRowAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/freelist/PagesList.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridLongList.java
- modules/core/src/main/java/org/apache/ignite/plugin/extensions/communication/MessageCollectionItemType.java
- modules/core/src/main/java/org/apache/ignite/plugin/extensions/communication/MessageReader.java
- modules/core/src/main/java/org/apache/ignite/plugin/extensions/communication/MessageWriter.java
- modules/core/src/test/java/org/apache/ignite/internal/managers/communication/AbstractCommunicationMessageSerializationTest.java
- modules/core/src/test/java/org/apache/ignite/util/GridLongListSelfTest.java
- modules/core/src/test/resources/codegen/TestCollectionsMessage.java
- modules/core/src/test/resources/codegen/TestCollectionsMessageSerializer.java
- modules/core/src/test/resources/codegen/TestMapMessage.java
- modules/core/src/test/resources/codegen/TestMapMessageSerializer.java
- modules/core/src/test/resources/codegen/TestMessage.java
- modules/core/src/test/resources/codegen/TestMessageSerializer.java
1. `GridLongList` serde moved to `MessageWriter` and `MessageReader`
2. `GridLongList` now does not implement `Message` interface.
3. Cleanup of  `GridLongList` was done.
---
- [How to …
> IGNITE-25991 Refactor GridLongList

- modules/compress/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotCompressionBasicTest.java
> IGNITE-25720 Fix failed tests SnapshotCompressionBasicTest

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheIdMessage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridNearAtomicCheckUpdateRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridNearAtomicUpdateResponse.java
> IGNITE-25961 Use MessageSerializer for GridNearAtomicUpdateResponse and GridNearAtomicCheckUpdateRequest

- modules/core/src/test/java/org/apache/ignite/internal/GridRuntimeExceptionSelfTest.java
> IGNITE-26220 Fix GridRuntimeExceptionSelfTest

- docs/_docs/tools/control-script.adoc
> IGNITE-24488 Documentation of distributed properties for blocking new connections.

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearGetRequest.java
> IGNITE-26496 Use MessageSerializer for GridNearGetRequest

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtForceKeysRequest.java
> IGNITE-26513 Use MessageSerializer for GridDhtForceKeysRequest

- modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryBatchAck.java
> IGNITE-26483 Use MessageSerializer for CacheContinuousQueryBatchAck
