- modules/log4j/src/main/java/org/apache/ignite/logger/log4j/Log4JLogger.java
Signed-off-by: Valentin Kulichenko <valentin.kulichenko@gmail.com>
> # ignite-1228

- scripts/apply-pull-request.sh
Implemented script for commiters apply-pull-request.sh.
> IGNITE-1217: apply-pull-request.sh

- modules/platform/src/main/java/org/apache/ignite/internal/processors/platform/lifecycle/PlatformLifecycleBean.java
Filter AfterStop events on Java side.
> IGNITE-1354 Platform: AFTER_GRID_STOP lifecycle events do not work

- scripts/apply-pull-request.sh
https://issues.apache.org/jira/browse/IGNITE-1383
> IGNITE-1383 Ability to use apply-pull-request.sh script for non-master branches

- modules/cloud/pom.xml
- modules/gce/pom.xml
- parent/pom.xml
I have tested this with AWS S3 account. All the tests were passing.
> IGNITE-4519 Updating ignite-aws java sdk pom version

- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringBuilder.java
- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringThreadLocal.java
- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/SBLimitedLength.java
- modules/core/src/test/java/org/apache/ignite/internal/util/tostring/GridToStringBuilderSelfTest.java
- modules/hadoop/src/test/java/org/apache/ignite/internal/processors/hadoop/impl/igfs/IgniteHadoopFileSystemClientBasedOpenTest.java
Revert of 
- IGNITE-8493
- IGNITE-9209
- IGNITE-602
> ignite-2.7 revert GridToStringBuilder changes

- examples/README.md
- examples/pom-standalone.xml
> IGNITE-11140 Fix Ignite examples compilation, support of Nightly builds

- parent/pom.xml
> IGNITE-11213 Fix for suites failed because of maven-surefire-plugin 

- modules/web-console/e2e/testenv/Dockerfile
@nva  I've update enviroment dockerfile for E2E to use and ran it on teamcity. Everything is working and seems fine. Please review and merge.
> IGNITE-8613. Web Console: E2E env docker image updated.

- modules/ml/src/main/java/org/apache/ignite/ml/selection/scoring/metric/classification/BinaryClassificationMetricValues.java
- modules/ml/src/main/java/org/apache/ignite/ml/selection/scoring/metric/classification/BinaryClassificationMetrics.java
- modules/ml/src/main/java/org/apache/ignite/ml/selection/scoring/metric/classification/ROCAUC.java
- modules/ml/src/test/java/org/apache/ignite/ml/selection/scoring/metric/classification/BinaryClassificationMetricsValuesTest.java
- modules/ml/src/test/java/org/apache/ignite/ml/selection/scoring/metric/classification/ROCAUCTest.java
1. Added separate metric
2. Added tests for ROCAUC
3. Added as one metric to BinaryClassifiactionMetric
NOTE: due to performance limitations added flag enableROCAUC (disabled by default) to avoid additional calulations
> IGNITE-10145: [ML] Implement ROC AUC metric

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Deployment/PeerAssemblyLoadingTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Deployment/GetAssemblyFunc.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Deployment/PeerAssemblyResolver.cs
Disable custom request assembly loading for GetAssemblyFunc
> IGNITE-11690 .NET: Unable to locate external assembly with enabled peerAssemblyLoading

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/GridCacheAbstractDataStructuresFailoverSelfTest.java
Interrupted flag check was added
> IGNITE-6454: suite timeout replace to failure

- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/DecisionTreeFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/DecisionTreeRegressionFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/GBTFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/GBTRegressionFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/KMeansFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/LinearRegressionFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/LogRegFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/RandomForestFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/RandomForestRegressionFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/inference/spark/modelparser/SVMFromSparkExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/selection/scoring/EvaluatorExample.java
- modules/ml/spark-model-parser/src/main/java/org/apache/ignite/ml/sparkmodelparser/SparkModelParser.java
- modules/ml/spark-model-parser/src/test/java/org/apache/ignite/ml/sparkmodelparser/SparkModelParserTest.java
- modules/ml/src/main/java/org/apache/ignite/ml/selection/scoring/evaluator/aggregator/BinaryClassificationPointwiseMetricStatsAggregator.java
> IGNITE-11294: [ML]  ML logger and env variables in Spark ML Parser

- examples/src/main/java/org/apache/ignite/examples/ml/tree/boosting/GDBOnTreesClassificationTrainerExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/Step_10_Bagging.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/Step_11_Boosting.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/Step_12_Model_Update.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/TutorialStepByStepExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/hyperparametertuning/Step_13_RandomSearch.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/hyperparametertuning/Step_14_Parallel_BrutForce_Search.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/hyperparametertuning/Step_15_Parallel_Random_Search.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/hyperparametertuning/Step_16_Genetic_Programming_Search.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/hyperparametertuning/Step_17_Parallel_Genetic_Programming_Search.java
- examples/src/main/java/org/apache/ignite/examples/ml/tutorial/hyperparametertuning/package-info.java
> IGNITE-9463: [ML] Update ML Tutorial with Boosting, Bagging, Online Learning

- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/TcpCommunicationSpi.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/messages/HandshakeMessage2.java
- modules/core/src/test/java/org/apache/ignite/internal/managers/communication/GridIoManagerFileTransmissionSelfTest.java
> IGNITE-12373: skip recovery descriptor reservation for a channel connection

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheMetricsImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheAbstractMetricsSelfTest.java
Add histograms for operations:
- get
- put
- remove
> IGNITE-12219: Cache operations performance metrics

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PageMemoryImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteSpeedBasedThrottle.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteThrottle.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/IgniteThrottlingUnitTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PageMemoryImplTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteThrottleSmokeTest.java
Add the `totalThrottleDuration` metric.
> IGNITE-12053 Total time threads parked if checkpoint throttling occurred

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
> IGNITE-12423 PME duration histogram updates only if log info enabled

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheMetricsImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheAbstractMetricsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheTransactionalAbstractMetricsSelfTest.java
Add commitTime, rollbackTime metrics
> IGNITE-12450 Transaction operations metrics

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinaryBuilderSelfTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientProtocolCompatibilityTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/Example.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/PathUtil.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteStartStopTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestRunner.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Common/TaskRunner.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/AppDomains.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/UnmanagedThread.cs
- modules/platforms/dotnet/build.ps1
- modules/platforms/dotnet/release/verify-nuget.ps1
* Fix P/Invoke in `UnmanagedThread`
* Fix `GetDefaultAppDomain`
* Fix `build.ps1` to work on Linux under PowerShell Core
This enables full development cycle on Linux, including NuGet package creation.
> IGNITE-12427 .NET: Fix Mono issues

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteFeatures.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ExchangeContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/GridExchangeFreeSwitchTest.java
Signed-off-by: Anton Vinogradov <av@apache.org>
> IGNITE-12470 Pme-free switch feature should be deactivatable

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteFeatures.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ExchangeContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/GridExchangeFreeSwitchTest.java
Signed-off-by: Anton Vinogradov <av@apache.org>
(cherry picked from commit 0e6b97edc1d6a1faba5efa10d69e6eb69c78ae24)
> IGNITE-12470 into 2.8 Pme-free switch feature should be deactivatable (#7304)

- modules/platforms/dotnet/build.ps1
Fix missing .NET Core publish directory
> IGNITE-12604 .NET: Fix file copy logic in build script

- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/impl/MetricUtils.java
- modules/core/src/main/java/org/apache/ignite/spi/metric/jmx/MetricRegistryMBean.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/JmxExporterSpiTest.java
…se when histogram name contains underscore character
> IGNITE-12768: MetricRegistryMBean doesn't show histogram values in case when histogram name contains underscore character

- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/ChangeStateCommandHandlerTest.java
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/MvccJdbcTransactionFinishOnDeactivatedClusterSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/client/GridClientClusterState.java
- modules/core/src/main/java/org/apache/ignite/internal/client/impl/GridClientClusterStateImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/client/impl/connection/GridClientConnection.java
- modules/core/src/main/java/org/apache/ignite/internal/client/impl/connection/GridClientNioTcpConnection.java
- modules/core/src/main/java/org/apache/ignite/internal/cluster/IgniteClusterImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/commandline/ActivateCommand.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/IGridClusterStateProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/cluster/GridChangeClusterStateCommandHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/cluster/GridChangeStateCommandHandler.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/client/AdditionalSecurityCheckTest.java
IGNITE-12773 : Reduce number of cluster deactivation methods in internal API.
> IGNITE-12773 : Reduce number of cluster deactivation methods in internal API.

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/H2ConnectionWrapper.java
- modules/indexing/src/test/java/org/apache/ignite/sqltests/BaseSqlTest.java
PR (Forbid empty sql schema name) from Aleksei_Litsov@epam.com
> IGNITE-8152 Forbid empty sql schema name

- .travis.yml
> IGNITE-12918 .NET: Add Travis job

- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryCancel.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/cache/query/RegisteredQueryCursor.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridReduceQueryExecutor.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/KillQueryErrorOnCancelTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/KillQueryFromClientTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/KillQueryOnClientDisconnectTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/KillQueryTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite.java
(cherry picked from commit b0e923e474ddd32cdd97b9c02d4c8cd8beebb8e6)
> IGNITE-12732 Fix for KILL QUERY command hanging. (#7498)

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheGroupsMetricsRebalanceTest.java
> IGNITE-12927: The CacheGroupsMetricsRebalanceTest.testRebalancingLastCancelledTime is flacky

- checkstyle/checkstyle.xml
- modules/clients/src/test/java/org/apache/ignite/internal/client/integration/ClientAbstractConnectivitySelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheIteratorConverter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryAcknowledgeBuffer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridCachePartitionedUnloadEventsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/service/GridServiceProcessorProxySelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/util/GridConcurrentMultiPairQueueTest.java
- modules/core/src/test/java/org/apache/ignite/messaging/IgniteMessagingSendAsyncTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteReproducingSuite.java
- modules/hadoop/src/main/java/org/apache/ignite/internal/processors/hadoop/impl/fs/HadoopLazyConcurrentMap.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteBinaryObjectFieldsQuerySelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/LongIndexNameTest.java
- modules/web-console/web-agent/src/main/java/org/apache/ignite/console/agent/db/dialect/DatabaseMetadataDialect.java
Fix codestyle issues and add the check rule
> IGNITE-12959 Add support for GenericWhitespace to checkstyle rules

- RELEASE_NOTES.txt
> ignite-2.8.1-release-notes

- modules/core/src/main/java/org/apache/ignite/internal/marshaller/optimized/OptimizedMarshaller.java
- modules/core/src/main/java/org/apache/ignite/internal/marshaller/optimized/OptimizedObjectPooledStreamRegistry.java
- modules/core/src/main/java/org/apache/ignite/internal/marshaller/optimized/OptimizedObjectSharedStreamRegistry.java
- modules/core/src/main/java/org/apache/ignite/internal/marshaller/optimized/OptimizedObjectStreamRegistry.java
- modules/core/src/test/java/org/apache/ignite/internal/marshaller/optimized/OptimizedObjectStreamSelfTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteReproducingSuite.java
> IGNITE-13032 Use non-static stream pool for optimized marshaller.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryListener.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryManager.java
> IGNITE-13082 Fix deadlock between topology update and CQ registration.

- README.md
How the README.md looks like:
https://github.com/Mmuzaf/ignite/blob/ignite-13089/README.md
> IGNITE-13089: add README.md project activity status

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheAffinitySharedManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/mvcc/CacheMvccConfigurationValidationTest.java
Validate and enable MVCC if cache will not start
> IGNITE-13051 still validate MVCC if cache will not start

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteCache15ClientsTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteCacheMultiClientsStartTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheMvccTestSuite6.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite6.java
> IGNITE-13108: decrease number of parallel starting clients for test

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> IGNITE-13122: Fix NullPointerException on snapshot deletion

- modules/core/src/test/java/org/apache/ignite/testframework/junits/GridAbstractTest.java
> IGNITE-13066: Print which tests start in quite mode too

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
> IGNITE-13155: Fix NullPointerException on in-memory cluster for snapshot creation

- modules/visor-console/src/main/scala/org/apache/ignite/visor/commands/start/VisorStartCommand.scala
- parent/pom.xml
> IGNITE-13172 Fix ignite-scalar module compilation on JDK 11+

- examples/src/main/java/org/apache/ignite/examples/ml/sql/DecisionTreeClassificationTrainerSQLInferenceExample.java
- examples/src/main/java/org/apache/ignite/examples/ml/sql/DecisionTreeClassificationTrainerSQLTableExample.java
- modules/ml/src/main/java/org/apache/ignite/ml/selection/scoring/evaluator/package-info.java
> IGNITE-12903 Fixed ML + SQL examples

- modules/kubernetes/DEVNOTES.txt
- modules/kubernetes/config/Dockerfile
- modules/kubernetes/config/ignite-account-role.yaml
- modules/kubernetes/config/ignite-deployment.yaml
- modules/kubernetes/config/ignite-role-binding.yaml
- modules/kubernetes/config/ignite-service-account.yaml
Fix issues while start kubernetes plain example
> IGNITE-13257 update kubernetes plain example

- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/ZookeeperDiscoverySpi.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZkIgnitePaths.java
- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/ZookeeperDiscoverySpiTestSuite1.java
- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperValidatePathsTest.java
…ry dependency to Apache Curator. …
> IGNITE-13291 Add path validation to Ignite codebase. Remove unnecessary dependency to Apache Curator.

- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/setup.py
> ducktape to v0.7.8

- modules/sqlline/pom.xml
> IGNITE-13215: set dependency sqlline version 1.9.0

- modules/ducktests/tests/ignitetest/services/zk/zookeeper.py
```
(ducktape) ➜  tests git:(zk-waitnode-fix) ✗ /usr/bin/zsh  /home/ivandasch/Job/ignite/modules/ducktests/tests/check_style.sh 
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```
```
================================================================================
SESSION REPORT (ALL TESTS)
ducktape version: 0.7.8
session_id:       2020-07-31--002
run time:         10 minutes 23.634 seconds
tests run:        9
passed:           9
failed:           0
ignored:          0
================================================================================
```
> Fix zk wait for finishing node.

- .travis.yml
> IGNITE-13318 Update travis configuration for spark compilation under jdk11

- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/tests/control_utility_test.py
- modules/ducktests/tests/ignitetest/tests/utils/__init__.py
- modules/ducktests/tests/ignitetest/tests/utils/_mark.py
> Ignite ducktape test decorators

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/AbstractExporterSpiTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/JmxExporterSpiTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/metric/SqlViewExporterSpiTest.java
- [Apache Ignite Teamcity Bot](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Igni …
> IGNITE-13347: InitialSize, MaxSize added to data region metrics

- docs/_data/toc.yaml
- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/TDE.java
- docs/_docs/security/master-key-rotation.adoc
> IGNITE-12492 TDE - Phase-2. Documentation.

- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/JavaThinClient.java
- docs/_docs/thin-client-comparison.csv
- docs/_docs/thin-clients/java-thin-client.adoc
> IGNITE-13330 Java thin client documentation update

- modules/ducktests/tests/tox.ini
> Ignite ducktape set pylint

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/metastorage/MetaStorage.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/JmxExporterSpiTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/metric/SqlViewExporterSpiTest.java
> IGNITE-13427 Fix Metastore view iteration on unmarshalleable keys

- modules/ducktests/tests/ignitetest/tests/cellular_affinity_test.py
- modules/ducktests/tests/ignitetest/tests/discovery_test.py
- modules/ducktests/tests/ignitetest/utils/__init__.py
- modules/ducktests/tests/tox.ini
> Add check codestyle (flake8)

- modules/clients/src/test/java/org/apache/ignite/internal/client/suite/IgniteClientTestSuite.java
- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorBeforeNodeStartSelfTest.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/WarmUpCommand.java
- modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/CommandHandlerParsingTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/GridRestProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/protocols/tcp/GridTcpRestNioListener.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/request/GridRestAuthenticationRequest.java
- modules/rest-http/src/main/java/org/apache/ignite/internal/processors/rest/protocols/http/jetty/GridJettyRestHandler.java
> IGNITE-13435 Fix uncovered issues for command "warm-up" of control.sh

- docs/_docs/restapi.adoc
- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAbstractSelfTest.java
> IGNITE-12977 Documentation.

- docs/_docs/restapi.adoc
> IGNITE-12977 Minor formatting issues.

- docs/_docs/persistence/snapshots.adoc
> IGNITE-12968 fix snapshot documentation minor issues

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/database/H2TreeIndex.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> IGNITE-13477 Fix NPE in SQL tracing implementation.

- docs/_data/toc.yaml
- docs/_docs/security/sandbox.adoc
> IGNITE-12443 Document the Ignite Sandbox

- docs/_docs/SQL/ODBC/odbc-driver.adoc
- docs/_docs/includes/cpp-linux-build-prerequisites.adoc
- docs/_docs/includes/cpp-prerequisites.adoc
- docs/_docs/quick-start/cpp.adoc
- docs/_docs/thin-clients/cpp-thin-client.adoc
> IGNITE-13459 Document new building process of Ignite C++ (CMake)

- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/metric/SqlViewExporterSpiTest.java
> IGNITE-13486 testBinaryMeta fixed

- docs/_docs/sql-reference/operational-commands.adoc
> KILL commands docs added.

- docs/_docs/monitoring-metrics/system-views.adoc
> PAGE_LISTS and PARTITION_STATES views documentation

- docs/_docs/code-snippets/dotnet/DataStreaming.cs
- docs/_docs/code-snippets/dotnet/SqlJoinOrder.cs
- docs/_docs/code-snippets/dotnet/ThinClient.cs
- docs/_docs/code-snippets/dotnet/dotnet.csproj
- docs/_docs/thin-clients/dotnet-thin-client.adoc
> IGNITE-13331 Document .NET thin client features implemented in 2.9 release

- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryImpl.java
- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryMiscTest.java
> IGNITE-13495: fix ZookeeperDiscoveryImpl#getCoordinator()

- docs/_layouts/default.html
Only updated the ID for GA code.
> changed GA code

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/cellular_affinity_test/CellularPreparedTxStreamer.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/cellular_affinity_test/CellularTxStreamer.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/pme_free_switch_test/LongTxStreamerApplication.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/pme_free_switch_test/SingleKeyTxStreamerApplication.java
- modules/ducktests/tests/ignitetest/tests/cellular_affinity_test.py
- modules/ducktests/tests/ignitetest/tests/pme_free_switch_test.py
> Pme test fix

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCachePartitionExchangeManager.java
- modules/core/src/test/java/org/apache/ignite/failure/ExchangeWorkerWaitingForTaskTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite.java
…onsidered as blocked.
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbre …
> IGNITE-13540 Fix: exchange worker, waiting for new task from queue, considered as blocked.

- modules/core/src/main/java/org/apache/ignite/client/ClientAuthenticationException.java
- modules/core/src/main/java/org/apache/ignite/client/ClientAuthorizationException.java
- modules/core/src/main/java/org/apache/ignite/client/ClientFeatureNotSupportedByServerException.java
- modules/core/src/main/java/org/apache/ignite/client/ClientReconnectedException.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java
- modules/indexing/src/test/java/org/apache/ignite/client/SecurityTest.java
Preserve exception types when rethrowing
> IGNITE-13530 Java thin: Fix exception propagation

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/cellular_affinity_test/CellularTxStreamer.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/pme_free_switch_test/SingleKeyTxStreamerApplication.java
- modules/ducktests/tests/ignitetest/tests/cellular_affinity_test.py
- modules/ducktests/tests/ignitetest/tests/pme_free_switch_test.py
> Ignite 13552

- modules/ducktests/tests/ignitetest/tests/pme_free_switch_test.py
> IGNITE-13571

- modules/core/src/test/java/org/apache/ignite/platform/PlatformProcessUtils.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Compatibility/ClientServerCompatibilityTest.cs
* Improve error handling in PlatformProcessUtils
* Fix NRE in case of failed fixture setup
> IGNITE-13551 .NET: Enable ClientServerCompatibilityTest on Linux - improvements

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/cellular_affinity_test/CellularTxStreamer.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/pme_free_switch_test/LongTxStreamerApplication.java
- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/pme_free_switch_test/SingleKeyTxStreamerApplication.java
- modules/ducktests/tests/docker/run_tests.sh
> IGNITE-13599 Switch tests should have better precision

- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/templates/log4j.xml.j2
> IGNITE-13638 : Bring log config to ducktape tests

- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/GridMetricManager.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/MetricsSelfTest.java
> IGNITE-13627 Metric registry remove not thread safe.

- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformConfigurationUtils.java
- modules/core/src/main/java/org/apache/ignite/util/AttributeNodeFilter.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.DotNetCore.csproj
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.csproj
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/CacheNodeFilterTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/cache-attribute-node-filter.xml
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/full-config.xml
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationSerializerTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
- modules/platforms/dotnet/Apache.Ignite.Core/Cache/Configuration/CacheConfiguration.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Cluster/AttributeNodeFilter.cs
- modules/platforms/dotnet/Apache.Ignite.Core/IgniteConfigurationSection.xsd
* Add CacheConfiguration.NodeFilter
* Add AttributeNodeFilter - the only allowed IClusterNodeFilter implementation for cache node filter, maps to Java attribute filter
> IGNITE-2890 .NET: Add CacheConfiguration.NodeFilter

- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
> Fix regexp in baseline output.

- docs/_docs/clustering/network-configuration.adoc
Improoves description of soLinger property of DiscoverySpi.
> IGNITE-13702 : Fix description of soLinger for DiscoveryTcpSpi.

- modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySpi.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySpiMBeanTest.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/ZookeeperDiscoverySpi.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZkRuntimeState.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryImpl.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryStatistics.java
- modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryMiscTest.java
> IGNITE-13699 Register ZookeeperDiscovery metrics to new metrics framework, fix concurrency bugs.

- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySpi.java
Better place for note of affection several node addresses on failure detection timeout.
> IGNITE-13695 : Move javadoc of affection of several addresses on failure detection.

- examples/pom.xml
- parent/pom.xml
> IGNITE-13724 Fix checkstyle config for dymanic source directories for ignite-examples

- modules/ducktests/tests/ignitetest/tests/discovery_test.py
> IGNITE-13778: fix startup_timeout_sec on discovery_test.py

- modules/core/src/main/java/org/apache/ignite/spi/IgniteSpiOperationTimeoutHelper.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/TcpDiscoveryNodesRing.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryFailoverAbstractSelfTest.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryNetworkIssuesTest.java
couple of missing commits for tcp
IGNITE-13465
IGNITE-13705
Both commits were backported
> Ign 291 tcp

- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/docker/run_tests.sh
- modules/ducktests/tests/ignitetest/tests/client_test.py
- modules/ducktests/tests/ignitetest/tests/control_utility/baseline_test.py
- modules/ducktests/tests/ignitetest/tests/control_utility/tx_test.py
- modules/ducktests/tests/ignitetest/utils/version.py
> IGNITE-13789 Add 2.9.0 version to ducktape tests

- docs/_docs/index.adoc
…/quick-start/java to correct link: https://ignite.apache.org/docs/latest/quick-start/java
- [Coding …
> Fixed broken link

- modules/ducktests/tests/docker/requirements.txt
- modules/ducktests/tests/ignitetest/services/spark.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/zk/zookeeper.py
- modules/ducktests/tests/setup.py
- modules/ducktests/tests/tox.ini
> IGNITE-13828: Change ducktape dependency to own fork

- RELEASE_NOTES.txt
- packaging/deb/changelog
- packaging/rpm/apache-ignite.spec
> IGNITE-13806 | Merge release notes for 2.9.1 into master

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtPartitionsReservation.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/tracing/SpanTags.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/QueryParser.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/PartitionReservationManager.java
- modules/opencensus/src/test/java/org/apache/ignite/internal/processors/monitoring/opencensus/AbstractTracingTest.java
- modules/opencensus/src/test/java/org/apache/ignite/internal/processors/monitoring/opencensus/OpenCensusSqlJdbcTracingTest.java
- modules/opencensus/src/test/java/org/apache/ignite/internal/processors/monitoring/opencensus/OpenCensusSqlNativeTracingTest.java
> IGNITE-13456 Extends info collected during tracing of SQL queries.

- modules/core/src/test/java/org/apache/ignite/platform/PlatformDeployServiceTask.java
- modules/core/src/test/java/org/apache/ignite/platform/model/ParamValue.java
- modules/core/src/test/java/org/apache/ignite/platform/model/Parameter.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/IJavaService.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/JavaServiceDynamicProxy.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/Model.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServiceTypeAutoResolveTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs
This PR is a follow-up of c2204cda29e70294cc93756eabc844b64e07a42e. It adds new tests to ensure that .Net -> .Net service call for overloaded methods works as expected.
- [Coding …
> IGNITE-13931 .NET: Add tests for overload service methods

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataStorageMetricsImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/Checkpointer.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteDataStorageMetricsSelfTest.java
> IGNITE-13845 Add checkpoint metrics

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Log/CustomLoggerTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/JavaTypes.cs
(cherry picked from commit 12ee51cec0218e372f7de5eff3e7768ce89d42dd) …
> IGNITE-12090 .NET: logger throws KeyNotFound on creating cache with nullable 'sbyte?' field

- docs/_docs/setup.adoc
- docs/_docs/starting-nodes.adoc
- docs/_docs/tools/control-script.adoc
- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
* control.sh metric command.
* control.sh system view command.
* ignite.sh system properties command
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guid …
> Docs for metric, system view, system properties commands

- docs/_docs/events/events.adoc
> IGNITE-13968 Add snapshot events documentation pages

- docs/_data/toc.yaml
- docs/_docs/monitoring-metrics/performance-statistics.adoc
- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/mxbean/PerformanceStatisticsMBean.java
> IGNITE-13854 Add documentation for the cluster performance profiling tool

- docs/_data/toc.yaml
- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/TDE.java
- docs/_docs/code-snippets/xml/tde.xml
- docs/_docs/monitoring-metrics/new-metrics.adoc
- docs/_docs/security/cache-encryption-key-rotation.adoc
- docs/_docs/security/master-key-rotation.adoc
- docs/_docs/security/tde.adoc
- docs/assets/css/docs.scss
- docs/assets/css/styles.scss
> IGNITE-13659 Cache encryption key rotation (documentation)

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManagerImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/RebalanceIteratorLargeEntriesOOMTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite2.java
> IGNITE-14003 Improve heap consumption on reserving rebalance iterator.

- docs/_docs/events/events.adoc
> IGNITE-14013 Adds documentation for the node validation failure event.

- docs/_docs/persistence/native-persistence-defragmentation.adoc
> IGNITE-13674  Documentation page added for Native Persistence Defragmentation feature

- docs/_docs/memory-configuration/data-regions.adoc
> IGNITE-13385

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/Example.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/ExamplePaths.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/ProjectFilesTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/ThinExamplesTest.cs
Make examples tests framework-agnostic: remove hardcoded versions
> IGNITE-14045 .NET: Fix examples test on .NET Core 3

- modules/ducktests/tests/checks/utils/check_jvm_settings.py
> Add additional unit test for merge jvm

- docs/_docs/monitoring-metrics/metrics.adoc
> IGNITE-13606

- .travis.yml
- modules/ducktests/tests/README.md
- modules/ducktests/tests/docker/requirements.txt
- modules/ducktests/tests/docker/run_tests.sh
- modules/ducktests/tests/ignitetest/services/ignite.py
- modules/ducktests/tests/ignitetest/services/ignite_app.py
- modules/ducktests/tests/ignitetest/services/spark.py
- modules/ducktests/tests/ignitetest/services/utils/background_thread.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py
- modules/ducktests/tests/ignitetest/services/utils/jvm_utils.py
- modules/ducktests/tests/ignitetest/services/zk/zookeeper.py
- modules/ducktests/tests/setup.py
- modules/ducktests/tests/tox.ini
> IGNITE-14046 Update ducktape version to 0.8.2 in ignite-ducktape module

- modules/ducktests/tests/docker/run_tests.sh
> Run tests fix

- docs/_docs/tools/control-script.adoc
> IGNITE-12955 Add documentation pages for index inline size console command

- modules/ducktests/tests/ignitetest/tests/pme_free_switch_test.py
> IGNITE-14105: Fix ignoring tests PmeFreeSwitchTests

- .travis.yml
> IGNITE-14117 Debug maven

- modules/ducktests/tests/ignitetest/tests/cellular_affinity_test.py
- modules/ducktests/tests/ignitetest/tests/pme_free_switch_test.py
- modules/ducktests/tests/ignitetest/tests/ssl_test.py
> IGNITE-14106

- docs/_docs/code-snippets/cpp/src/broadcast_jobs_to_remote_nodes.cpp
- docs/_docs/code-snippets/cpp/src/predefined_cluster_groups.cpp
- docs/_docs/distributed-computing/cluster-groups.adoc
> IGNITE-14133 Document cluster API implementation for CPP

- docs/_docs/monitoring-metrics/tracing.adoc
> IGNITE-13981 Documentation: SQL tracing.

- RELEASE_NOTES.txt
> IGNITE-14069 added release notes for 2.10 version

- docs/_docs/net-specific/net-deployment-options.adoc
- modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.targets
* Update NuGet specifics
* Document how to exclude jar files from build output with `<ExcludeAssets>build</ExcludeAssets>`
> IGNITE-10073 .NET: Document how to exclude jar files from build output

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FilePageStore.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FilePageStoreManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FilePageStoreV2.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FileVersionCheckingFactory.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsTaskCancelingTest.java
> IGNITE-14141 Remove unnecessary storage configuration from PageStore

- modules/clients/src/test/java/org/apache/ignite/jdbc/JdbcAuthorizationTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/closure/GridClosureProcessor.java
> IGNITE-13472 fix security context for JDBC bulkload operations

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/CheckpointWorkflow.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/file/IgnitePdsCheckpointSimpleTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsMvccTestSuite.java
> IGNITE-14139 Incorrect initialize checkpoint-runner-cpu thread pool

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/freelist/PagesList.java
> IGNITE-14140 Checkpointer thread holds write lock too long

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheValidateIndexes.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_cache_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_cache_help.output
> IGNITE-14168 fix description of validate_indexes command

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/CommandList.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/performancestatistics/PerformanceStatisticsCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/performancestatistics/PerformanceStatisticsSubCommand.java
- modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/CommandHandlerParsingTest.java
- modules/control-utility/src/test/java/org/apache/ignite/testsuites/IgniteControlUtilityTestSuite.java
- modules/control-utility/src/test/java/org/apache/ignite/util/PerformanceStatisticsCommandTest.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/performancestatistics/VisorPerformanceStatisticsOperation.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/performancestatistics/VisorPerformanceStatisticsTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/performancestatistics/VisorPerformanceStatisticsTaskArg.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/performancestatistics/AbstractPerformanceStatisticsTest.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output
> IGNITE-14191 Add command to control.(sh|bin) to manage performance statistics

- .gitignore
- modules/ducktests/tests/checks/utils/check_enum_constructible.py
> IGNITE-14192: added modules/ducktests/tests/certs to .gitignore

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTest.Misc.cs
- modules/platforms/dotnet/Apache.Ignite.Linq/Impl/CacheQueryModelVisitor.cs
>  IGNITE-5266 .NET: Add LongCount to LINQ provider

- docs/_docs/monitoring-metrics/metrics.adoc
- docs/_docs/monitoring-metrics/new-metrics-system.adoc
> IGNITE-14261 Add documentation references to the new metrics system

- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/WarmUpStrategy.java
- docs/_docs/code-snippets/xml/warm-up-strategy.xml
- docs/_docs/memory-configuration/data-regions.adoc
> Ignite 13385 3

- docs/_docs/monitoring-metrics/metrics.adoc
> IGNITE-14143 Document metric for processed keys when rebuilding indexes.

- modules/sqlline/bin/sqlline.bat
- modules/sqlline/bin/sqlline.sh
> IGNITE-14285 Fix sqlline history file location

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> IGNITE-14286 Fix snapshot check command on cluster with client nodes

- docs/_docs/thin-clients/cpp-thin-client.adoc
> IGNITE-14144 Document C++ thin client transactions

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/SortedReduceIndexAdapter.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheParallelismQuerySortOrderTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite.java
> IGNITE-14177 fix NULLS LAST/FIRST sorting if set query parallelism

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.csproj
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/Model.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/PlatformTestService.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTypeAutoResolveTest.cs
Currently, `IJavaService` methods in `ServicesTest` and `ServicesTypeAutoResolveTest` only checked for .Net -> Java case. 
This PR extends it with .Net -> .Net invocation.
- [Coding …
> IGNITE-14313 .NET: Add tests for .NET -> .NET service calls

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FilePageStoreManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotFutureTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotMetadata.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyTask.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckWithIndexesTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgnitePdsWithIndexingTestSuite.java
> IGNITE-14305 Fix snapshot check command for indexes

- docs/Gemfile
- docs/_data/toc.yaml
- docs/_docs/persistence/snapshot-directory.adoc
- docs/_docs/snapshots/snapshots.adoc
- docs/_docs/tools/control-script.adoc
> IGNITE-14247 Add snapshot page, add checking snapshot commands

- modules/core/src/main/java/org/apache/ignite/cache/store/jdbc/dialect/OracleDialect.java
- modules/core/src/test/java/org/apache/ignite/cache/store/jdbc/dialect/OracleDialectTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite.java
> IGNITE-14214 Fix merge query with no unique colons for the Oracle dialect

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/WriteAheadLogManagerSelfTest.java
> IGNITE-14130 Fixing NullPointerException for automatic archiving WAL segment

- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/ignitetest/utils/version.py
> IGNITE-14329 Set 2.9.1 as LATEST_2.9 and 2.10 as LATEST

- modules/ducktests/tests/ignitetest/tests/__init__.py
> Add hash of params to test results and test name.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/WriteAheadLogManagerSelfTest.java
> IGNITE-14373 Fix race between auto rollover WAL segment and deactivate of WAL

- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
Remove U.sleep(200) from the node ping.
> IGNITE-14378 : Remove delay from node ping

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/rebalance/DataGenerationApplication.java
- modules/ducktests/tests/ignitetest/services/ignite.py
- modules/ducktests/tests/ignitetest/services/ignite_app.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/tests/discovery_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/__init__.py
- modules/ducktests/tests/ignitetest/tests/rebalance/in_memory_test.py
> IGNITE-14300 Rebalance speed as part of test result data

- modules/ducktests/tests/ignitetest/tests/rebalance/in_memory_test.py
> IGNITE-14395 Shorter test results directory name

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/FileLockHolder.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/PdsConsistentIdProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/filename/PdsFolderSettings.java
> IGNITE-14360 Refactor FileLockHolder for reusage

- modules/ducktests/tests/ignitetest/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/utils/version.py
> IGNITE-14396: fixed snapshot test on ducktape

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/rebalance/DataGenerationApplication.java
- modules/ducktests/tests/ignitetest/tests/rebalance/__init__.py
- modules/ducktests/tests/ignitetest/tests/rebalance/in_memory_test.py
> IGNITE-14391 Multi-node cache data preloading

- modules/ducktests/tests/checks/utils/check_dev_version.py
- modules/ducktests/tests/ignitetest/utils/version.py
- pom.xml
> IGNITE-14422: Version management for ducktape.

- modules/ducktests/tests/ignitetest/tests/rebalance/__init__.py
- modules/ducktests/tests/ignitetest/tests/rebalance/in_memory_test.py
> IGNITE-14390 Add rebalance statistic to test result data

- docs/_data/toc.yaml
- docs/_docs/extensions-and-integrations/performance-statistics.adoc
- docs/_docs/monitoring-metrics/performance-statistics.adoc
> IGNITE-14417 Document performance-statistics-ext module

- docs/_data/toc.yaml
- docs/_docs/extensions-and-integrations/spring/spring-tx.adoc
> IGNITE-14397 Documents spring-tx integration.

- docs/_docs/extensions-and-integrations/spring/spring-data.adoc
> IGNITE-14398 Documents thin client support for spring-data integration.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManagerImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IndexStorage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IndexStorageImpl.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/DurableBackgroundCleanupIndexTreeTask.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/database/H2TreeIndex.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/CleanupIndexTreeCheckpointFailoverTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteCacheWithIndexingAndPersistenceTestSuite.java
> IGNITE-14447 Fixed possible meta tree corruption after drop index with failed checkpoint scenario.

- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/ConnectionClientPool.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/GridNioServerWrapper.java
> IGNITE-14448 Fix hanging of node if the inverse connection is requested and paired connections are enabled

- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/path.py
- modules/ducktests/tests/ignitetest/tests/self_test.py
…n.xml for ducktests.
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbrev …
> IGNITE-14455: The directory with logs must contain IgniteConfiguration.xml for ducktests.

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteDataStorageMetricsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/IgniteLocalWalSizeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/WriteAheadLogManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/WalArchiveConsistencyTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/common/GridCommonAbstractTest.java
> IGNITE-14458 Fix flaky IgniteLocalWalSizeTest

- modules/ducktests/tests/docker/ducker-ignite
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
This PR allows to run ducktape tests for third party Ignite based tests.
* With `DOCKER_OPTIONS` user can specify additional mount points for docker image.
* `project` name can be specified in globals to run tests for another product. …
> IGNITE-14463 Support of testing Ignite based products with ducktape tests

- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/tests/discovery_test.py
Sometimes, we lack settings of iptables for unknows reason. Let's monitor this issue.
> Ignite-14452 : Add checking of the iptables settings applied

- docs/_docs/extensions-and-integrations/spring/spring-data.adoc
- docs/_docs/extensions-and-integrations/spring/spring-tx.adoc
> IGNITE-14493 Documents versions of Spring integration extensions.

- .gitignore
- modules/ducktests/tests/ignitetest/services/ignite.py
- modules/ducktests/tests/ignitetest/services/ignite_app.py
- modules/ducktests/tests/ignitetest/services/spark.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/tests/discovery_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/__init__.py
> IGNITE-14483 Ignite_app and ignite clean_up

- docs/_docs/includes/partition-awareness.adoc
- docs/_docs/installation/kubernetes/generic-configuration.adoc
As per IGNITE-14491, https://ignite.apache.org/docs/latest/installation/kubernetes/amazon-eks-deployment#partition-awareness page had an incorrect note and a REST connectivity section in the wrong place. This PR fixes it. …
> IGNITE-14491-moving-sections-and-deleting-incorrect-note

- docs/_docs/includes/cpp-prerequisites.adoc
- docs/_docs/includes/dotnet-prerequisites.adoc
- docs/_docs/includes/java9.adoc
- docs/_docs/includes/prereqs.adoc
- docs/_docs/quick-start/java.adoc
- modules/platforms/dotnet/DEVNOTES.txt
- modules/platforms/dotnet/build.ps1
- modules/platforms/dotnet/release/verify-nuget.ps1
Ignite only works with Java 8 and 11, not 8+. This patch applies correct versions across the boart.
- …
> IGNITE-14404-specify-correct-java-versions

- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/impl/MetricUtils.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/TcpDiscoveryStatistics.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/MetricsSelfTest.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryStatistics.java
Current PR constraints name of the metrics that can be registered through MetricRegistry#register(Metric) - it must start with the name of metric registry it's registered into.
The purpose of this change is to make all metrics that belongs to one MetricRegistry have the name that obeys mentioned above  rule regardless how they were registered. It helps to use a consistent approach to work with all metrics.
The following metric names was changed to obey this rule:
JoinedNodes -> io.discovery.JoinedNodes 
LeftNodes -> io.discovery.LeftNodes
FailedNodes -> io.discovery.FailedNodes 
PendingMessagesRegistered -> io.discovery.PendingMessagesRegistered
CommunicationErrors -> io.discovery.CommunicationErrors
CurrentTopologyVersion -> io.discovery.CurrentTopologyVersion 
Thank you for submitting …
> IGNITE-14428 Formalizes the names of the metrics included in the metric registry.

- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/path.py
> IGNITE-14585 IgniteSpec can provide arbitrary configs

- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/__init__.py
> IGNITE-14592 Incapsulate configuration preparation

- modules/core/src/main/java/org/apache/ignite/internal/processors/localtask/DurableBackgroundTasksProcessor.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/LongDestroyDurableBackgroundTaskTest.java
> IGNITE-14497 Move background task deletion at the end of next checkpoint

- modules/ducktests/tests/ignitetest/services/ignite.py
- modules/ducktests/tests/ignitetest/services/ignite_app.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py
- modules/ducktests/tests/ignitetest/tests/snapshot_test.py
> IGNITE-14601 Specs should use service's params instead of copying.

- modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/snapshot_test/DataLoaderApplication.java
- modules/ducktests/tests/ignitetest/tests/snapshot_test.py
> IGNITE-14622 Snapshot test simplification

- modules/ducktests/tests/ignitetest/services/ignite.py
- modules/ducktests/tests/ignitetest/services/ignite_app.py
> IGNITE-14618 Increase stop timeout to 60 seconds

- modules/ducktests/README.md
> IGNITE-14629 Update ducktests documentation about forks run (form releases or sources)	

- docs/_docs/extensions-and-integrations/spring/spring-data.adoc
> IGNITE-14662 Updates dependency artifactId in spring-data extension documentation.

- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
> IGNITE-14688 Fix testDetectPeerDeployAwareInfiniteRecursion failure.

- modules/core/src/main/java/org/apache/ignite/internal/GridKernalContext.java
- modules/core/src/main/java/org/apache/ignite/internal/GridKernalContextImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/CheckpointWorkflow.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneGridKernalContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/localtask/DurableBackgroundTasksProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/localtask/DurableBackgroundTasksProcessorSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/localtask/ObservingCheckpointListener.java
> IGNITE-14684 Fixed node fail due to deleting DurableBackgroundTask's at the end of a checkpoint when stopping a node

- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinAuthenticateConnectionSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteKernal.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/authentication/IgniteAuthenticationProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/security/SecurityUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/authentication/Authentication1kUsersNodeRestartTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/authentication/AuthenticationProcessorSelfTest.java
> IGNITE-14675 Refactors IgniteAuthenticationProcessor callbacks.

- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ClientImpl.java
> IGNITE-14729 Fix race condition in ClientImpl

- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/tests/discovery_test.py
Added checking of iptables-legacy in certain code place.
> IGNITE-14485 : Docker execution fail on iptables change

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/Checkpointer.java
> IGNITE-14771 Fixed deadlock in GridCacheDataStore initialization.

- modules/core/src/test/java/org/apache/ignite/internal/metric/IoStatisticsSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewComputeJobTest.java
> IGNITE-14783 SystemViewComputeJobTest.testCancelComputeTask fixed

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessorTest.java
- modules/calcite/src/test/sql/order/test_nulls_first.ignore
- modules/calcite/src/test/sql/order/test_nulls_first.test
> IGNITE-14779 Unblock NULLS FIRST|LAST functionality checks

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerMetadataTest.java
- modules/core/src/main/java/org/apache/ignite/internal/commandline/meta/tasks/MetadataInfoTask.java
> IGNITE-14801 Add tests for commands to manage metadata

- examples/pom-standalone-lgpl.xml
- examples/pom-standalone.xml
Add kubernetes dep to examples standalone poms.
> IGNITE-14781 Add kubernetes dep to examples standalone poms

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
> IGNITE-14894

- modules/clients/src/test/java/org/apache/ignite/common/NodeSslConnectionMetricTest.java
- modules/clients/src/test/java/org/apache/ignite/common/SslConnectorsMetricTest.java
- modules/clients/src/test/java/org/apache/ignite/internal/client/suite/IgniteClientTestSuite.java
- modules/core/src/main/java/org/apache/ignite/internal/client/impl/connection/GridClientConnectionManagerAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/client/router/impl/GridTcpRouterImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/io/gridnioserver/GridNioClientConnectionMultiplexer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/protocols/tcp/GridTcpRestProtocol.java
- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
- modules/core/src/main/java/org/apache/ignite/internal/util/nio/ssl/GridNioSslFilter.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/GridNioServerWrapper.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySpi.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/TcpDiscoveryStatistics.java
- modules/core/src/test/java/org/apache/ignite/internal/util/nio/GridNioSslSelfTest.java
The PR adds the following new metrics:
sslHandshakeDurationHistogram  - provides the histogram of SSL handshake duration c.
sslRejectedSessionsCount - provides the number of rejected connections due to SSL errors (not exported if ssl is disabled).
sslEnabled - indicates whether SSL is enabled for the connector
activeSessionsCount - provides the number of active TCP sessions
Each of the mentioned above metrics was added to the following metric groups that relate to different connectors (SSL is configured separately for each of them)
(NEW) client.connector.tcp - for metrics related to thin client connector SSL metrics.
(NEW) client.connector.rest.tcp - for metrics related to REST TCP client connector SSL metrics.
communication.tcp - for metrics related to node communicatonconnector SSL …
> IGNITE-14658 Adds connector SSL metrics.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteSpeedBasedThrottle.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/IgniteThrottlingUnitTest.java
> IGNITE-14899 Fix PagesWriteSpeedBasedThrottle time to throttle calculation

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/UnstableTopologyTest.java
- modules/calcite/src/test/java/org/apache/ignite/testsuites/IntegrationTestSuite.java
> IGNITE-13587 Additional calcite tests with unstable topology

- docs/_docs/persistence/native-persistence.adoc
> IGNITE-14932 Reference to the Ignite Storage Overview video

- modules/ducktests/tests/ignitetest/tests/thin_client_test.py
With this change you can override defaults of Thin Client test ["DEV", "LATEST"] to something different
for example:
"project":"ignite","ignite_versions":["2.10.0","dev"]
"project":"superfork","ignite_versions":["100500","13","dev"] …
> IGNITE-14780 Thin client test should use versions from globals

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/DataStorageConfigurationValidationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/WalArchiveSizeConfigurationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/WalArchiveConsistencyTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite.java
> IGNITE-14923

- modules/core/src/main/java/org/apache/ignite/cdc/CdcConfiguration.java
- modules/core/src/main/java/org/apache/ignite/cdc/CdcConsumer.java
- modules/core/src/main/java/org/apache/ignite/cdc/CdcEvent.java
- modules/core/src/main/java/org/apache/ignite/cdc/CdcLoader.java
- modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcConsumerState.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcEventImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcFileLockHolder.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/WalRecordsConsumer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/main/java/org/apache/ignite/startup/cmdline/CdcCommandLineStartup.java
- modules/core/src/test/java/org/apache/ignite/cdc/AbstractCdcTest.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcCacheVersionTest.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/reader/IgniteWalReaderTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite2.java
- modules/indexing/src/test/java/org/apache/ignite/internal/cdc/SqlCdcTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite.java
- modules/spring/src/test/config/cdc/cdc-config-without-persistence.xml
- modules/spring/src/test/config/cdc/correct-cdc-config.xml
- modules/spring/src/test/config/cdc/double-cdc-config.xml
- modules/spring/src/test/java/org/apache/ignite/cdc/CdcConfigurationTest.java
- modules/spring/src/test/java/org/apache/ignite/testsuites/IgniteSpringTestSuite.java
> ChangeDataCapture -> Cdc

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotCommand.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output
> IGNITE-14989 Control utility help output fix.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridCacheTxRecoveryFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtLockFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxPrepareFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/colocated/GridDhtColocatedLockFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearLockFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearOptimisticSerializableTxPrepareFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearOptimisticTxPrepareFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearPessimisticTxPrepareFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxFinishFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxQueryEnlistFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/util/future/GridCompoundFuture.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/metastorage/DistributedMetaStorageTest.java
> IGNITE-15017 Contention in lock on Compound future

- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/Snapshots.java
- docs/_docs/snapshots/snapshots.adoc
> IGNITE-14722 Automatic snapshot restore documentation.

- docs/_docs/monitoring-metrics/new-metrics.adoc
> IGNITE-14901 Documents Discovery and SSL metrics.

- docs/_docs/monitoring-metrics/system-views.adoc
> IGNITE-15063 Documents system views obtaining through a control script.

- modules/calcite/pom.xml
> Calcite. Ignite node runner script failed to start instance

- modules/calcite/pom.xml
> IGNITE-15076 Calcite. Ignite node runner script failed to start instance

- modules/core/src/main/java/org/apache/ignite/IgniteBinary.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientBinary.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/CacheObjectBinaryProcessorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/IgniteBinaryImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cacheobject/IgniteCacheObjectProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cacheobject/NoOpBinary.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/binary/BinaryMetadataRegisterClassTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBinaryObjectsTestSuite.java
> IGNITE-15065 Add an explicit method to register binary type based on class

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/IndexRenameRootPageRecord.java
- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/WALRecord.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManagerImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IndexStorage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IndexStorageImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordDataV1Serializer.java
- modules/core/src/test/java/org/apache/ignite/testframework/wal/record/RecordUtils.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/index/QueryIndexDefinition.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/AbstractRebuildIndexTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/RenameIndexTreeTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/ResumeCreateIndexTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgnitePdsWithIndexingTestSuite.java
> IGNITE-15050 Add rename index tree to drop index

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessor.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/ExpressionFactoryImpl.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/IgnitePlanner.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rule/CorrelatedNestedLoopJoinRule.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rule/LogicalScanConverterRule.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rule/TableFunctionScanConverterRule.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessorTest.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/FunctionsTest.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/logical/SqlScriptRunner.java
- modules/calcite/src/test/sql/subquery/test_neumann.test
> IGNITE-13159 Correlated queries support

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/WALRecord.java
Reserve WALRecord type ID for tombstones.
> IGNITE-11704 Add PARTITION_META_PAGE_DELTA_RECORD_V4 WALRecord type placeholder

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/ExchangeServiceImpl.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/ExecutionServiceImpl.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/rel/RootNode.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/message/ExecutionContextAware.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/message/MessageServiceImpl.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/message/TestIoManager.java
> IGNITE-15122 Calcite. Remove sync mode of RootNode#closeInternal

- docs/_data/toc.yaml
> IGNITE-14392 Hid SQL Transactions page from TOC

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/IgniteSqlValidator.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/TableDmlIntegrationTest.java
> IGNITE-15123 Calcite. Multi-tuple insert fails on validation

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreSelfTest.java
> IGNITE-15170 Fixed incorrect comparison of consistent IDs during snapshot restore.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/IgniteWalIteratorFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneGridKernalContext.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIterator.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
> IGNITE-15146 Handle lifecycle properly for the standalone context

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/IgniteWalIteratorFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIterator.java
> IGNITE-15205 Fix standalone records iterator for existing context

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/WalArchiveSizeConfigurationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManagerSelfTest.java
> IGNITE-15243 Return the IGNITE_THRESHOLD_WAL_ARCHIVE_SIZE_PERCENTAGE and deprecate it

- modules/core/src/main/java/org/apache/ignite/IgniteCache.java
- modules/core/src/main/java/org/apache/ignite/events/CacheConsistencyViolationEvent.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridPartitionedGetFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/consistency/GridNearReadRepairAbstractFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/consistency/GridNearReadRepairCheckOnlyFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/consistency/GridNearReadRepairFuture.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/AbstractFullSetReadRepairTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/AbstractReadRepairTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/AtomicReadRepairTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/ExplicitTransactionalReadRepairTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/ImplicitTransactionalReadRepairTest.java
> IGNITE-15180 Read Repair should generate Event even when nothing fixed but broken (eg. atomics check).

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/IgniteWriteAheadLogManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/aware/SegmentArchiveSizeStorage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/aware/SegmentAware.java
- modules/core/src/test/java/org/apache/ignite/cache/AbstractReleaseSegmentTest.java
- modules/core/src/test/java/org/apache/ignite/cache/AutoReleaseSegmentSelfTest.java
- modules/core/src/test/java/org/apache/ignite/cache/ReleaseSegmentOnHistoricalRebalanceTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/NoOpWALManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/aware/SegmentAwareTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite4.java
> IGNITE-15246 Error when starting a node when exceeding the DataStorageConfiguration#getMaxWalArchiveSize

- modules/core/src/main/java/org/apache/ignite/spi/metric/jmx/JmxMetricExporterSpi.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/JmxExporterSpiTest.java
> IGNITE-15252 Fix the AssertionError when the JmxMetricExporterSpi unregister a filtered metric registry

- docs/_docs/data-modeling/data-partitioning.adoc
> IGNITE-15238 Add a reference on data partitioning deep-dive

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
> IGNITE-15273 Triple flushing of meta information at the checkpoint

- parent/pom.xml
> Ignite 15261

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionDemander.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPreloader.java
> IGNITE-15208 Fix rebalance procedure if delay greater that zero

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtLocalPartition.java
> IGNITE-15282 Remove unused the private clear method in GridDhtLocalPartition

- parent/pom.xml
> IGNITE-15301 update Ignite dependency Bouncycastle

- parent/pom.xml
> IGNITE-15292 Update dependency httpclient&&httpcore

- modules/core/src/test/java/org/apache/ignite/internal/encryption/CacheGroupKeyChangeTest.java
> IGNITE-15232 fix flaky test CacheGroupKeyChangeTest.testWalArchiveCleanup

- docs/_docs/sql-reference/transactions.adoc
> IGNITE-15349 Fixed feedback-4

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexingUtils.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/pagemem/store/IgnitePageStoreManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManagerImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionDemander.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionSupplier.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtLocalPartition.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtPartitionTopologyImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/RowStore.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/Checkpointer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FilePageStoreManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/metastorage/MetaStorage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/migration/UpgradePendingTreeToPerPartitionTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/PendingTreeCorruptionTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/RestorePartitionStateDuringCheckpointTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/IgnitePdsWithTtlTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/NoOpPageStoreManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/memtracker/PageMemoryTracker.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/CacheScanQueryFailoverTest.java
> IGNITE-15283 Remove duplicated managing of CacheDataStore in offheap manager

- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
> IGNITE-15367 Fix unnecessary socket shutdown and close log output

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/NoUnnecessaryRebalanceTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/NoUnnecessaryRebalancesTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite4.java
- modules/core/src/test/java/org/apache/ignite/util/TestStorageUtils.java
> IGNITE-15355 Fix method corruptDataEntry used for tests

- modules/core/src/main/java/org/apache/ignite/internal/processors/security/SecurityUtils.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/isolated/IsolatedDiscoverySpi.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/isolated/IsolatedNode.java
- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/maintenance/MaintenanceModeNodeSecurityTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
- modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoveryImpl.java
> IGNITE-15378 Fixes node restart in maintenance mode with security enabled.

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexForceRebuildTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexRebuildStatusTest.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/IndexProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/indexing/IndexesRebuildTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/IndexRebuildCancelToken.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaIndexCacheFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaIndexCachePartitionWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaIndexCacheVisitorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaIndexOperationCancellationException.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaOperationWorker.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/AbstractIndexingCommonTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/DynamicEnableIndexingConcurrentSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/IndexesRebuildTaskEx.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/StopRebuildIndexTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsIndexingDefragmentationTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/GridIndexRebuildSelfTest.java
> IGNITE-15413 Extract cancellation token to rebuild index method

- parent/pom.xml
> IGNITE-15395 update dependency PostgreSQL

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotFutureTask.java
> IGNITE-15427 Improve the snapshot procedure logging

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
> IGNITE-15429 Checkpoint is not always forced when taking a snapshot.

- docs/_docs/code-snippets/k8s/stateful/node-configuration.xml
- docs/_docs/code-snippets/k8s/stateless/node-configuration.xml
> IGNITE-15459 Expanded kubernetes examples examples to include full beans

- docs/_docs/configuring-caches/near-cache.adoc
> IGNITE-15461 Described that thin clients do not receive near caches

- modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/daemon/DaemonNodeBasicSecurityTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
> IGNITE-15384 Fixes execution of daemon node operations that require authorization.

- modules/control-utility/src/test/java/org/apache/ignite/util/SystemViewCommandTest.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteKernal.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/IgniteMBeansManager.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/systemview/GridSystemViewManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/GridMetricManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/pool/PoolProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/JmxExporterSpiTest.java
- modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
- modules/core/src/test/java/org/apache/ignite/thread/ThreadPoolMetricsTest.java
> IGNITE-15457 Moves thread pool metrics registration to PoolProcessor.

- modules/control-utility/src/test/java/org/apache/ignite/testsuites/IgniteControlUtilityTestSuite.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyBinaryTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/consistency/GridNearReadRepairAbstractFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/consistency/GridNearReadRepairCheckOnlyFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/consistency/GridNearReadRepairFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/consistency/VisorConsistencyRepairTask.java
> IGNITE-15482 Read Repair should support binary objects

- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
> IGNITE-15488 Error extension about B+tree lock retry for indexes

- docs/_docs/includes/note-on-deactivation.adoc
- docs/_docs/monitoring-metrics/cluster-states.adoc
Fix documentation for #IGNITE-12779
> IGNITE-15524 : Fix cluster deactivation documentation for the MXBean

- parent/pom.xml
Signed-off-by: chandresh pancholi <chandresh.pancholi@navi.com> …
> [IGNITE-15469] mysql connector dependency upgrade

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteDataStorageMetricsSelfTest.java
> IGNITE-15542 walTotalSize incorrectly reported when wal archiving is turned off.

- docs/_docs/tools/control-script.adoc
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheCommandList.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheCommands.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheDelete.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheDestroy.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheSubcommands.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringBuilder.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/query/VisorQueryUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/util/tostring/GridToStringBuilderSelfTest.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_cache_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_cache_help.output
> IGNITE-15445 Сache destroy command for control.sh

- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/exec/rel/HashAggregateExecutionTest.java
> IGNITE-15654 Calcite engine. Fix the test HashAggregateExecutionTest#countOfEmptyWithRewind

- docs/_docs/extensions-and-integrations/ignite-for-spark/overview.adoc
> IGNITE-15578 Broken documentation links on the website

- pom.xml
> IGNITE-15676 Fix update-version.sh for .NET

- docs/_docs/extensions-and-integrations/spring/spring-caching.adoc
- docs/_docs/extensions-and-integrations/spring/spring-tx.adoc
> IGNITE-15854 Removes documentation notes about Ignite 2.10 and earlier support for spring-cache and spring-tx integrations.

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/IdleVerifyResultV2.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> IGNITE-15849 Remove idle_verify and snapshot check ambiguity error output

- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
> IGNITE-15865: fixed persistence_upgrade_test.py

- docs/_docs/code-snippets/k8s/stateful/node-configuration.xml
- docs/_docs/code-snippets/k8s/stateless/node-configuration.xml
> IGNITE-15862 Fix kubernetes ConfigMap docs on site

- modules/core/src/main/java/org/apache/ignite/internal/binary/builder/BinaryBuilderReader.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryMarshallerSelfTest.java
> IGNITE-15855 BinaryObjectBuilder builds invalid object in case the original object contains several collection or reference fields

- docs/_data/toc.yaml
- docs/_docs/code-deployment/peer-class-loading.adoc
- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/UsingScanQueries.java
- docs/_docs/distributed-computing/collocated-computations.adoc
- docs/_docs/events/events.adoc
- docs/_docs/key-value-api/using-cache-queries.adoc
- docs/_docs/thin-clients/java-thin-client.adoc
- examples/src/main/java/org/apache/ignite/examples/datagrid/CacheQueryExample.java
- examples/src/main/java/org/apache/ignite/examples/model/Person.java
- modules/core/src/main/java/org/apache/ignite/cache/query/IndexQuery.java
> IGNITE-15745 Add docs for IndexQuery

- docs/_docs/services/services.adoc
- examples/src/main/java/org/apache/ignite/examples/servicegrid/SimpleMapServiceImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/resource/GridResourceIoc.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/resource/GridResourceProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/service/GridServiceProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/service/IgniteServiceProcessor.java
- modules/core/src/main/java/org/apache/ignite/resources/ServiceContextResource.java
- modules/core/src/main/java/org/apache/ignite/services/Service.java
- modules/core/src/main/java/org/apache/ignite/services/ServiceContext.java
- modules/spring/src/test/java/org/apache/ignite/internal/processors/resource/GridServiceContextInjectionSelfTest.java
- modules/spring/src/test/java/org/apache/ignite/testsuites/IgniteResourceSelfTestSuite.java
…ervices (wip).
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation …
> IGNITE-15801 Annotation-based injection of ServiceContext.

- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAbstractSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/GridRestProcessor.java
Fixes exception when PROBE command is called via REST:
`curl -v -k 'https://127.0.0.1:8080/ignite?cmd=probe&ignite.login=***&ignite.password=***'`
`java.lang.AssertionError: Unexpected command: PROBE
at org.apache.ignite.internal.processors.rest.GridRestProcessor.authorize(GridRestProcessor.java:968) ~[ignite-core-8.8.10.jar:8.8.10]
at org.apache.ignite.internal.processors.rest.GridRestProcessor.handleRequest(GridRestProcessor.java:286) ~[ignite-core-8.8.10.jar:8.8.10]
at org.apache.ignite.internal.processors.rest.GridRestProcessor.access$100(GridRestProcessor.java:108) ~[ignite-core-8.8.10.jar:8.8.10]
at org.apache.ignite.internal.processors.rest.GridRestProcessor$2.body(GridRestProcessor.java:183) ~[ignite-core-8.8.10.jar:8.8.10]
at …
> IGNITE-15868 Unexpected command: PROBE when authorization is enabled

- modules/core/src/main/java/org/apache/ignite/resources/ServiceContextResource.java
> IGNITE-15895 ServiceContextResource javadoc fix.

- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/ignitetest/utils/version.py
…and set it as LATEST
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbrev …
> IGNITE-15890: added ignite version 2.11.0 to Docker file and set it as LATEST

- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/stat/StatisticsAbstractTest.java
> IGNITE-15917 Increase timeout for test.

- docs/_docs/monitoring-metrics/new-metrics.adoc
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheMetricsImpl.java
> IGNITE-15591 Update description of initiator-updated cache metrics

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpIgniteClient.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/OptimizedMarshallerClassesCachedTest.java
- modules/indexing/src/test/java/org/apache/ignite/client/ClientTestSuite.java
> IGNITE-15924 Thin client cache for OptimizedMarshaller class names

- modules/core/src/main/java/org/apache/ignite/internal/processors/service/IgniteServiceProcessor.java
- modules/core/src/test/java/org/apache/ignite/ServiceAuthorizationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/service/ServiceAuthorizationTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
> IGNITE-15951 Fixes preconfigured service deployment authorization.

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/GridSubqueryJoinOptimizer.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/GridSubqueryJoinOptimizerSelfTest.java
> IGNITE-14354 Regression when using SELECT (EXISTS (...))

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotRestoreFromRemoteTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicWithPersistenceTestSuite.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteSnapshotTestSuite.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgnitePdsWithIndexingTestSuite.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteSnapshotWithIndexingTestSuite.java
> IGNITE-15233 Apply scale factor for loading snapshot partitions

- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/defragmentation/DefragIndexFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/defragmentation/IndexingDefragmentation.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/io/IORowHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsIndexingDefragmentationTest.java
https://issues.apache.org/jira/browse/IGNITE-15968 …
> IGNITE-15968 Index de-fragmentation fails on DECIMAL and VARCHAR columns

- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/defragmentation/DefragIndexFactory.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/defragmentation/IndexingDefragmentation.java
> IGNITE-15968 Fix checkstyle

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheAbstractMetricsSelfTest.java
> IGNITE-16002 The remove cache method should update statistics if the method returns true

- modules/core/src/main/java/org/apache/ignite/internal/processors/service/IgniteServiceProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/service/ServiceAuthorizationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/security/service/ServiceStaticConfigTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
> IGNITE-16019 Fix check of SERVICE_DEPLOY permission

- modules/core/src/main/java/org/apache/ignite/configuration/IgniteConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/pool/PoolProcessor.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotWithMetastorageTest.java
> IGNITE-16014 Add snapshot thread pool configuration

- docs/_docs/perf-and-troubleshooting/thread-pools-tuning.adoc
- docs/_docs/snapshots/snapshots.adoc
> IGNITE-16045 Add documentation pages for the snapshot thread pool size property

- modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/CacheGroupPageScanner.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/pool/PoolProcessor.java
…e pool processor.
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviat …
> IGNITE-16070 Move re-encryption executor into the pool processor.

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Services/ServicesClientTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/ComputeApiTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/PlatformComputeBinarizable.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/IJavaService.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/JavaServiceDynamicProxy.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/PlatformTestService.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtils.cs
> IGNITE-16076 .NET: Remove duplicate PlatformComputeBinarizable test class

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/IgnitePKIndexesMigrationToUnwrapPkTest.java
- modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
- modules/core/src/main/java/org/apache/ignite/configuration/SystemDataRegionConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/IgniteKernal.java
- modules/core/src/main/java/org/apache/ignite/internal/IgnitionEx.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/mvcc/MvccProcessorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformConfigurationUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/node/VisorDataStorageConfiguration.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/node/VisorMemoryConfiguration.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/OutOfMemoryVolatileRegionTest.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/full-config.xml
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationSerializerTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgnitionStartTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Configuration/DataStorageConfiguration.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Configuration/SystemDataRegionConfiguration.cs
- modules/platforms/dotnet/Apache.Ignite.Core/IgniteConfigurationSection.xsd
> IGNITE-15998 Add separate configuration for system data region

- modules/log4j2/src/main/java/org/apache/ignite/logger/log4j2/Log4J2Logger.java
- parent/pom.xml
> IGNITE-16101 update log4j to 2.15

- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineTreeFilterClosure.java
Fixes incorrect check of MVCC in InlineFilterClosure
> IGNITE-16123 Fix MVCC check in InlineFilterClosure

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryObjectImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryWriterExImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/binary/builder/BinaryBuilderSerializer.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryMarshallerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryObjectBuilderAdditionalSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/mutabletest/GridBinaryTestClasses.java
> Revert "IGNITE-15978 Support binary HANLDEs by BinaryObjectBuilder (#9590)"

- bin/ignite-cdc.sh
> IGNITE-14366 Support separate JVM options for ignite-cdc.sh and ignite.sh

- parent/pom.xml
> IGNITE-16127 update log4j

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcSelfTest.java
> IGNITE-15558 CDC support non default page size

- parent/pom.xml
> IGNITE-16153 Update log4j2 dependency up to 2.17.0

- docs/_docs/distributed-computing/collocated-computations.adoc
> IGNITE-16174 Bugyard feedback #45: Fix the job's name

- docs/_docs/includes/starting-node.adoc
> IGNITE-16172 Bugyard feedback #43: Fix typos in the tab's names

- docs/_docs/quick-start/java.adoc
> IGNITE-16173 Bugyard feedback #44: Fix broken link in docs

- RELEASE_NOTES.txt
> IGNITE-16145 Added RELEASE NOTES for the 2.11.1

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotVerificationTask.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotRestoreFromRemoteTest.java
> IGNITE-16177 Fix hanging of restore operation when not all "affinity" partitions are physically present in the snapshot.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotRestoreFromRemoteTest.java
> IGNITE-16194 Fix snapshot restore fails if metadata is missing on any blt node. 

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/AbstractClientCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/JavaThinCompatibilityTest.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientServicesImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ProtocolBitmaskFeature.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientBitmaskFeature.java
> IGNITE-16210 Fix GET_SERVICE_DESCRIPTORS enum value

- modules/rest-http/README.txt
- modules/rest-http/pom.xml
- modules/zookeeper/pom.xml
> IGNITE-13464: Removed lоg4j and slf4j dependencies from rest-http.

- RELEASE_NOTES.txt
> IGNITE-16021 Update Apache Ignite 2.12 release notes

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/DataRecord.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/RecoveryDebug.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIterator.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordDataV1Serializer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordDataV2Serializer.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsSporadicDataRecordsOnBackupTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/file/IgnitePdsCheckpointSimulationWithRealCpDisabledTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/reader/IgniteWalReaderTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxPartitionCounterStateConsistencyTest.java
- modules/dev-utils/src/main/java/org/apache/ignite/development/utils/IgniteWalConverter.java
- modules/dev-utils/src/main/java/org/apache/ignite/development/utils/WalStat.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/IgniteWalRecoveryTest.java
> IGNITE-16188 Eliminate intermediate list for DataRecord

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotRestoreTask.java
> IGNITE-15300 Fix hanging of zk ctl utility suite.

- parent/pom.xml
> IGNITE-16241 Updated log4j version to 2.17.1

- docs/_docs/clustering/baseline-topology.adoc
> IGNITE-16170 - Fixing broken links for feedback 38-41

- docs/_data/toc.yaml
- docs/_docs/persistence/snapshots.adoc
> IGNITE-16169 - added snapshots to latest to fix feedback 37

- docs/_docs/setup.adoc
> IGNITE-16171 Bugyard feedback #42: Fix typo in docs

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/util/MavenUtils.java
> IGNITE-15963 Improves Maven Utils to automatically reuse project repositories while downloading dependencies.

- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerNioListener.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> IGNITE-16249 Drop down log level from error to warn for some user operation failures

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheSqlQuery.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheTwoStepQuery.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/sql/GridSqlQuerySplitter.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/sql/SqlAstTraverser.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheJoinPartitionedAndReplicatedTest.java
> IGNITE-16261 Query with 'in' condition with a sub-query returns multiplicative data.

- modules/compatibility/pom.xml
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/util/MavenUtils.java
- parent/pom.xml
> IGNITE-16270 Refines Maven Utils to obtain repositories list through help:effective-pom plugin.

- docs/_docs/thin-clients/java-thin-client.adoc
> IGNITE-16017 Bugyard feedback #34: Fix typo in Java Thin Client section

- packaging/deb/changelog
- packaging/rpm/apache-ignite.spec
> IGNITE-16301 Update released 2.12.0 packages version

- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridReduceQueryExecutor.java
> IGNITE-16290 Avoid non-informative warning on query retry.

- docs/_data/toc.yaml
- docs/_docs/persistence/native-persistence.adoc
> IGNITE-14365 CDC Documentation: fixed broken links

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcSelfTest.java
> IGNITE-16248 Fixes CDC default page size initialization.

- modules/dev-utils/src/main/java/org/apache/ignite/development/utils/IgniteWalConverterArguments.java
- modules/dev-utils/src/test/java/org/apache/ignite/development/utils/IgniteWalConverterArgumentsTest.java
https://issues.apache.org/jira/browse/IGNITE-16324
> IGNITE-16324 wal-reader can't parse negative groupId/cacheId

- modules/ducktests/pom.xml
- modules/ml/pom.xml
- modules/ml/spark-model-parser/pom.xml
- modules/zookeeper/pom.xml
- parent/pom.xml
> IGNITE-16330 Update sfl4j version

- modules/core/src/main/java/org/apache/ignite/internal/GridJobResultImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/GridTaskSessionImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/job/ComputeJobStatusEnum.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/job/GridJobProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/job/GridJobWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/session/GridTaskSessionProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/GridTaskEventListener.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/GridTaskProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/GridTaskWorker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/monitor/ComputeGridMonitor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/monitor/ComputeTaskStatus.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/monitor/ComputeTaskStatusEnum.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/task/monitor/ComputeTaskStatusSnapshot.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/compute/ComputeGridMonitorTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/compute/ComputeJobStatusTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/common/GridCommonAbstractTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteComputeGridTestSuite.java
https://issues.apache.org/jira/browse/IGNITE-16325
> IGNITE-16325 Add compute task monitoring to keep track of their current status

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
> IGNITE-16150 Fix redundant file copy when restoring.

- modules/mesos/pom.xml
- modules/mesos/src/test/java/org/apache/ignite/mesos/IgniteSchedulerSelfTest.java
> IGNITE-16352 Update Ignite dependency Mesos

- modules/core/src/main/java/org/apache/ignite/cdc/CdcLoader.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/client/router/impl/GridRouterCommandLineStartup.java
- modules/core/src/main/java/org/apache/ignite/internal/util/spring/IgniteSpringHelper.java
- modules/core/src/main/java/org/apache/ignite/startup/cmdline/CdcCommandLineStartup.java
- modules/spring/src/main/java/org/apache/ignite/internal/util/spring/IgniteSpringHelperImpl.java
> IGNITE-16360 Fix CdcLoader instantiates several Spring contexts

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/IgniteReleasedVersion.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/AbstractClientCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/IndexTypesCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/InlineJavaObjectCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/persistence/PersistenceBasicCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/util/CompatibilityTestsUtils.java
- modules/core/src/test/java/org/apache/ignite/testframework/GridTestUtils.java
> IGNITE-16394 Provide enum of released versions to compatibility tests

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_cache_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_cache_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output
> IGNITE-16402 Fixed year check in the GridCommandHandler* tests

- modules/core/src/main/java/org/apache/ignite/internal/processors/query/property/QueryBinaryProperty.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/H2DynamicTableSelfTest.java
> IGNITE-16421 : Wrap_key doesn't work with custom value_type

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FileWriteHandleImpl.java
> IGNITE-16436 Fix node can crash with ClosedChannelException

- docs/_docs/tools/control-script.adoc
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/consistency/ConsistencyCommand.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/KillCommandsCommandShTest.java
- modules/ducktests/tests/ignitetest/tests/control_utility/consistency_test.py
> IGNITE-16225 Read Repair control.sh command should have named params

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerIndexingTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PageMemoryImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsRecoveryAfterFileCorruptionTest.java
> IGNITE-16264 tryToRestorePage does not mark the page as dirty.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheManyAsyncOperationsTest.java
https://issues.apache.org/jira/browse/IGNITE-16405 …
> IGNITE-16405 Fix NoClassDefFound on invokeAsync with using BinaryObjects.

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/CheckpointMarkersStorage.java
- modules/core/src/test/java/org/apache/ignite/startup/cmdline/CommandLinePrintPropertiesTest.java
> IGNITE-16437 Fix CommandLinePrintPropertiesTest#testPrintProperties

- modules/ducktests/tests/ignitetest/tests/control_utility/consistency_test.py
> IGNITE-16508 Travis check should be duplicated at TC

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/database/BPlusTreeSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-16518
> IGNITE-16518 BPlusTreeReuseListPageMemoryImplTest.testMassiveRemove2_true flaky

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/cdc/RestartWithWalForceArchiveTimeoutTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite2.java
> IGNITE-16523 Rollover by timeout fixed

- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
> IGNITE-16537 Fix ducktests failure because of the changes in output format of control.sh

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/cache/QueryEntity.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryTypeDescriptor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryEntityEx.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryTypeDescriptorImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryUtils.java
- modules/geospatial/src/test/java/org/apache/ignite/internal/processors/query/h2/H2IndexingAbstractGeoSelfTest.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/CommandProcessor.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/QueryParser.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/dml/UpdatePlan.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/dml/UpdatePlanBuilder.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2RowDescriptor.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/IgniteInsertNullableDuplicatesSqlTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteCacheQuerySelfTestSuite6.java
> IGNITE-16494 Query engine allows to insert rows with logically equal compound PK

- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py
1. Use more specific regexp to get the correct MBean.
2. Change to use the "extended regular expressions" grep mode, since otherwise (in basic mode) the '+' meta-character
should be used with backslash.  In that case the python style checker complains.
***
the `green visa` attached to the JIRA ticket (see …
> IGNITE-16540 [ducktests] Fix test failure because of mix of snapshot and snapshot system view mbeans

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/LogicalRelImplementor.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/RuntimeHashIndex.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/rel/IndexSpoolNode.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rel/IgniteHashIndexSpool.java
- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rule/FilterSpoolMergeToHashIndexSpoolRule.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/exec/rel/HashIndexSpoolExecutionTest.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/HashSpoolIntegrationTest.java
> IGNITE-14916 Calcite. RuntimeHashIndex scan must filter result by predicate

- modules/zookeeper/pom.xml
- parent/pom.xml
> IGNITE-15673 Update Ignite dependency zookeeper

- parent/pom.xml
> IGNITE-16385 Update Ignite dependency JNR POSIX

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteSpeedBasedThrottle.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteThrottle.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteThrottlePolicy.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/IgniteThrottlingUnitTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PageMemoryImplTest.java
https://issues.apache.org/jira/browse/IGNITE-16600 …
> IGNITE-16600 Implement tryWakeupThrottledThreads and shouldThrottle for speed based throttle

- docs/_docs/SQL/indexes.adoc
> IGNITE-14310 Update CREATE TABLE, Schema, and Indexing sections

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheMapEntry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxRemoteAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/colocated/GridDhtDetachedCacheEntry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearCacheEntry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/version/GridCacheVersionEx.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcCacheVersionTest.java
> IGNITE-16587 Fix putAllConflict, removeAllConflict for tx caches

- docs/_docs/snapshots/snapshots.adoc
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotCancelCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotCheckCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotCreateCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotCreateCommandOption.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotRestoreCommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotRestoreCommandOption.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotSubcommand.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/snapshot/SnapshotSubcommands.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotCancelTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotCheckTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotCreateTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotCreateTaskArg.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotOneNodeTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotRestoreTask.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotRestoreTaskAction.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotRestoreTaskArg.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotTaskResult.java
- modules/core/src/main/resources/META-INF/classnames.properties
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output
> IGNITE-15450 Add special option to run snapshot commands synchronously.

- modules/platforms/cpp/odbc-test/src/api_robustness_test.cpp
- modules/platforms/cpp/odbc/CMakeLists.txt
> IGNITE-13771 ODBC: Add linking to odbcinst on linux

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/SpeedBasedThrottleBreakdownTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite.java
https://issues.apache.org/jira/browse/IGNITE-16623
In IGNITE-16581, a speed-based throttling breakage bug was fixed, but we only covered the fix with local JUnit tests. Here, we add an integration test to rest assured. …
> IGNITE-16623 Cover speed-based throttling breakdown fix with integration test

- bin/control.bat
- bin/control.sh
- bin/ignite.bat
- bin/ignite.sh
- bin/ignitevisorcmd.bat
- bin/ignitevisorcmd.sh
- bin/include/jvmdefaults.bat
- bin/include/jvmdefaults.sh
- bin/index-reader.bat
- bin/index-reader.sh
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FileWriteHandleImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/util/FeatureChecker.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/TcpHandshakeExecutor.java
- modules/spark-2.4/src/main/scala/org/apache/ignite/spark/IgniteRDD.scala
- modules/spark-2.4/src/main/scala/org/apache/ignite/spark/impl/IgniteSqlRDD.scala
- modules/sqlline/bin/sqlline.bat
- modules/sqlline/bin/sqlline.sh
- modules/tools/pom.xml
- modules/tools/src/main/java15/org/apache/ignite/tools/javadoc/IgniteLinkTaglet.java
- modules/web/ignite-websphere-test/pom.xml
- parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-16622
WHAT:
- Added new maven profile that allows running tests with Java 17 (--add-opens and all that). This maven profile is also used for source folder with `IgniteLinkTaglet` (the same way as with java 11 profile)
- Fixed fsync for mmap'ped byte buffers, because original one uses internal fields and APIs that were changed in JDK 15. Now there are two fsync mechanisms, one for *older* java and one for java >= 15.
- Rewritten shell and batch scripts to eliminate copy-pasted JVM_OPTS, now they all are in one place, jvmdefaults.(sh|bat)
- Fixed an issue with TLS v1.3: there was a buffer underflow in the client's handshake process
In order to streamline the review of the …
> IGNITE-16622 Add support for JDK17

- parent/pom.xml
> IGNITE-16602 Update Ignite dependency: PostgreSQL JDBC to 42.3.3

- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/DurableBackgroundCleanupIndexTreeTaskV2.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexTree.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/maintenance/MaintenanceRebuildIndexTarget.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/maintenance/MaintenanceRebuildIndexUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/maintenance/MaintenanceProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/LightweightCheckpointManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/aware/IndexBuildStatusStorage.java
- modules/core/src/main/java/org/apache/ignite/maintenance/MaintenanceRegistry.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/MaintenanceRegistrySimpleTest.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/SchemaManager.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/database/H2TreeIndex.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/maintenance/RebuildIndexAction.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/maintenance/RebuildIndexWorkflowCallback.java
- modules/indexing/src/main/java/org/apache/ignite/internal/visor/verify/ValidateIndexesClosure.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/IndexCorruptionRebuildTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/RenameIndexTreeTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsIndexingDefragmentationTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/maintenance/MaintenanceRebuildIndexUtilsSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteCacheWithIndexingTestSuite.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgnitePdsWithIndexingTestSuite.java
https://issues.apache.org/jira/browse/IGNITE-16661 …
> IGNITE-16661 Maintenance task to rebuild corrupted indexes

- modules/core/src/main/java/org/apache/ignite/internal/GridEventConsumeHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/GridDeploymentClassLoader.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/P2PClassLoadingIssues.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/P2PClassNotFoundException.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/CacheContinuousQueryHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/datastreamer/DataStreamerUpdateJob.java
- modules/core/src/test/java/org/apache/ignite/internal/managers/deployment/P2PClassLoadingIssuesTest.java
- modules/core/src/test/java/org/apache/ignite/p2p/P2PClassLoadingFailureHandlingTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteP2PSelfTestSuite.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/CacheEntryProcessorCausingP2PClassLoadProblem.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/ComputeTaskCausingP2PClassLoadProblem.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/P2PClassLoadingProblems.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/RemoteEventFilterCausingP2PClassLoadProblem.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/RemoteFilterFactoryCausingP2PClassLoadProblem.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/RemoteMessagingListenerCausingP2PClassLoadProblem.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/RemoteTransformerFactoryCausingP2PClassLoadProblem.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/ServiceCausingP2PClassLoadProblem.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/SomeP2PClass.java
- modules/extdata/p2p/src/main/java/org/apache/ignite/tests/p2p/classloadproblem/StreamReceiverCausingP2PClassLoadProblem.java
https://issues.apache.org/jira/browse/IGNITE-16640 …
> IGNITE-16640 Peer class loading failure should not be treated as a critical node failure

- docs/_data/toc.yaml
- docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc
- docs/_docs/persistence/change-data-capture.adoc
> IGNITE-16246 Fix CDC extension documentation links and titles.

- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcConsumerState.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
- modules/core/src/main/java/org/apache/ignite/internal/cdc/WalRecordsConsumer.java
- modules/core/src/test/java/org/apache/ignite/cdc/AbstractCdcTest.java
- modules/core/src/test/java/org/apache/ignite/cdc/CdcSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIteratorTest.java
> IGNITE-14829 Save DataEntry index inside CDC state

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/main/java/org/apache/ignite/internal/util/io/GridFileUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/util/io/GridFileUtilsTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite2.java
> IGNITE-16541 Added CDC hard links check on startup

- .gitignore
- modules/ducktests/tests/docker/run_tests.sh
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/event_type.py
- modules/ducktests/tests/ignitetest/services/utils/ssl/client_connector_configuration.py
- modules/ducktests/tests/ignitetest/services/utils/templates/ignite.xml.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/misc_macro.j2
- modules/ducktests/tests/ignitetest/services/zk/zookeeper.py
- modules/ducktests/tests/ignitetest/tests/cellular_affinity_test.py
- modules/ducktests/tests/ignitetest/tests/control_utility/consistency_test.py
- modules/ducktests/tests/ignitetest/tests/discovery_test.py
- modules/ducktests/tests/ignitetest/tests/persistence_upgrade_test.py
- modules/ducktests/tests/ignitetest/tests/pme_free_switch_test.py
- modules/ducktests/tests/ignitetest/tests/rebalance/util.py
- modules/ducktests/tests/ignitetest/tests/snapshot_test.py
- modules/ducktests/tests/ignitetest/utils/_mark.py
- modules/ducktests/tests/ignitetest/utils/ignite_test.py
Added ability to add extra procedures to be invoked _before_ and _after_ each ducktest transparently via the globals parameters in a way similar to customization of specs for ignite nodes.  It should be possible to invoke of extra ducktape services in these procedures on the same testing cluster.  
In this PR some modifications were also done to let tests run smoothly in presence of the customization:
* The **persistence_upgrade_test.py::PersistenceUpgradeTest** fails if SSL is enabled via the --globals options. The immediate reason is that control.sh doesn't support the SSL options (like key_store_path) in the 2.7.6 version which is the starting point for the test incremental migrations of the PDS. Solution is to ignore test if SSL is enabled.
* The framework was modified to let …
> IGNITE-16569  [ducktests] Add ability to customize the test context for ducktest

- modules/core/src/main/java/org/apache/ignite/internal/processors/pool/MetricsAwareExecutorService.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/pool/PoolProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/util/StripedExecutor.java
- modules/core/src/main/java/org/apache/ignite/thread/IgniteStripedThreadPoolExecutor.java
- modules/core/src/main/java/org/apache/ignite/thread/IgniteThreadPoolExecutor.java
- modules/core/src/test/java/org/apache/ignite/thread/ThreadPoolMetricsTest.java
> IGNITE-16698 Fix metrics for IgniteStripedThreadPoolExecutor.

- bin/include/jvmdefaults.bat
- modules/sqlline/bin/sqlline.bat
https://issues.apache.org/jira/browse/IGNITE-16708 …
> IGNITE-16708 Fix sqlline.bat windows shell scripts

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/JavaThinCompatibilityTest.java
…er(Version 2.4.0)
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviat …
> IGNITE-16720 Fix JavaThinCompatibilityTest.testCurrentClientToOldServer

- parent/pom.xml
> IGNITE-16673 Update Ignite dependency zookeeper

- parent/pom.xml
> IGNITE-16682 update dependency netty

- docs/_docs/monitoring-metrics/new-metrics.adoc
- modules/core/src/main/java/org/apache/ignite/internal/processors/metric/impl/HistogramMetricImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/pool/PoolProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridMutableLong.java
- modules/core/src/main/java/org/apache/ignite/internal/util/StripedExecutor.java
- modules/core/src/main/java/org/apache/ignite/thread/IgniteStripedThreadPoolExecutor.java
- modules/core/src/main/java/org/apache/ignite/thread/IgniteThreadPoolExecutor.java
- modules/core/src/test/java/org/apache/ignite/thread/ThreadPoolMetricsTest.java
> IGNITE-16648 Add task execution metrics to thread pools.

- modules/core/src/test/java/org/apache/ignite/internal/MarshallerContextLockingSelfTest.java
> IGNITE-16764 Fix MarshallerContextLockingSelfTest.testMultithreadedUpdate

- modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessor.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/RunningQueriesIntegrationTest.java
- modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/jdbc/JdbcQueryTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/NoOpQueryEngine.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryEngine.java
- modules/platforms/cpp/CMakeLists.txt
- modules/platforms/cpp/core-test/src/test_utils.cpp
- modules/platforms/cpp/odbc-test/src/cross_engine_test.cpp
- modules/platforms/cpp/odbc-test/src/test_utils.cpp
- modules/platforms/cpp/thin-client-test/src/test_utils.cpp
> IGNITE-16740 SQL Calcite: Implement batches in JDBC and ODBC

- modules/checkstyle/pom.xml
> IGNITE-16812 Change the relative directory for checkstyle resources

- .github/workflows/publish-snapshot.yml
> IGNITE-16775 Add GitHub Actions to deploy snapshot to the maven repository

- modules/ducktests/README.md
- modules/ducktests/pom.xml
- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/docker/clean_up.sh
- modules/ducktests/tests/docker/ducker-ignite
- modules/ducktests/tests/docker/run_tests.sh
- modules/ducktests/tests/ignitetest/services/utils/control_utility.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/data_storage.py
- modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
- modules/ducktests/tests/ignitetest/services/utils/jmx_remote/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/jmx_remote/jmx_remote_params.py
- modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py
- modules/ducktests/tests/ignitetest/services/utils/metrics/__init__.py
- modules/ducktests/tests/ignitetest/services/utils/metrics/metrics.py
- modules/ducktests/tests/ignitetest/services/utils/templates/cache_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/datastorage_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/ignite.xml.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/misc_macro.j2
- modules/ducktests/tests/ignitetest/services/utils/templates/opencensus_metrics_beans_macro.j2
- modules/ducktests/tests/ignitetest/tests/rebalance/util.py
- modules/ducktests/tests/ignitetest/tests/snapshot_test.py
- modules/ducktests/tests/ignitetest/utils/bean.py
Added new global parameters to enable metrics exporters in Ignite nodes started in scope of ducktests.
Both JMX and HTTP Prometheus metrics are supported.
See more details in the Jira ticket and in the README.md in this patch
**** …
> IGNITE-16804 [ducktests] Add ability to export metrics

- RELEASE_NOTES.txt
> IGNITE-16818 Update Apache Ignite 2.13 release notes

- .github/workflows/publish-snapshot.yml
> IGNITE-16837 Prevent triggering GitHub Action on Apache Ignite forks

- modules/indexing/src/test/java/org/apache/ignite/internal/metric/SqlStatisticsUserQueriesFastTest.java
> IGNITE-16839 Fix SqlStatisticsUserQueriesFastTest.testLocalSelectFailed

- modules/spark/src/test/scala/org/apache/ignite/spark/IgniteOptimizationAggregationFuncSpec.scala
> IGNITE-16844 Fix IgniteOptimizationAggregationFuncSpec

- docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/ConfiguringMetrics.java
- docs/_docs/code-snippets/xml/metrics.xml
- docs/_docs/monitoring-metrics/new-metrics-system.adoc
> IGNITE-15712: Documentation: Invalid documentation about SqlViewMetricExporterSpi

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/junits/Dependency.java
> IGNITE-16852 Fix classloading for compatibility tests

- examples/pom.xml
- modules/rest-http/pom.xml
- parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-16781 …
> IGNITE-16781 Upgrade org.springframework:spring-core for CVE-2022-22965 (a.k.a. Spring4Shell)

- modules/core/src/main/java/org/apache/ignite/internal/util/GridJavaProcess.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/TcpCommunicationSpiFreezingClientTest.java
> IGNITE-16838 Fix TcpCommunicationSpiFreezingClientTest#testFreezingClient

- DEVNOTES.txt
> IGNITE-16876 Add instruction for building release with NUMA allocator

- .github/workflows/publish-snapshot.yml
> IGNITE-16880 Add compatibility module for publishing snapshot version

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/IgniteWalHistoryReservationsTest.java
…artiallyRemoved for compression suite …
> IGNITE-16891 Disable testWalHistoryPartiallyRemoved for compression suite

- modules/calcite/pom.xml
> IGNITE-16917 Fix deploy configuration for the ignite-calcite module

- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheDataRegionConfigurationTest.java
> IGNITE-16910 Reduce the memory usage of CacheDataRegionConfigurationTest.

- .github/workflows/publish-website-on-branch-update.yml
> IGNITE-16895 Update documentation with GitHub Actions

- docs/_data/toc.yaml
- docs/_docs/clustering/tcp-ip-discovery.adoc
- docs/_docs/extensions-and-integrations/zookeeper-ip-finder-ext.adoc
> IGNITE-16239 Document the zookeeper-ip-finder-ext extension.

- docs/_docs/setup.adoc
> IGNITE-16239 Documentation: added the zookeeper-ip-finder-ext extension to the setup page.

- modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryWriterExImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryMarshallerSelfTest.java
> IGNITE-16318 Fix write/read/modify empty binary object

- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinInsertStatementSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/jdbc/JdbcRequestHandler.java
> IGNITE-17001 Don't print error on user input into node log

- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientOperation.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpIgniteClient.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/datastructures/ClientAtomicLongRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/datastructures/ClientAtomicLongValueCompareAndSetAndGetRequest.java
- modules/core/src/test/java/org/apache/ignite/platform/PlatformGetInternalCachesTask.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/PartitionAwarenessTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/DataStructures/AtomicLongClientTests.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Client/DataStructures/AtomicClientConfiguration.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Client/DataStructures/IAtomicLongClient.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Client/IIgniteClient.cs
- modules/platforms/dotnet/Apache.Ignite.Core/IIgnite.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientOp.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/DataStructures/AtomicLongClient.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/IgniteClient.cs
- modules/platforms/dotnet/Apache.Ignite.DotNetCore.sln.DotSettings
* Add `IIgniteClient.GetAtomicLong` and `IAtomicLongClient` APIs.
* Use partition-aware requests.
> IGNITE-16946 .NET: Thin client: Add AtomicLong

- parent/pom.xml
> IGNITE-16888 update lz4

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/IgniteReleasedVersion.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/JavaThinCompatibilityTest.java
> IGNITE-17026 Add the 2.13 version to compatibility tests

- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexKeyType.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexTree.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/types/NullableInlineIndexKeyType.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/index/client/ClientIndexFactory.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryInlineSizesTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/SqlSystemViewsSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/database/inlinecolumn/ComputeInlineSizeTest.java
> IGNITE-17025 Adjust inline size for fixed size index items

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
> IGNITE-17035 Fixed flaky testChangeSnapshotTransferRateInRuntime test.

- modules/bom/pom.xml
- modules/compatibility/pom.xml
> IGNITE-17037 Add compatibility jars to the release lyfecycle

- modules/core/src/main/java/org/apache/ignite/internal/marshaller/optimized/OptimizedObjectOutputStream.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridHandleTable.java
- modules/core/src/test/java/org/apache/ignite/internal/util/GridHandleTableSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-17043
WHAT:
Automatically shrink the size of GridHandleTable on `clear` by the factor of two. Shrink only in case if element count is less than table size / 2, so we don't actually shrink table if we have a lot of big lists, for example.
WHY:
GridHandleTable grows during marshalling and never shrinks. Which leads to very long clear operations if, for example, we marshal a very big list and after that we marshal a very small list. In this case GridHandleTable will grow to the size of the very big list and subsequent clear operations will take a long time on every small list.
we ask you to ensure the following steps have been …
> IGNITE-17043 Shrink GridHandleTable on clear

- modules/compatibility/pom.xml
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/junits/Dependency.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/testframework/junits/IgniteCompatibilityAbstractTest.java
- modules/compatibility/src/test/resources/compatibility.properties
…dedicated JVM with incorrect classpath …
> IGNITE-17079 Fix compatibility framework when a node is started in a dedicated JVM with incorrect classpath

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/CheckpointProgressImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteSpeedBasedThrottle.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/SpeedBasedMemoryConsumptionThrottlingStrategy.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/AbstractSlowCheckpointFileIOFactory.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/CheckpointBufferDeadlockTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/SlowCheckpointMetadataFileIOFactory.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/SlowCheckpointPagesFileIOFactory.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/IgniteThrottlingUnitTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteThrottleSandboxTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PagesWriteThrottleSmokeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/SpeedBasedThrottleIntegrationTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/performancestatistics/CheckpointTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite5.java
Speed-based throttle contained 2 algorithms (it took max of the values they were returning):
* Simpler that throttled when current marking speed was higher than average CP speed
* More complex one that first computed max acceptable marking speed (taking into account clean pages ratio and average CP speed) and then throttled if current marking speed was higher than the acceptable speed AND the current dirty ratio was higher than the acceptable dirty ratio
There was a bug that prevented the second algorithm from ever kicking in.
The first one did not take into account the clean pages that we still had, so it throttled bursts even in situations when the buffering power of the clean pages was still enough to smooth the bursts. Also, the second algorithm seems to be more general than the first …
> IGNITE-16582 Improve behavior of speed-based throttling when dirty pages ratio is low

- parent/pom.xml
> IGNITE-17095 Update Ignite dependencies for the apache commons libraries

- modules/calcite/pom.xml
> IGNITE-17096 update jsonpath dependency

- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/DiscoveryClientSocketTest.java
Co-authored-by: Vladislav Pyatkov <vldpyatkov@gmail.com>
> IGNITE-17119 DiscoveryClientSocketTest.sslSocketTest fails regularly on TC and locally

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterPerMethodAbstractTest.java
- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/PartitionUpdateCounter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/PartitionUpdateCounterDebugWrapper.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/PartitionUpdateCounterErrorWrapper.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/PartitionUpdateCounterTrackingImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/PartitionUpdateCounterVolatileImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/IdleVerifyResultV2.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/IdleVerifyUtility.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/PartitionHashRecordV2.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/VerifyBackupPartitionsTaskV2.java
> IGNITE-17114 Idle_verify must print and compare full partition counter state instead of just LWM

- modules/platforms/cpp/thin-client-test/src/sql_fields_query_test.cpp
- modules/platforms/cpp/thin-client/CMakeLists.txt
- modules/platforms/cpp/thin-client/include/ignite/thin/cache/query/query_sql_fields.h
- modules/platforms/cpp/thin-client/src/impl/data_channel.cpp
- modules/platforms/cpp/thin-client/src/impl/data_channel.h
- modules/platforms/cpp/thin-client/src/impl/message.cpp
- modules/platforms/cpp/thin-client/src/impl/message.h
- modules/platforms/cpp/thin-client/src/impl/protocol_context.cpp
- modules/platforms/cpp/thin-client/src/impl/protocol_context.h
- modules/platforms/cpp/thin-client/src/impl/protocol_version.h
> IGNITE-16873 C++ Thin SqlFieldsQuery setting partitions

- parent/pom.xml
> IGNITE-17136 Update Ignite dependency: Tomcat Servlet API to 9.0.63

- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinStatementSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/jdbc/thin/JdbcThinConnection.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/SqlStateCode.java
> IGNITE-17145 Fix handle BinaryObjectException at the thin JDBC

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxRemoteAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxPrepareFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxRemote.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxEntry.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxRemoteEx.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxPartitionCounterStateConsistencyNoopInvokeTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite9.java
> IGNITE-17123: Fix update counter assignment on backup nodes.

- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/ClientExceptionsUtils.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/TcpCommunicationSpi.java
- modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/CommunicationWorker.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/ClientExceptionsUtilsTest.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/CommunicationWorkerThreadUtils.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/GridTcpCommunicationInverseConnectionEstablishingTest.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/TcpCommunicationSpiInverseConnectionLoggingTest.java
- modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/TcpCommunicationSpiNodeLeftLoggingTest.java
- modules/core/src/test/java/org/apache/ignite/testframework/MemorizingAppender.java
- modules/core/src/test/java/org/apache/ignite/testframework/MemorizingAppenderTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite2.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteSpiCommunicationSelfTestSuite.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
https://issues.apache.org/jira/browse/IGNITE-17152
> IGNITE-17152 Improve logging levels for situations when dealing with a client node

- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/argument/parser/CLIArgument.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/argument/parser/CLIArgumentParser.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/IgniteIndexReader.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/PageListsInfo.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/TreeTraversalInfo.java
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/TreeTraverseContext.java
- modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/indexreader/IgniteIndexReaderTest.java
- modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/IndexProcessor.java
> IGNITE-17160 Minor index-reader code improvements

- modules/core/src/main/java/org/apache/ignite/internal/managers/eventstorage/GridEventStorageManager.java
- modules/core/src/test/java/org/apache/ignite/internal/managers/events/LifecycleAwareListenerTest.java
> IGNITE-17178 Fixes  preconfigured event listeners start notification before resources were injected.

- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs
- modules/platforms/dotnet/Apache.Ignite.Core/Impl/Services/ServiceContext.cs
…hreadLocal.
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Ru …
> IGNITE-17204 .NET: Store service call context in AsyncLocal (not ThreadLocal)

- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
https://issues.apache.org/jira/browse/IGNITE-17159 …
> IGNITE-17159 Fix race condition in GridNioServer

- modules/core/src/main/java/org/apache/ignite/resources/SpringResource.java
- modules/spring/src/main/java/org/apache/ignite/internal/processors/resource/GridResourceSpringBeanInjector.java
- modules/spring/src/test/java/org/apache/ignite/internal/processors/resource/GridSpringResourceInjectionSelfTest.java
- modules/spring/src/test/java/org/apache/ignite/internal/processors/resource/spring-resource.xml
> IGNITE-17218 Adds support of optional beans for SpringResource annotation injection.

- docs/_docs/installation/kubernetes/generic-configuration.adoc
- docs/_docs/thin-clients/java-thin-client.adoc
> IGNITE-17270 Fix issues with Kubernetes docs

- docs/_docs/thin-client-comparison.csv
> IGNITE-17284 Fix supported thin client features list on documentation

- modules/core/src/main/java/org/apache/ignite/IgniteLogger.java
- modules/core/src/main/java/org/apache/ignite/spi/collision/jobstealing/JobStealingCollisionSpi.java
> IGNITE-17288 Fix broken links in Javadocs

- docs/_docs/monitoring-metrics/system-views.adoc
- modules/clients/src/test/java/org/apache/ignite/jdbc/thin/JdbcThinMetadataSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/managers/systemview/walker/SqlQueryViewWalker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridRunningQueryInfo.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/query/RunningQueryManager.java
- modules/core/src/main/java/org/apache/ignite/spi/systemview/view/SqlQueryView.java
- modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/SqlSystemViewsSelfTest.java
- modules/indexing/src/test/java/org/apache/ignite/internal/systemview/SystemViewSecurityTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteStatisticsTestSuite.java
> IGNITE-17277 Added a user info to the sql queries view

- modules/core/src/main/java/org/apache/ignite/internal/processors/service/IgniteServiceProcessor.java
> IGNITE-17274 Improve service name lookup performance

- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAbstractSelfTest.java
- modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAuthenticationWithTokenSelfTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/rest/GridRestProcessor.java
> IGNITE-17234 skip authentication for Probe and Version commands

- parent/pom.xml
> IGNITE-17323 update Jetty dependency

- parent/pom.xml
> IGNITE-17326 update Spring

- modules/platforms/cpp/DEVNOTES.txt
- modules/platforms/cpp/examples/README.txt
Improved instructions for building Ignite C++ examples. …
> IGNITE-17388 Clarifications for examples/README.txt

- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridLuceneDirectory.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridLuceneFile.java
- modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridLuceneOutputStream.java
- parent/pom.xml
> IGNITE-16337 Update lucene version to 8.11.2

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxAsyncOpsSemaphorePermitsExceededTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite13.java
> IGNITE-17385 Skip acquire asyncOp permit for sync singleCache ops

- modules/core/src/main/java/org/apache/ignite/IgniteSystemProperties.java
- modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
- modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-17414 …
> IGNITE-17414 Fix node is trying to resolve its hostname if IP is configured with IGNITE_LOCAL_HOST

- modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/TcpDiscoveryNode.java
- modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryDeadNodeAddressResolvingTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteSpiDiscoverySelfTestSuite.java
- modules/web/src/test/java/org/apache/ignite/internal/websession/WebSessionSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-17415 …
> IGNITE-17415 Fix node resolves obsolete addresses from the previously restarted and killed nodes

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordV2Serializer.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotWalRecordTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
- modules/core/src/test/java/org/apache/ignite/testsuites/IgniteSnapshotTestSuite.java
Ensure that buffer has enough remaining bytes for extracting plain record for encrypted records.
> IGNITE-17408 Ensure buffer before read plain record type

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyRepairCorrectnessTransactionalTest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/AbstractFullSetReadRepairTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/AbstractReadRepairTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/consistency/ReadRepairDataGenerator.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/JUnitAssertAware.java
- modules/core/src/test/java/org/apache/ignite/testframework/junits/common/GridCommonAbstractTest.java
> IGNITE-15837 Read Repair should support binary keys

- parent/pom.xml
> IGNITE-17427 Update netty version up to 4.1.79.Final

- modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/CacheGroupPageScanner.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/util/BasicRateLimiter.java
- modules/core/src/test/java/org/apache/ignite/internal/util/BasicRateLimiterTest.java
> IGNITE-17407 Improved rate limiter accuracy.

- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/AbstractClientCompatibilityTest.java
- modules/compatibility/src/test/java/org/apache/ignite/compatibility/clients/JavaThinCompatibilityTest.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientOperation.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ProtocolBitmaskFeature.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientBitmaskFeature.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCachePutAllConflictRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheRemoveAllConflictRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/streamer/ClientDataStreamerReader.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformUtils.java
- modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
- modules/core/src/test/java/org/apache/ignite/internal/client/thin/DataReplicationOperationsTest.java
- modules/indexing/src/test/java/org/apache/ignite/client/ClientTestSuite.java
> IGNITE-15000 Implement data replication thin client operations

- modules/core/src/test/java/org/apache/ignite/testframework/ListeningTestLogger.java
> IGNITE-17463 Fix assertion error in test log messages

- modules/core/src/main/java/org/apache/ignite/cache/query/IndexQuery.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheDistributedQueryFuture.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryAdapter.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryManager.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryPartitionTest.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryTestSuite.java
> IGNITE-17455 Add setPartition() for IndexQuery

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotFilesRequestMessage.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotResponseRemoteFutureTask.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotRemoteRequestTest.java
> IGNITE-17502 Tasks to sent the snapshot files are not ordered

- modules/core/src/main/java/org/apache/ignite/client/ClientOperationType.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientOperation.java
- modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientCache.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheIndexQueryRequest.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheQueryIndexRequest.java
- modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryTestSuite.java
- modules/indexing/src/test/java/org/apache/ignite/cache/query/ThinClientIndexQueryTest.java
> IGNITE-17511 Java ThinClient supports IndexQuery

- modules/core/src/main/java/org/apache/ignite/internal/processors/service/IgniteServiceProcessor.java
…e list lookup with map lookup. …
> IGNITE-17524 Improve lookup of deployed services UUID by name: replace list lookup with map lookup

- modules/tools/pom.xml
- modules/tools/src/main/java/org/apache/ignite/tools/ant/beautifier/GridJavadocAntTask.java
> IGNITE-17565 Update Ignite dependency: jodd-lagarto

- docs/_docs/SQL/indexes.adoc
> IGNITE-17570 Extend documentation about defining of indices

- bin/ignitevisorcmd.bat
- bin/ignitevisorcmd.sh
> IGNITE-17432 ignitevisorcmd can't run in jdk17 env

- modules/core/src/main/java/org/apache/ignite/internal/managers/deployment/GridDeploymentStoreAdapter.java
https://issues.apache.org/jira/browse/IGNITE-17481 …
> IGNITE-17481 Fixed a workaround for Metaspace leak that stopped working for Java 11.0.16+ and 17.0.4+

- modules/ducktests/tests/docker/Dockerfile
- modules/ducktests/tests/ignitetest/utils/version.py
Move the latest released version of Ignite used in ducktests to the most recent 2.13.0.
----
- [Coding …
> IGNITE-17168 [ducktests] Bump the latest version to 2.13.0

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
> IGNITE-17552 Fix error propagation to the non-coordinator nodes.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataStorageMetricsImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/Checkpointer.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/file/FilePageStoreManager.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteDataStorageMetricsSelfTest.java
> IGNITE-17587 Fixed the "io.datastorage.StorageSize" metric in case of multiple persistence dataregions

- docs/_docs/tools/control-script.adoc
> IGNITE-17522 Add documentation for schedule_index_rebuild

- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/service/ClientServiceInvokeRequest.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientConnectionTest.cs
> IGNITE-17499 Fixes propagation of service call exception stacktrace to the client side

- docs/_docs/tools/control-script.adoc
- modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/cache/CacheIndexesForceRebuild.java
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_cache_help.output
- modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_cache_help.output
> IGNITE-17600 Fix documentation of control.sh indexes_force_rebuild task

- docs/_docs/code-snippets/k8s/stateful/node-configuration.xml
- docs/_docs/code-snippets/k8s/stateless/node-configuration.xml
> IGNITE-15862 fix node k8s config.xml

- modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
- modules/core/src/main/java/org/apache/ignite/internal/visor/snapshot/VisorSnapshotStatusTask.java
> IGNITE-17617 Fixed NPE in the snapshot restore status command on client nodes and non-persistent cluster.

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/io/BPlusIO.java
https://issues.apache.org/jira/browse/IGNITE-17631 …
> IGNITE-17631 Improve B+Tree implementation documentation

- packaging/deb/changelog
- packaging/rpm/apache-ignite.spec
> IGNITE-17661 Update packages version to 2.14

- bin/include/jvmdefaults.bat
- bin/include/jvmdefaults.sh
- parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-17660 …
> IGNITE-17660 Add missing opens/exports to java15+ config

- docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc
> IGNITE-17674 Document Kafka to thin client CDC streamer

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
- modules/core/src/test/java/org/apache/ignite/cdc/WalForCdcTest.java
> IGNITE-17668 Fix removing archive WAL segments for in-memory CDC mode

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/filehandle/FileWriteHandleImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/file/WalFilesCloseTest.java
- modules/indexing/src/test/java/org/apache/ignite/testsuites/IgnitePdsWithIndexingCoreTestSuite.java
> IGNITE-17675 Fixed file resources leak on cluster deactivation/stop in case non full sync WAL mode.

- modules/control-utility/src/test/java/org/apache/ignite/testsuites/IgniteControlUtilityTestSuite.java
- modules/control-utility/src/test/java/org/apache/ignite/testsuites/IgniteControlUtilityTestSuite2.java
https://issues.apache.org/jira/browse/IGNITE-17695 …
> IGNITE-17695 Split IgniteControlUtilityTestSuite in two

- modules/core/src/main/java/org/apache/ignite/DataRegionMetrics.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsMXBeanImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsSnapshot.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PageMetricsImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/FillFactorMetricTest.java
- modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/DataRegionMetricsTest.cs
https://issues.apache.org/jira/browse/IGNITE-17728 …
> IGNITE-17728 Improve size-related metrics

- bin/include/jvmdefaults.bat
- bin/include/jvmdefaults.sh
- docs/_docs/includes/java9.adoc
- modules/core/src/main/java/org/apache/ignite/internal/util/FeatureChecker.java
- parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-17758 …
> IGNITE-17758 Allow ConcurrentHashMap be marshalled on JDK 15+

- modules/platforms/cpp/binary/include/ignite/binary/binary_raw_writer.h
- modules/platforms/cpp/binary/include/ignite/impl/binary/binary_utils.h
- modules/platforms/cpp/binary/src/impl/binary/binary_utils.cpp
- modules/platforms/cpp/thin-client-test/src/continuous_query_test.cpp
- modules/platforms/cpp/thin-client/include/ignite/impl/thin/cache/cache_client_proxy.h
- modules/platforms/cpp/thin-client/include/ignite/impl/thin/platform_java_object_factory_proxy.h
- modules/platforms/cpp/thin-client/include/ignite/thin/cache/cache_client.h
- modules/platforms/cpp/thin-client/include/ignite/thin/cache/event/java_cache_entry_event_filter.h
- modules/platforms/cpp/thin-client/include/ignite/thin/cache/query/continuous/continuous_query_client.h
- modules/platforms/cpp/thin-client/src/impl/cache/cache_client_impl.cpp
- modules/platforms/cpp/thin-client/src/impl/cache/cache_client_impl.h
- modules/platforms/cpp/thin-client/src/impl/cache/cache_client_proxy.cpp
- modules/platforms/cpp/thin-client/src/impl/message.cpp
- modules/platforms/cpp/thin-client/src/impl/message.h
* Implemented Java remote filter for thin client.
* Added 2 tests. …
> IGNITE-16291 C++: Java remote filters for CQ for thin client

- modules/log4j2/src/main/java/org/apache/ignite/logger/log4j2/Log4J2Logger.java
- modules/log4j2/src/test/java/org/apache/ignite/logger/log4j2/Log4j2LoggerSelfTest.java
> IGNITE-17717 Fix APP_ID for Log4j2Logger

- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/defragmentation/CachePartitionDefragmentationManager.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/defragmentation/DefragmentationFileUtils.java
https://issues.apache.org/jira/browse/IGNITE-17761 …
> IGNITE-17761 Fixed PDS defragmentation on Windows

- modules/core/src/main/java/org/apache/ignite/internal/pagemem/impl/PageMemoryNoStoreImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/diagnostic/pagelocktracker/store/OffHeapPageMetaInfoStore.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/evict/Random2LruPageEvictionTracker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/evict/RandomLruPageEvictionTracker.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/ClockPageReplacementFlags.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/FullPageIdTable.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/PageMemoryImpl.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/RobinHoodBackwardShiftHashMap.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/SegmentedLruPageList.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/util/PageHandler.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/platform/memory/PlatformMemoryUtils.java
- modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java
- modules/core/src/main/java/org/apache/ignite/internal/util/offheap/unsafe/GridUnsafeMemory.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/tree/io/PageIOFreeSizeTest.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/memtracker/PageMemoryTracker.java
> IGNITE-17749 Remove unneeded zeroing of page, optimize memory zeroing.

- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
- modules/core/src/test/java/org/apache/ignite/internal/util/nio/FastSessionMoveAndKeyCancellationTest.java
https://issues.apache.org/jira/browse/IGNITE-17787 …
> IGNITE-17787 Fix node failures due to CancelledKeyException

- modules/core/src/main/java/org/apache/ignite/DataRegionMetrics.java
- modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsImpl.java
- modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/pagemem/FillFactorMetricTest.java
https://issues.apache.org/jira/browse/IGNITE-17783 …
> IGNITE-17783 Fix incorrect PagesFillFactor refactoring

- modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
https://issues.apache.org/jira/browse/IGNITE-17779 …
> IGNITE-17779 Fix infinite loop in RandomBalancer

- modules/core/src/test/java/org/apache/ignite/internal/encryption/CacheGroupReencryptionTest.java
https://issues.apache.org/jira/browse/IGNITE-17436 …
> IGNITE-17436 Fix CacheGroupReencryptionTest#testReencryptionOnUnstableTopology fails if checkpoint is skipped on node stop
