apache/ignite

modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryImpl.java
modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySpi.java
modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/TcpDiscoveryNode.java
modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/TcpDiscoveryNodesRing.java

This warning is printed out when a local server node is considered to be disconnected from the ring - it neither receives message nor sends to the next node.
In the buggy configuration (one server and one client nodes) the server periodically received messages from the client node but unable to send connection check messages to the next node cause there was no any. This affected failure detection timeout implementation logic.
As a fix, the failure should be detected and reported only when there are remote server nodes in a topology and a local node seems to be disconnected from them. To support this "TcpDiscovery.hasRemoteServerNodes()" method was implemented and used by failure timeout logic.

ignite-1241-dev: fixed failure timeout warning when only client is connected

---

modules/core/src/main/java/org/apache/ignite/internal/IgniteVersionUtils.java
modules/core/src/test/java/org/apache/ignite/internal/IgniteVersionUtilsSelfTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteUtilSelfTestSuite.java

copyrights date now depend on build date.

IGNITE-11084 copyrights date now depend on build date.

---

modules/web-console/web-agent/src/main/java/org/apache/ignite/console/agent/AgentLauncher.java
modules/web-console/web-agent/src/main/java/org/apache/ignite/console/agent/rest/RestExecutor.java

…n case of trustAll flag enabled.

IGNITE-11166 Web agent: Host name verifier should be disabled in case of "-Dtrust.all=true".

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientConnectionContext.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheConfigurationSerializer.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheRequest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformConfigurationUtils.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/CacheClientAsyncWrapper.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/CacheTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/CacheTestKeepBinary.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/ClientCacheConfigurationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/CreateCacheTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientTestBase.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cache/Expiry/ExpiryPolicy.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cache/ICache.cs
modules/platforms/dotnet/Apache.Ignite.Core/Client/Cache/CacheClientConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/Client/Cache/ICacheClient.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Cache/CacheClient.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Cache/ClientCacheConfigurationSerializer.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientSocket.cs

Added ability to create dynamic caches for thin clients with expiry policies.
- Added expiry policy property  to thin client cache configuration
- Added withExpiryPolicy method to the client cache interface
(cherry picked from commit b2b12eb31df3d240de8a657eec57cd6cbedb94fe)

IGNITE-9033 .NET: specify expiry policy when creating cache using thin client

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinaryBuilderSelfTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/BinaryBuilderTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Binary/IBinaryObjectBuilder.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryObjectBuilder.cs

Provide a way to set custom field type for metadata. Can be useful when passing values as `object` and calling `GetType()` on them (common use case is loading data in a generic way from another system):
```
foreach(IList<object> row in cursor)
  foreach(KeyValuePair<string, object> field in row)
    builder.SetField(field.Key, field.Value, field.Value.GetType())
```

IGNITE-12377 .NET: Add IBinaryObjectBuilder.SetField(name, val, type)

---

modules/platforms/dotnet/release/Program.cs
modules/platforms/dotnet/release/verify-nuget.ps1

Add a script to verify NuGet packages:
* Creates a test project with `dotnet new console`
* Installs all packages from specified folder with `dotnet add package`
* Runs a test program that uses basic Cache, SQL and LINQ APIs
* Checks exit codes to make sure there were no exceptions/errors

IGNITE-12390 .NET: Add NuGet verification script

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/CacheTestAsyncWrapper.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cache/ICache.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/CacheImpl.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/CacheOp.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Ignite.cs

* `WithReadRepair` was added to public API, but not implemented internally (`PlatformCache`) and not covered with tests. The functionality is somewhat niche and confusing, so let's remove it for now (not included into any release so far).
* `WithAllowAtomicOpsInTx` has a similar problem: implementation in `PlatformCache` is missing, there are no tests, the purpose is not clear. However, this was added much earlier and is present in 2.7.x releases, so we can't remove the method. Therefore marking it `[Obsolete]`.

IGNITE-12405 .NET: Remove WithReadRepair, deprecate WithAllowAtomicOpsInTx

---

modules/platforms/dotnet/Apache.Ignite.AspNet.Tests/ExpiryCacheHolderTest.cs
modules/platforms/dotnet/Apache.Ignite.AspNet/Apache.Ignite.AspNet.csproj
modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
modules/platforms/dotnet/Apache.Ignite.EntityFramework/Apache.Ignite.EntityFramework.csproj
modules/platforms/dotnet/Apache.Ignite.Linq/Apache.Ignite.Linq.csproj
modules/platforms/dotnet/Apache.Ignite.Log4Net/Apache.Ignite.Log4Net.csproj
modules/platforms/dotnet/Apache.Ignite.NLog/Apache.Ignite.NLog.csproj

.NET looks up documentation in `{assembly}.xml` files, and we had the extension in uppercase, causing missing documentation in IDE tooltips on case-sensitive filesystems (Linux, macOS).

IGNITE-12413 .NET: Fix xmldoc file extension for case-sensitive filesystems

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer/pom.xml

Maven seems to assume 1.5 language level by default, which is not supported in some Maven versions, causing a compiler error. Set version explicitly to fix this.

IGNITE-12473 .NET: Fix ClientServerCompatibilityTest - set Java version in pom.xml

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/CreateCacheTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientConnectionTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientProtocolCompatibilityTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientReconnectCompatibilityTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientServerCompatibilityTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer/pom.xml
modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer/src/main/java/Runner.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/ProcessExtensions.cs
modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
modules/platforms/dotnet/Apache.Ignite.Core/Client/IgniteClientConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryProcessorClient.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Cache/CacheClient.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Cache/Query/ClientQueryCursorBase.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientContextBase.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientFailoverSocket.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientRequestContext.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientResponseContext.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientSocket.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Cluster/ClientCluster.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/IgniteClient.cs
modules/platforms/dotnet/DEVNOTES.txt
modules/platforms/dotnet/build.ps1
modules/platforms/dotnet/release/Program.cs

Old servers do not support the extra flag, which causes exception and disconnect.
* Refactor client operation handling to be able to check `ProtocolVersion` of the exact connection that is used for the given operation
* Add `ProtocolVersion` check for cache operations with expiry policy.
* Fix `ProtocolVersion` check for `CacheConfiguration`

IGNITE-12471 .NET Thin Client: Fix WithExpiryPolicy crash

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPreloader.java

Fix a typo in the log message about the topology version context
when check if rebalance should be started

IGNITE-12642 Fix a typo in the log message about the topology version context.

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests.DotNetCore/Apache.Ignite.Core.Tests.DotNetCore.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinaryStructureTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/TypeNameParserTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTest.Misc.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Structure/BinaryStructure.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Structure/BinaryStructureEntry.cs
modules/platforms/dotnet/Apache.Ignite.DotNetCore.sln.DotSettings

* Fix NullReferenceException in BinaryStructure.GetFieldId
* Remove dead code
NRE was caused by empty (default) BinaryStructureEntry caused by replacing longer structure path with shorter one, then again using a longer path. This can be caused by the following behavior of `IBinarizable.WriteBinary`:
* First write: fields "Bar", "Foo"
* Second write: fields "Foo"
* Third write: fields "Foo", "Bar"
Third write yields structure path from second write, but second entry there is empty.

IGNITE-12860 .NET: Fix NRE in BinaryStructure.GetFieldId

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests.NuGet/install-package.ps1
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTest.Misc.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Log/CustomLoggerTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cache/Configuration/CacheConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/Configuration/DataRegionConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/Configuration/DataStorageConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/IgniteConfiguration.cs
modules/platforms/dotnet/build.ps1

New NuGet release has a bug causing failing builds: https://github.com/NuGet/Home/issues/9458
To fix this and prevent future issues, use a fixed NuGet version instead of the latest.

IGNITE-12940 .NET: Use fixed NuGet version in build script

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java

Fixed:
- `wasRebalanced` flag doesn't keep after snapshot
- `ExchangeType` must be `NONE` for the snapshot on a client node
- exchange aware component is not covered by test for a snapshot operation

IGNITE-12981: Fix pme-free snapshot exchange if coordinator left the cluster

---

modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperDiscoverySpiSslTestBase.java

After merging IGNITE-110947, in `cloneDiscoverySpi` input parameter was obtained every time from `getConfiguration()`, but not from first node, as it should be. This behaviour leads to instant failure of multijvm tests `GridCacheAtomicMultiJvmFullApiSelfTest` and   `GridCachePartitionedMultiJvmFullApiSelfTest`. After merging IGNITE-12992, this twist doesn't work and configuration cloned from first node, as it should. So we must set zk connection string explicitly.

IGNITE-12999: Fix ZookeeperDiscoverySpiSslTest.testIgniteSslWrongPort

---

modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2Table.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/TableStatistics.java

IGNITE-13068 use cache.localSize instead of index scan to calculate кow count statistic

---

modules/core/src/main/java/org/apache/ignite/internal/IgniteKernal.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteUtilSelfTestSuite.java
modules/core/src/test/java/org/apache/ignite/thread/ThreadPoolMetricsTest.java

IGNITE-12085: Fix the late registration of the thread pools metrics.

---

modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java

We should remove hardcoded timeout of 200ms from:
boolean ServerImpl.CrossRingMessageSendState.markLastFailedNodeAlive():
try {
Thread.sleep(200);
}
catch (InterruptedException e) {
Thread.currentThread().interrupt();
}
This can bring additional 200ms to duration of failed node detection.

IGNITE-13017 : Remove hardcoded delay from re-marking failed node as alive.

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests.DotNetCore/Common/TestRunner.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Compute/ComputeClientTests.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtils.Common.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientNotificationHandler.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientSocket.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Compute/ComputeClient.cs

Fix race condition in `ClientSocket.AddNotificationHandler`: `SetHandler` call was causing `RemoveNotificationHandler` call before `ConcurrentDictionary.AddOrUpdate` has finished, so `AddOrUpdate` added the handler back, causing the leak.

IGNITE-13226 .NET: Fix ClientNotificationHandler leak in ClientSocket

---

docker/apache-ignite/run.sh

Ticket was specifically about `-nojmx` flag but I don't think there's a good reason to limit it to that.

IGNITE-11715 Allow extra options to be passed in to ignite.sh from Docker

---

modules/platforms/dotnet/Apache.Ignite.BenchmarkDotNet/Models/BenchmarkEnum.cs
modules/platforms/dotnet/Apache.Ignite.BenchmarkDotNet/Models/ClassWithEnumField.cs
modules/platforms/dotnet/Apache.Ignite.BenchmarkDotNet/Models/ClassWithIntField.cs
modules/platforms/dotnet/Apache.Ignite.BenchmarkDotNet/Program.cs
modules/platforms/dotnet/Apache.Ignite.BenchmarkDotNet/ThinClient/ThinClientCachePutBenchmark.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/EnumsTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryWriter.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Metadata/BinaryType.cs

* Don't send enum metadata more than once (main part of this fix - see `BinaryWriter` changes)
* Cache name-value map per enum type
* Add benchmark
As a result, enum field serialization is on par with int field:
```
|                Method |     Mean |    Error |   StdDev | Ratio | RatioSD |
|---------------------- |---------:|---------:|---------:|------:|--------:|
|          PutPrimitive | 45.47 us | 0.907 us | 1.330 us |  1.00 |    0.00 |
|     PutPrimitiveAsync | 66.28 us | 1.317 us | 1.617 us |  1.45 |    0.05 |
|  PutClassWithIntField | 68.34 us | 1.275 us | 1.130 us |  1.49 |    0.05 |
| PutClassWithEnumField | 71.13 us | 1.419 us | 2.734 us |  1.57 |    0.08 |
```

IGNITE-13293 .NET: Fix enum serialization performance

---

modules/ducktests/tests/docker/Dockerfile

Fixed: Java app runs with UTC timezone whereas ducktape orchestrator in Europe/Moscow

Fix timezone in docker container

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/ReconnectTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cluster/ClusterGroupImpl.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Ignite.cs

Client reconnect causes local node ID to change, so we should reset cached node data on disconnect.

IGNITE-13369 .NET: Clear cached node data on client disconnect

---

modules/ducktests/tests/ignitetest/services/utils/config_template.py

Fix paths that contains templates. Currently this path calculates from variable, but there are list of built-in templates on persisted path.

Fix discovery templates discovery path

---

modules/ducktests/tests/README.md
modules/ducktests/tests/setup.py

Remove tox from ignitetest setup.py due to version conflict with ducktape

Make tox external dependency.

---

modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/smoke_test/AssertionApplication.java
modules/ducktests/tests/ignitetest/services/ignite_app.py
modules/ducktests/tests/ignitetest/services/ignite_execution_exception.py
modules/ducktests/tests/ignitetest/tests/assertion_test.py
modules/ducktests/tests/ignitetest/utils/ignite_test.py

IGNITE-13434 add assertion test

---

modules/core/src/test/java/org/apache/ignite/client/FunctionalTest.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientAbstractPartitionAwarenessTest.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientPartitionAwarenessStableTopologyTest.java

* Add partition awareness tests for partitioned caches with backups
* Add transactions tests for pessimistic and optimistic modes
* Fix `new Thread()` usage in tests: assertion errors were ignored in some tests

IGNITE-13485 Java thin: increase test coverage for transactions and partition awareness

---

docs/_docs/monitoring-metrics/system-views.adoc

JOBS system view description added.

---

modules/ml/src/test/java/org/apache/ignite/ml/dataset/impl/cache/util/DatasetAffinityFunctionWrapperTest.java

Added 'silent' mode for such kind of empty stub erros (due to Mockito version update)

IGNITE-13532 [ML]: Fixed test DatasetAffinityFunctionWrapperTest

---

modules/ml/src/main/java/org/apache/ignite/ml/math/primitives/vector/AbstractVector.java
modules/ml/src/test/java/org/apache/ignite/ml/math/primitives/vector/VectorNormCasesTest.java
modules/ml/src/test/java/org/apache/ignite/ml/math/primitives/vector/VectorNormTest.java

Current implementation of `Vector::kNorm` is incorrect. 
Current formula is (`org.apache.ignite.ml.math.primitives.vector.AbstractVector:882`):
```
(\sum_{i}{x^p})^{1/p}
```
But correct formula is:
```
(\sum_{i}{|x|^p})^{1/p}
```
We can verify this using lectures (https://www.math.usm.edu/lambers/mat610/sum10/lecture2.pdf) or using Wolfram Mathematica:
```
> Norm[{x, y, z}, p]
(Abs[x]^p+Abs[y]^p+Abs[z]^p)^(1/p)
```
Issue: https://issues.apache.org/jira/browse/IGNITE-13392

IGNITE-13392 [ML]: fix Incorrect Vector::kNorm evaluation for odd powers

---

modules/ml/src/main/java/org/apache/ignite/ml/math/distances/BrayCurtisDistance.java
modules/ml/src/main/java/org/apache/ignite/ml/math/distances/CanberraDistance.java
modules/ml/src/main/java/org/apache/ignite/ml/math/distances/JensenShannonDistance.java
modules/ml/src/main/java/org/apache/ignite/ml/math/distances/WeightedMinkowskiDistance.java
modules/ml/src/test/java/org/apache/ignite/ml/math/distances/BrayCurtisDistanceTest.java
modules/ml/src/test/java/org/apache/ignite/ml/math/distances/CanberraDistanceTest.java
modules/ml/src/test/java/org/apache/ignite/ml/math/distances/DistanceTest.java
modules/ml/src/test/java/org/apache/ignite/ml/math/distances/JensenShannonDistanceTest.java
modules/ml/src/test/java/org/apache/ignite/ml/math/distances/WeightedMinkowskiDistanceTest.java

add distances 
- BrayCurtis
- Canberra
- JensenShannon
- WeightedMinkowski
Issue: https://issues.apache.org/jira/browse/IGNITE-13386

IGNITE-13386 [ML]: Add new distances (BrayCurtis, Canberra, JensenShannon and etc)

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinarySelfTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryObject.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryWriter.cs

After investigating the [issue](https://issues.apache.org/jira/browse/IGNITE-13563), it seems to occur because `BinaryObject.Deserialize<T>()` uses `BinaryMode.Deserialize`. This, in turn, causes `BinaryReader.ReadBinaryObject()` to call `BinaryReader.Deserialize()` for the first `BinaryTypeId.Binary` object found (while switching to `BinaryMode.KeepBinary` for nested objects). Then, `BinaryReader.ReadFullObject()` gets called, and not knowing better, tries to deserialize the object of a nonexistent type.
Now, `BinaryMode.Deserialize` is also used by `CacheClient`. However, upon further investigation of the values passed to `Marshaller.Unmarshall`, `CacheClient` unmarshalls values starting with `BinaryTypeId.Binary`, while `BinaryObject` unmarshalls values starting directly with …

IGNITE-13563: Fix deserializing IBinaryObject containing an IBinaryObject field

---

modules/platforms/dotnet/README.md

* Fix NuGet link to point to Ignite packages
* Remove old .NET logo
* Fix Ignite logo

.NET: Fix logos and NuGet link in README.md

---

modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
modules/core/src/main/java/org/apache/ignite/internal/binary/builder/BinaryObjectBuilderImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformContext.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformContextImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/callback/PlatformCallbackGateway.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/callback/PlatformCallbackOp.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/SqlCacheStartStopTest.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.DotNetCore.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Affinity/AffinityTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/QueryEntityMetadataRegistrationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/ClientQueryEntityMetadataRegistrationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/ClientQueryEntityMetadataRegistrationTestJavaOnlyServer.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/native-client-test-cache-affinity.xml
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/query-entity-metadata-registration.xml
modules/platforms/dotnet/Apache.Ignite.Core/Cache/Configuration/QueryEntity.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Marshaller.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/UnmanagedCallbackOp.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/UnmanagedCallbacks.cs

* Register binary metadata for QueryEntity key and value .NET types on cache start (same way as we do for Java types - IGNITE-5795, 3bb03444246f863096063d084393676a84d2bc0e)
* Move `registerMetadataForRegisteredCaches` call to `onCacheKernalStart` so that `PlatformProcessor` is available
This builds on the fix from IGNITE-5795 by adding a platform callback to get metadata for .NET types. It has the same limitations as the original fix: does not work when classes are not present on the server node, in particular, for thin clients. IGNITE-13607 filed to deal with that separately.

IGNITE-13160 .NET: Register binary metadata during cache start

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheMapEntry.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/IgniteCacheOffheapManagerImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/tree/PendingEntriesTree.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/ttl/CacheSizeTtlTest.java
modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteCacheWithIndexingTestSuite.java

https://issues.apache.org/jira/browse/IGNITE-9474
Fixed an issue where the cache size could return a wrong value when TTL is enabled.

IGNITE-9474 Fix incorrect cache.size() with ttl enabled

---

modules/core/src/main/java/org/apache/ignite/internal/processors/metastorage/persistence/DistributedMetaStorageUtil.java
modules/ml/src/main/java/org/apache/ignite/ml/clustering/kmeans/KMeansTrainer.java
modules/ml/src/main/java/org/apache/ignite/ml/dataset/feature/ObjectHistogram.java
modules/ml/src/main/java/org/apache/ignite/ml/dataset/impl/cache/util/ComputeUtils.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/IgniteModelStorageUtil.java
modules/ml/src/main/java/org/apache/ignite/ml/math/Blas.java
modules/ml/src/main/java/org/apache/ignite/ml/math/util/MapUtil.java
modules/ml/src/main/java/org/apache/ignite/ml/math/util/MatrixUtil.java
modules/ml/src/main/java/org/apache/ignite/ml/nn/Activators.java
modules/ml/src/main/java/org/apache/ignite/ml/preprocessing/imputing/ImputerTrainer.java
modules/ml/src/main/java/org/apache/ignite/ml/preprocessing/maxabsscaling/MaxAbsScalerTrainer.java
modules/ml/src/main/java/org/apache/ignite/ml/preprocessing/minmaxscaling/MinMaxScalerTrainer.java
modules/ml/src/main/java/org/apache/ignite/ml/util/Utils.java

- add a private constructorto Util classes in ignite ml.
- add Serializable to Blas class
- add final modifier to static inner fields in utils class
- inefficient use of keySet iterator instead of entrySet
- can be replaced with single Arrays.fill method call
Issue: https://issues.apache.org/jira/browse/IGNITE-13531

IGNITE-13531 [ML]: Code cleanup in Util classes

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/PlatformCache.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/query/PlatformContinuousQuery.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/query/PlatformContinuousQueryImpl.java
modules/platforms/cpp/core/src/impl/cache/cache_impl.cpp
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Continuous/ContinuousQueryAbstractTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Continuous/ContinuousQueryTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/ContinuousQueryTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
modules/platforms/dotnet/Apache.Ignite.Core/Cache/Event/CacheEntryEventType.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cache/Query/Continuous/ContinuousQuery.cs
modules/platforms/dotnet/Apache.Ignite.Core/Client/Cache/Query/Continuous/ContinuousQueryClient.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/Event/CacheEntryExpireEvent.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/Query/Continuous/ContinuousQueryHandleImpl.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/Query/Continuous/ContinuousQueryUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Cache/CacheClient.cs
modules/platforms/dotnet/Apache.Ignite.DotNetCore.sln.DotSettings

* Add `IncludeExpired` flag to thin and thick continuous query APIs: `ContinuousQuery`, `ContinuousQueryClient`
* Thin client protocol not affected: the flag is already supported

IGNITE-13357 .NET: Add IncludeExpired to ContinuousQuery and ContinuousQueryClient

---

modules/core/src/main/java/org/apache/ignite/cache/query/SqlFieldsQuery.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientUtils.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/ProtocolBitmaskFeature.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/PlatformCache.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientBitmaskFeature.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/cache/ClientCacheSqlFieldsQueryRequest.java
modules/indexing/src/test/java/org/apache/ignite/client/FunctionalQueryTest.java
modules/platforms/cpp/core/include/ignite/cache/query/query_sql_fields.h
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/CacheQueriesTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTest.Introspection.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/SqlQueryTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cache/Query/SqlFieldsQuery.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryHashCodeUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Cache/CacheClient.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientBitmaskFeature.cs
modules/platforms/dotnet/Apache.Ignite.Linq/Apache.Ignite.Linq.csproj
modules/platforms/dotnet/Apache.Ignite.Linq/Impl/CacheFieldsQueryExecutor.cs
modules/platforms/dotnet/Apache.Ignite.Linq/QueryOptions.cs

* Add `Partitions` and `UpdateBatchSize` to `SqlFieldsQuery` and `QueryOptions` (LINQ) for thick and thin APIs
* Add `updateBatchSize` validation on the server side (invalid values were ignored previously)
* Propagate `updateBatchSize` and `partitions` in Java thin client

IGNITE-13608 .NET: Add Partitions and UpdateBatchSize to SqlFieldsQuery

---

modules/core/src/test/java/org/apache/ignite/internal/encryption/EncryptedCacheNodeJoinTest.java

IGNITE-13807 Fix error message validation in tests.

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheOffheapManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/RowStore.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/H2RowCacheSelfTest.java

IGNITE-13776 BPlus tree lock retries limit reached with sqlOnHeapCacheEnabled

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/CacheAbstractTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/PlatformTargetAdapter.cs

Fix async cache operations when key and value objects reference each other or have references to the same object.
Async key-val operations used `WriteObject` instead `WriteObjectDetached`, so references to the same inner object were shared in the binary stream (referenced object is written once). However, cache stores key and val binary objects separately, so the reference to the inner object gets broken.
`WriteObjectDetached` disables reference sharing and writes both object independently.

IGNITE-8884 .NET: Fix async key-val operations - use WriteObjectDetached

---

modules/ducktests/tests/ignitetest/services/ignite.py
modules/ducktests/tests/ignitetest/services/ignite_app.py
modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py
modules/ducktests/tests/ignitetest/services/utils/ignite_persistence.py
modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
modules/ducktests/tests/ignitetest/tests/discovery_test.py

IGNITE-13829: added rotate log

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/binary/PlatformBinaryProcessor.java
modules/core/src/test/java/org/apache/ignite/platform/Account.java
modules/core/src/test/java/org/apache/ignite/platform/PlatformDeployServiceTask.java
modules/core/src/test/java/org/apache/ignite/platform/model/ACL.java
modules/core/src/test/java/org/apache/ignite/platform/model/Account.java
modules/core/src/test/java/org/apache/ignite/platform/model/Address.java
modules/core/src/test/java/org/apache/ignite/platform/model/Department.java
modules/core/src/test/java/org/apache/ignite/platform/model/Employee.java
modules/core/src/test/java/org/apache/ignite/platform/model/Key.java
modules/core/src/test/java/org/apache/ignite/platform/model/Role.java
modules/core/src/test/java/org/apache/ignite/platform/model/User.java
modules/core/src/test/java/org/apache/ignite/platform/model/Value.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/IJavaService.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/JavaServiceDynamicProxy.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/Model.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServiceProxyTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServiceTypeAutoResolveTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryProcessor.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryProcessorClient.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Marshaller.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Services/ServiceProxySerializer.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Services/Services.cs

This PR fixes bug that occurs on the invocation of the service method that has not registered return type.
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Codin …

IGNITE-13734 .NET: Register service return type on method invocation

---

modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/util/HostAndPortRange.java
modules/core/src/test/java/org/apache/ignite/client/ConnectionTest.java
modules/core/src/test/java/org/apache/ignite/client/LocalIgniteCluster.java
modules/core/src/test/java/org/apache/ignite/internal/util/HostAndPortRangeTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteUtilSelfTestSuite.java

- changed HostAndPortRange.parse method to support addresses like [IPv6_host]:port1..port2, because previous implementation didn't recognized IPv6;
- implemented unit tests for HostAndPortRange.parse method for both IPv4 and IPv6 hosts.

IGNITE-13555 Java thin: add IPv6 address support

---

modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryRawReaderEx.java
modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryReaderExImpl.java
modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryUtils.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/services/PlatformServices.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformUtils.java
modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryMarshallerSelfTest.java
modules/core/src/test/java/org/apache/ignite/platform/PlatformDeployServiceTask.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/IJavaService.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/JavaServiceDynamicProxy.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServiceTypeAutoResolveTest.cs

The array of user objects can't be deserialized on the java side. …

IGNITE-13897 .NET: Service can't assign correct type to passed array parameters

---

modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py

Fixed logging of node failure simalating.

ducktape log fix

---

modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/discovery.py
modules/ducktests/tests/ignitetest/services/utils/templates/discovery_macro.j2
modules/ducktests/tests/ignitetest/services/zk/templates/zookeeper.properties.j2
modules/ducktests/tests/ignitetest/services/zk/zookeeper.py
modules/ducktests/tests/ignitetest/tests/discovery_test.py

Introduces soLinger for Ignite 2.8.1 to reduce node failure detection. + other minor params.

ducktape-better-params

---

modules/ducktests/tests/ignitetest/services/utils/jmx_utils.py

Sometimes MBeans structure looks like:
org.apache:clsLdr=764c12b6,group=Kernal,igniteInstanceName=Server_Example_Xml_-676757500,name=IgniteKernal
but jmx_utils works only if it looks like:
.*group=Kernal,name=IgniteKernal
This PR change search pattern …

IGNITE-14012 fix ducktape jmx_tools MBean pattern

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/MessagingTest.cs

* Improve assertions to understand the failures easier
* Add `TestStopRemoteListenRemovesAllCallbacksUponExit` to demonstrate the problem, ignore with a ticket link
* Add `AssertHandleRegistryHasItems` with a timeout to fix the flakiness

IGNITE-14033 .NET: Fix MessagingTest.TestRemoteListen flakiness

---

modules/platforms/dotnet/build.ps1

NuGet is required both for building the .NET Framework part and for the packing.

IGNITE-14047 .NET: Fix NuGet download condition in build.ps1

---

modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryTypeDescriptorImpl.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/CacheQueriesCodeConfigurationTest.cs

Do not add `_KEY` and `_VAL` to `validateProps` when no constraints are defined for them. This brings back previous behavior that existed before 2.9.

IGNITE-13957 Fix unnecessary key/val deserialization in GridQueryProcessor

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/CacheQueriesCodeConfigurationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryUtils.cs

`BinaryUtils.GetSqlTypeName` used to return `Type.FullName`, which includes assembly-qualified type names for all generic type arguments, which causes the following problems:
* SQL type name includes assembly versions, so queries stop working if there is a version change
* Incorrect binary type id is registered through the {{UnmanagedCallbacks.BinaryTypeGet}}
Remove assembly part from the SQL type name to tolerate version changes in the same way as we do for regular binary types.

IGNITE-13588 .NET: Fix SQL type name for generic query types

---

modules/core/src/main/java/org/apache/ignite/binary/BinaryBasicNameMapper.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/QueryUtils.java
modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryBasicNameMapperSelfTest.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/CacheQueriesCodeConfigurationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTest.Misc.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryUtils.cs

* Fix `BinaryNameMapper.simpleName` to strip namespaces from generic types
* Fix `QueryUtils.typeName` to strip generic part

IGNITE-14064 .NET: Fix SQL table name for generic query types

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientBitmaskFeature.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/binary/ClientBinaryConfigurationGetRequest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/binary/ClientBinaryConfigurationGetResponse.java
modules/core/src/test/java/org/apache/ignite/platform/PlatformCustomBinaryBasicNameMapper.java
modules/core/src/test/java/org/apache/ignite/platform/PlatformCustomBinaryNameMapper.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests.TestDll2/Properties/AssemblyInfo.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.DotNetCore.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Binary/BinaryConfigurationRetrievalTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientFeaturesTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/binary-custom-name-mapper.xml
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/binary-custom-name-mapper2.xml
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Binary/BinaryConfigurationClientInternal.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/Binary/BinaryNameMapperMode.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientFailoverSocket.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientFeatures.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientOp.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/IgniteClient.cs

* Add `OP_BINARY_CONFIGURATION_GET` to the protocol, and `BINARY_CONFIGURATION` feature flag
* Retrieve the configuration in .NET thin client
* The only automatic adjustment: change `CompactFooter` from `true` to `false` on the client
* Log warnings in other cases of configuration mismatch: we can't change name mapper automatically, and we can't enable compact footers automatically, because it can break other clients which don't have compact footer support or rely on a specific name mapping.

IGNITE-14103 .NET: Add thin client automatic binary configuration

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/CacheLocalAtomicTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/CacheLocalTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/PersistenceTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Platform/PlatformCacheTopologyChangeTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/CacheDmlQueriesTestSimpleName.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/CacheQueriesTestSimpleName.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Continuous/ContinuousQueryTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTestSimpleName.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Linq/CacheLinqTestSqlEscapeAll.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/CacheTestAsync.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/CacheTestSsl.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/ContinuousQueryTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cluster/ClientClusterDiscoveryTests.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cluster/ClientClusterDiscoveryTestsBaselineTopology.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cluster/ClientClusterDiscoveryTestsNoLocalhost.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cluster/ClientClusterDiscoveryTestsSsl.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Compute/ComputeClientTests.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/ComputeApiTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/ComputeApiTestFullFooter.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteLockTests.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTestAsync.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTestFullFooter.cs
modules/platforms/dotnet/DEVNOTES.txt

* Review all tests duration and mark slow ones with `[Category(TestUtils.CategoryIntensive)]`
* Update DEVNOTES with a command to run quick tests only
|          | All Tests | Quick Tests |
|----------|-----------|-------------|
| Count    | 3242      | 1777        |
| Run time | 35 min    | 4 min       |

IGNITE-14116 .NET: Update tests with LongRunning category

---

docs/_docs/net-specific/net-deployment-options.adoc
docs/_docs/net-specific/net-troubleshooting.adoc
modules/platforms/dotnet/Apache.Ignite.Core.Tests/ProjectFilesTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/DllLoader.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/NativeLibraryUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/UnmanagedThread.cs
modules/platforms/dotnet/DEVNOTES.txt

* Fix `DllNotFoundException: Unable to load shared library 'libcoreclr.so'` error in single file mode on .NET 5 by adding a custom `DllImportResolver`
* Update Deployment and Troubleshooting documentation

IGNITE-12941 .NET: Fix and document single file deployment on .NET 5

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Compatibility/ClientReconnectCompatibilityTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientFailoverSocket.cs

* Fix failing `TestReconnectToOldNodeDisablesPartitionAwareness`: when thin client reconnects to a new "default" node, and that node does not support partition awareness, the feature should be disabled automatically. 
* Enable the test on .NET Core
* Fix compatibility test flakiness: add port range to `JavaServer.GetClientConfiguration`

IGNITE-14173 .NET: Fix partition awareness auto-disable on old servers

---

modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringBuilder.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractQuerySelfTest.java

This PR fixes IgniteCacheAbstractQuerySelfTest#testClientQueryExecutedEventsIncludeSensitive which is broken since 2ed8e7c
- [Coding …

IGNITE-14241 Fix testClientQueryExecutedEventsIncludeSensitive

---

modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.nuspec

Test Ignite with recent `System.Configuration.ConfigurationManager` versions (including 6.x preview), and extend supported version range accordingly.

IGNITE-14243 .NET: Extend ConfigurationManager dependency version range

---

modules/sqlline/bin/sqlline.bat
modules/sqlline/bin/sqlline.sh

It does Class.forName() but also causes warning `Property "url" is required' under sqlline 1.9
We do not need it, since thick driver works just fine even at it is not mentioned in -d.
- [How to …

IGNITE-14284 Remove -d option from sqlline invocation.

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/JavaServiceDynamicProxy.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTypeAutoResolveTest.cs

This patch improves .NET `ServicesTest` by 
* removing code duplication
* adding checks for a return array type
* adding case when service deployed on the server node and .Net call it via the client one. …

IGNITE-14311 .NET: ServiceTest refactoring

---

modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformConfigurationUtils.java
modules/core/src/main/java/org/apache/ignite/internal/visor/node/VisorDataStorageConfiguration.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/reader/IgniteWalReaderTest.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/full-config.xml
modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationSerializerTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteConfigurationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Configuration/DataStorageConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/IgniteConfigurationSection.xsd

This PR introduces new `DataStorageConfiguration` parameter `walForceArchiveTimeout`.
If this parameter set then Ignite will execute WAL segment rollover each `walForceArchiveTimeout` milliseconds.
This change required to successfully implement [Ignite CDC feature](https://cwiki.apache.org/confluence/display/IGNITE/IEP-59+CDC+-+Capture+Data+Change)
- [How to …

IGNITE-13582 WAL force rollover timeout introduced

---

modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerClusterByClassTest.java
modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/DataEntry.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/DataRecord.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/LazyDataEntry.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/MvccDataEntry.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/UnwrapDataEntry.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/WALRecord.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheMapEntry.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxRemoteAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/colocated/GridDhtDetachedCacheEntry.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearCacheEntry.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/reader/StandaloneWalRecordsIterator.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordDataV1Serializer.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordDataV2Serializer.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxLocalAdapter.java
modules/core/src/test/java/org/apache/ignite/TestStorageUtils.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgnitePdsSporadicDataRecordsOnBackupTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/file/IgnitePdsCheckpointSimulationWithRealCpDisabledTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/IgniteWalRebalanceTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/reader/IgniteWalReaderTest.java
modules/core/src/test/java/org/apache/ignite/testframework/wal/record/RecordUtils.java
modules/dev-utils/src/main/java/org/apache/ignite/development/utils/DataEntryWrapper.java
modules/dev-utils/src/main/java/org/apache/ignite/development/utils/WalStat.java
modules/dev-utils/src/test/java/org/apache/ignite/development/utils/IgniteWalConverterArgumentsTest.java
modules/dev-utils/src/test/java/org/apache/ignite/development/utils/IgniteWalConverterSensitiveDataTest.java
modules/dev-utils/src/test/java/org/apache/ignite/development/utils/IgniteWalConverterTest.java

This PR introduces `primary` flag for WAL `DataRecord`.
Flag will be used in [Ignite CDC application](https://cwiki.apache.org/confluence/display/IGNITE/IEP-59+CDC+-+Capture+Data+Change) to distinguish changes that happened on primary and backup. …

IGNITE-13596 Flag to distinguish DataRecord on primary and backup added

---

modules/ducktests/tests/ignitetest/tests/discovery_test.py

INPUT network failures are incosistent with disabled connection recovery in the ducktests. Alive node can be thrown out the ring.

IGNITE-14437 : Adjust test params: exclude input net failures with disabled connRecovery

---

modules/core/src/main/java/org/apache/ignite/internal/IgnitionEx.java
modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
modules/core/src/main/java/org/apache/ignite/logger/LoggerPostfixAware.java
modules/core/src/main/java/org/apache/ignite/logger/java/JavaLogger.java
modules/core/src/main/java/org/apache/ignite/logger/java/JavaLoggerFileHandler.java
modules/core/src/test/java/org/apache/ignite/logger/java/JavaLoggerTest.java
modules/core/src/test/java/org/apache/ignite/testframework/junits/logger/GridLog4jRollingFileAppender.java
modules/core/src/test/java/org/apache/ignite/testframework/junits/logger/GridTestLog4jLogger.java
modules/log4j/src/main/java/org/apache/ignite/logger/log4j/Log4JLogger.java
modules/log4j/src/main/java/org/apache/ignite/logger/log4j/Log4jNodeIdFilePath.java
modules/log4j2/src/main/java/org/apache/ignite/logger/log4j2/Log4J2Logger.java
modules/log4j2/src/test/java/org/apache/ignite/logger/log4j2/Log4j2LoggerSelfTest.java

This PR adds an ability for Ignite-related application to specify string log file postfix instead of `UUID` nodeId.
It will allow those applications to store their own log files near ignite logs.
* LoggerPostfixAware interface introduced
* LoggerNodeIdAware interface deprecated
- …

IGNITE-14353 Ability to specify postfix for IgniteLogger instead of nodeId

---

modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySpi.java
modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoveryIpFinderFailureTest.java
modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TestDynamicIpFinder.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteSpiDiscoverySelfTestSuite.java
modules/kubernetes/src/test/java/org/apache/ignite/kubernetes/discovery/KubernetesDiscoveryAbstractTest.java
modules/kubernetes/src/test/java/org/apache/ignite/kubernetes/discovery/TestClusterClientConnection.java
modules/kubernetes/src/test/java/org/apache/ignite/kubernetes/discovery/TestKubernetesIpFinderDisconnection.java
modules/kubernetes/src/test/java/org/apache/ignite/testsuites/IgniteKubernetesTestSuite.java

* Fixed TcpDiscoverySpi might be stuck infinitely resolving IP addresses, now the process is configurable either using netTimeout or joinTimeout depending on a process.
(cherry picked from commit b6735e14e8f47bed7ef478e02c6f78d732d353e0) …

IGNITE-14324 EVT_CLIENT_NODE_DISCONNECTED is not triggered in k8s

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/IgniteStartStopTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Ignition.cs

On Linux, Java overwrites SIGSEGV handler installed by .NET, so NullReferenceException causes a confusing "Stack smashing detected" error. This can be fixed by setting COMPlus_EnableAlternateStackCheck environment variable. Log a warning to raise user awareness.

IGNITE-14644 .NET: Log a warning about COMPlus_EnableAlternateStackCheck

---

docs/_data/toc.yaml
docs/_docs/key-value-api/basic-cache-operations.adoc
docs/_docs/net-specific/net-async.adoc
modules/core/src/main/java/org/apache/ignite/lang/IgniteFuture.java
modules/platforms/dotnet/Apache.Ignite.Benchmarks/ThinClient/ThinClientPutAsyncBenchmark.cs

Java:
* Update "Asynchronous Execution" section on "Basic Cache Operations" page
* Fix IgniteFuture javadoc (listen methods)
.NET:
* Add dedicated async page to ".NET Specific" section
* Document Cache and Compute async continuation behavior in different versions

IGNITE-14609 Document old and new async continuation behavior

---

modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/DurableBackgroundCleanupIndexTreeTask.java
modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/metastorage/pendingtask/DurableBackgroundTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/metastorage/pendingtask/DurableBackgroundTaskResult.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/localtask/DurableBackgroundTaskState.java
modules/core/src/main/java/org/apache/ignite/internal/processors/localtask/DurableBackgroundTasksProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteDataStorageMetricsSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/wal/WalArchiveConsistencyTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/localtask/DurableBackgroundTasksProcessorSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/localtask/ObservingCheckpointListener.java
modules/core/src/test/java/org/apache/ignite/internal/processors/localtask/SimpleTask.java
modules/core/src/test/java/org/apache/ignite/testframework/junits/common/GridCommonAbstractTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgnitePdsTestSuite.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/LongDestroyDurableBackgroundTaskTest.java

IGNITE-14625

---

modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/CacheGroupPageScanner.java
modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/GridEncryptionManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/GridCacheDatabaseSharedManager.java
modules/core/src/test/java/org/apache/ignite/internal/encryption/CacheGroupReencryptionTest.java

IGNITE-14424

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformProcessorImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteMarshallerCacheSeparateDirectoryTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/QueryEntityMetadataRegistrationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/ShellTests.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Shell.cs

* Restore `registerMetadataForRegisteredCaches` call in `GridQueryProcessor#start` - this fixes Java-side behavior, but breaks registration for platform types, because `PlatformProcessor` is not available at this point
* Call `registerMetadataForRegisteredCaches` second time from `PlatformProcessorImpl.start` only for platform types

IGNITE-14856 Fix "Failed to resolve class name" on server when cache with indexed types is defined on client

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheGroupContext.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheGroupMetricsImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/IgniteCacheDatabaseSharedManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/metric/GridMetricManager.java
modules/core/src/test/java/org/apache/ignite/internal/metric/CacheMetricsAddRemoveTest.java
modules/core/src/test/java/org/apache/ignite/internal/metric/MetricsClusterActivationTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/IgniteSequenceInternalCleanupTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite.java

Remove data region/cache/cache group metrics on deactivation without removing metrics configuration.

IGNITE-14990 Incorrect values of cache, cache group, data region metrics after cluster re-activation

---

.travis.yml

Upgrade Travis image for checks. Trusty isn't fully supported by Travis now, so it's impossible to debug it locally.

IGNITE-15041 Upgrade travis image to xenial

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/continuous/SecurityAwareFilter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/query/PlatformContinuousQueryImpl.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Query/Continuous/ContinuousQueryTest.cs

Add null check to `SecurityAwareFilter`, because `PlatformContinuousQueryImpl` always sets itself as a remote filter, but serializes as null when the actual filter is not present.

IGNITE-15045 .NET: Fix NullPointerException in ContinuousQuery with security enabled

---

modules/core/src/main/java/org/apache/ignite/events/EventType.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotSelfTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotRestoreWithIndexingTest.java

IGNITE-15062 Events for snapshot restore operation.

---

modules/ducktests/tests/ignitetest/tests/rebalance/persistent_test.py

DuctTape rebalance test dont work on dev version because it tries to read cache statistics on deactivated cluster. 
Easy fix is to remove unneeded? deactivation in this test
- [How to …

IGNITE-15270  Fix rebalance test

---

modules/core/src/main/java/org/apache/ignite/internal/IgniteEventsImpl.java
modules/core/src/main/java/org/apache/ignite/internal/IgniteSchedulerImpl.java
modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoManager.java
modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurity.java
modules/core/src/main/java/org/apache/ignite/internal/processors/security/IgniteSecurityProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/security/NoOpIgniteSecurityProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/security/OperationSecurityContext.java
modules/core/src/main/java/org/apache/ignite/internal/processors/security/thread/SecurityAwareCallable.java
modules/core/src/main/java/org/apache/ignite/internal/processors/security/thread/SecurityAwareRunnable.java
modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/TcpDiscoveryNode.java
modules/core/src/test/java/org/apache/ignite/internal/processors/security/client/ClientReconnectTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/security/impl/TestSecurityProcessor.java
modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TestReconnectProcessor.java
modules/core/src/test/java/org/apache/ignite/testsuites/SecurityTestSuite.java
modules/zookeeper/src/main/java/org/apache/ignite/spi/discovery/zk/internal/ZookeeperClusterNode.java

Reinitialized local security context on client node reconnect, because node id changed on disconnect.
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Gui …

IGNITE-15358: Fix client node reconnect with enabled security

---

modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpIgniteClient.java
modules/core/src/main/java/org/apache/ignite/internal/marshaller/optimized/OptimizedMarshaller.java
modules/core/src/test/java/org/apache/ignite/client/PersonExternalizable.java
modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java

Clear thin client caches when cluster connection is lost.
The root cause of the issue is that client believes that server nodes preserve registered user types after reconnect, however, it could be the case that server nodes lose this information (e.g. full cluster restart with clean up of working dirs). This leads to ClassNotFoundException.

IGNITE-15256 Java Thin: Fix ClassNotFoundException on service call after failover

---

modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/sql/SqlAstTraverser.java
modules/indexing/src/test/java/org/apache/ignite/sqltests/CheckWarnJoinPartitionedTables.java

This patch fixes a bug in the `SqlAstTraverser`. It incorrectly handled info about PK in cases of changing order of tables.

IGNITE-15407 Fix PK flag ordering in SQL AST traverse

---

modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/cellular_affinity_test/CellularTxStreamer.java

IGNITE-15078 add DateTimeFormatter to IgniteUtils and change custom formater used in test to it.
The problem is: we don't have this formater in previous versions of ignite, but we run ducktape on this versions (and even on GridGain)
I revert this changes for Ducktape CellularAffinity test
the `green visa` …

IGNITE-15489 revert IGNITE-15078 for Ducktape CellularAffinity test

---

modules/azure/pom.xml
modules/azure/src/main/java/org/apache/ignite/spi/discovery/tcp/ipfinder/azure/TcpDiscoveryAzureBlobStoreIpFinder.java
modules/azure/src/test/java/org/apache/ignite/spi/discovery/tcp/ipfinder/azure/TcpDiscoveryAzureBlobStoreIpFinderSelfTest.java
parent/pom.xml

This patch includes the following changes: 
* Azure-storage-blob version update (to 12.13.0) and its dependencies (considering the dependency graph).
* Removed "removeContainer" method - it is never called because "afterTestsStopped" is called on a separate instance and ipfinder is always null there.
* Removed unnecessary imports (com.nimbusds.oauth2.sdk.util.URLUtils.CHARSET) and reworked the bunch of code in which it was involved.
* Fixed incorrect comparison of error codes in the "unregisterAddresses" method.
The test was checked in a separate (from Ignite) project to make sure all required dependencies were included.

IGNITE-15388

---

modules/core/src/main/java/org/apache/ignite/cache/query/IndexQuery.java
modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/IndexQueryProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/util/GridArgumentCheck.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryAliasTest.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryAllTypesTest.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryFailoverTest.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryQueryEntityTest.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryRangeTest.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQuerySqlIndexTest.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryTestSuite.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/IndexQueryWrongIndexTest.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/MultiTableIndexQuery.java
modules/indexing/src/test/java/org/apache/ignite/cache/query/MultifieldIndexQueryTest.java

Make index name optional for IndexQuery. Then Ignite find an index for query by list of criteria fields. Order of fields in the criteria list doesn't matter.

IGNITE-15391 Add support for creating IndexQuery without index name

---

modules/kubernetes/src/main/java/org/apache/ignite/kubernetes/configuration/KubernetesConnectionConfiguration.java
modules/kubernetes/src/main/java/org/apache/ignite/spi/discovery/tcp/ipfinder/kubernetes/TcpDiscoveryKubernetesIpFinder.java

Add `KubernetesConnectionConfiguration.discoveryPort` so with multiple independent Ignite clusters in a single Kubernetes namespace it is possible to connect to a specific cluster.

IGNITE-15602 Add KubernetesConnectionConfiguration.discoveryPort

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.DotNetCore.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientConnectionTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/RawSecureSocketTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/Client/server-with-ssl-no-client-auth.xml
modules/platforms/dotnet/Apache.Ignite.Core/Client/SslStreamFactory.cs

Allow thin client to establish SSL connection without client-side certificate when `ClientConnectorConfiguration.sslClientAuth` is `false` on server.

IGNITE-15915 .NET: Allow null SslStreamFactory.CertificatePath

---

modules/core/src/test/java/org/apache/ignite/platform/PlatformProcessUtils.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtilsJni.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/TypeNameParser.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/Jvm.cs

Pass Java 9+ specific JVM arguments when necessary (`illegal-access=permit`, `add-exports`).

IGNITE-14294 .NET: Fix ClientServerCompatibilityTest flakiness

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionMap.java
modules/core/src/main/java/org/apache/ignite/internal/util/GridPartitionStateMap.java

CacheGroupMetricsImpl#numberOfPartitionCopies created a lot of objects of `java.lang.Integer` for every call. Amount of objects linearly depends on cache partitions count. Replaced it with existing set objects.

IGNITE-15781 CacheGroupMetricsImpl#numberOfPartitionCopies uses existing set of partitions keys

---

modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/index/H2RowComparator.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/IgniteSqlQueryDecimalArgumentsWithTest.java
modules/indexing/src/test/java/org/apache/ignite/testsuites/IgniteBinaryCacheQueryTestSuite.java

Decimal is only index key that isn't inlined and in the same type can be used for searching data by keys that are inlines (int, double). Tested both int and double, because they have different compare differently with decimal.

IGNITE-15943 Fix comparison inlined fields with decimal search key

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/TypeNameParserTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/TypeResolverTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/ExamplesTestBase.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/TypeNameParser.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/TypeResolver.cs

* Allow dynamic assemblies in `TypeResolver`.
* Skip compiler-generated type names parsing in `TypeNameParser`.

IGNITE-15954 .NET: Fix dynamic assemblies handling in TypeResolver

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Platform/PlatformCacheTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientConnectionTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/CallPlatformServiceTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServiceProxyTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesAsyncWrapper.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Services/ServiceContext.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/UnmanagedCallbacks.cs
modules/platforms/dotnet/Apache.Ignite.Core/Services/ServiceCallContextBuilder.cs

* Fix `TestFailover` flakiness.
* Fix `TestServerConnectionAborted` flakiness.
* Fix IDE warnings.

IGNITE-15986 .NET: Fix ClientConnectionTest.TestFailover flakiness

---

modules/core/src/main/java/org/apache/ignite/internal/binary/streams/BinaryHeapOutputStream.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/PayloadOutputChannel.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/io/ClientConnection.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/io/gridnioserver/GridNioClientConnection.java

* Release pooled buffer in NIO future listener to avoid an extra copy.
* Use `BinaryMemoryAllocator.POOLED` instead of `THREAD_LOCAL` because we release the buffer asynchronously.
* Fix use-after-free caused by `PayloadOutputChannel.out()` callers which wrap it into a writer inside try-with-resources.
* Checked `JmhThinClientCacheBenchmark` - no observable difference.

IGNITE-13804 Java thin: avoid buffer copy on send

---

docs/_docs/code-snippets/java/src/main/java/org/apache/ignite/snippets/services/ServiceExample.java
docs/_docs/services/services.adoc
modules/core/src/main/java/org/apache/ignite/IgniteServices.java
modules/core/src/main/java/org/apache/ignite/internal/processors/service/IgniteServiceProcessor.java
modules/core/src/main/java/org/apache/ignite/services/ServiceConfiguration.java
modules/core/src/test/java/org/apache/ignite/internal/processors/service/GridServiceProcessorProxySelfTest.java
modules/spring/src/test/java/org/apache/ignite/internal/processors/resource/GridServiceInjectionSelfTest.java

As discussed in the threads related to the main ticket #IGNITE-12464, we deprecate references to local services. Also we will return service proxy every time even for local services by `serviceProxy()`

IGNITE-16400 : Deprecate direct references to local services. Fix service proxy.

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientBitmaskFeature.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientGetIdleTimeoutRequest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientHeartbeatTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/IgniteClientConfigurationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/Client/IgniteClientConfiguration.xml
modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
modules/platforms/dotnet/Apache.Ignite.Core/Client/IgniteClientConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/IgniteClientConfigurationSection.xsd
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientBitmaskFeature.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientOp.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientSocket.cs
modules/platforms/dotnet/Directory.Build.props

Implement keepalive: https://cwiki.apache.org/confluence/display/IGNITE/IEP-83+Thin+Client+Keepalive
* Add `OP_HEARTBEAT`, `OP_GET_IDLE_TIMEOUT` on server with `HEARTBEAT` feature flag.
* Implement heartbeats in .NET thin client:
* `IgniteClientConfiguration.EnableHeartbeats`, default `false`.
* `IgniteClientConfiguration.HeartbeatInterval`, default 30 seconds.
* When heartbeats are enabled, get idle timeout from server, set effective heartbeat interval to `Math.Min(HeartbeatInterval, IdleTimeout / 3)`. Log warning when user-defined value is overridden.

IGNITE-16462 .NET: Thin client: add heartbeats

---

modules/core/src/main/java/org/apache/ignite/configuration/ThinClientConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientRequestHandler.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/compute/ClientComputeTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/utils/PlatformConfigurationUtils.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientConnectionTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Configuration/ClientConnectorConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/Configuration/ThinClientConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/IgniteConfigurationSection.xsd

* Propagate SendServerExceptionStackTraceToClient to .NET
* Java fix: Include stack trace for Compute errors
* Java fix: Include stack trace even when cause is null

IGNITE-16549 .NET: Add IgniteClientConfiguration.SendServerExceptionStackTraceToClient

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinaryChangeSchemaTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinarySchemaChangeTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryWriter.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Structure/BinaryStructure.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/Structure/BinaryStructureTracker.cs

When new binary object schema is a subset of existing schema, it was not sent to the cluster. Detect this case and send the schema.

IGNITE-16649 .NET: Fix missing binary schema update when field is removed

---

modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/AbstractIndex.java
modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/sorted/inline/InlineIndexImpl.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GeoSpatialClientIndex.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GeoSpatialClientIndexDefinition.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GeoSpatialClientIndexFactory.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GeoSpatialIndexImpl.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GeoSpatialUtils.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GriH2SpatialBaseIndex.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2SpatialBaseIndex.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2SpatialClientIndex.java
modules/geospatial/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2SpatialIndex.java
modules/geospatial/src/test/java/org/apache/ignite/internal/processors/query/h2/H2IndexingAbstractGeoSelfTest.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/index/client/AbstractClientIndex.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/index/client/ClientInlineIndex.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2Table.java

Client nodes incorrectly handle geo-spatial indexes, and fail on trying to create index. This patch provides a mock for geo-spatial indexes on client nodes by analogue with ClientInlineIndex for sorted indexes. It enables creation of indexes on Ignite client nodes.

IGNITE-16604: Fix GeoSpatial indexes for client nodes

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs

IGNITE-15650 caused .NET test failure on Windows platform. 
Reason: wrong runtime binding. 
Solution: simplified method calls. Dynamic and ordinary service object are now separated.

IGNITE-16759 .NET: Fix services tests for Windows platform

---

modules/control-utility/pom.xml
modules/zookeeper/pom.xml
modules/zookeeper/src/test/java/org/apache/ignite/spi/discovery/zk/ZookeeperDiscoverySpiTestSuite1.java
parent/pom.xml

Fix zookeeper tests didn't run. Downgrade zoo version, exclude transitive junit deps, add system property (actually default one)

IGNITE-16753 Add junit to exclusions for curator-test library

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.DotNetCore.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.csproj
modules/platforms/dotnet/Apache.Ignite.Core/Apache.Ignite.Core.csproj
modules/platforms/dotnet/Apache.Ignite.Log4Net/Apache.Ignite.Log4Net.csproj
modules/platforms/dotnet/Apache.Ignite.NLog/Apache.Ignite.NLog.csproj
modules/platforms/dotnet/release/NuGet.config
modules/platforms/dotnet/release/_global.json
modules/platforms/dotnet/release/verify-nuget.ps1

The issue was caused by .NET Core 2.1 package restore quirks. 2.1 is out of support now.
* Remove `global.json` to get rid of .NET Core 2.1 requirement.
* Use `NuGet.config` to restore from multiple sources (local folder + nuget.org for 3rd party packages).
* Update script to install Ignite packages with specific version.
* Bump `NLog` and `log4net` dependencies to versions that support netstandard.

IGNITE-16788 .NET: Fix verify-nuget.ps1 

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheProcessor.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheLifecycleAwareSelfTest.java
modules/core/src/test/java/org/apache/ignite/testframework/junits/common/GridAbstractLifecycleAwareSelfTest.java

IGNITE-16822 Fix GridCacheLifecycleAwareSelfTest.testLifecycleAware

---

modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientAtomicLongImpl.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/AtomicLongTest.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientAbstractPartitionAwarenessTest.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientPartitionAwarenessStableTopologyTest.java

`AtomicLong` is just a cache entry underneath, where `GridCacheInternalKeyImpl` is the key. Use partition awareness to send requests to the primary node and improve performance.

IGNITE-16983 Java thin: Add AtomicLong partition awareness

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/ShellTests.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Shell.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/JvmDll.cs

* Try `/usr/bin/readlink` as well as `readlink` - it is not in PATH in some rare scenarios.
* Improve logging when commands fail.

IGNITE-17063 .NET: Improve Java detection on Linux

---

modules/core/src/main/java/org/apache/ignite/internal/client/thin/io/gridnioserver/GridNioClientConnectionMultiplexer.java
modules/core/src/test/java/org/apache/ignite/client/ConnectionTest.java

When `GridNioServer.createSession` is called concurrently with `GridNioServer.stop`, it is possible that `GridNioFuture` returned by `createSession` will never complete. Add RW lock in `GridNioClientConnectionMultiplexer` to fix this.

IGNITE-17247 Fix race condition on close in GridNioClientConnectionMultiplexer

---

modules/core/src/main/java/org/apache/ignite/cache/query/AbstractContinuousQuery.java

All the setters for ContinuousQueries return `this` to help with chaining... except for `.setIncludeExpired`. This PR fixes that.
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNIT …

IGNITE-17245 AbstractContinuousQuery.setIncludeExpired returns this for chaining

---

modules/ducktests/src/main/java/org/apache/ignite/internal/ducktest/tests/self_test/TestAffinityMapper.java
modules/ducktests/tests/ignitetest/services/utils/config_template.py
modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/__init__.py
modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/cache.py
modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/communication.py
modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/data_storage.py
modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/transaction.py
modules/ducktests/tests/ignitetest/services/utils/ssl/client_connector_configuration.py
modules/ducktests/tests/ignitetest/services/utils/ssl/connector_configuration.py
modules/ducktests/tests/ignitetest/services/utils/templates/cache_macro.j2
modules/ducktests/tests/ignitetest/services/utils/templates/client_connector_configuration.j2
modules/ducktests/tests/ignitetest/services/utils/templates/connector_configuration.j2
modules/ducktests/tests/ignitetest/services/utils/templates/datastorage_macro.j2
modules/ducktests/tests/ignitetest/services/utils/templates/ignite.xml.j2
modules/ducktests/tests/ignitetest/services/utils/templates/misc_macro.j2
modules/ducktests/tests/ignitetest/services/utils/templates/transaction_macro.j2
modules/ducktests/tests/ignitetest/tests/auth_test.py
modules/ducktests/tests/ignitetest/tests/control_utility/baseline_test.py
modules/ducktests/tests/ignitetest/tests/persistence_upgrade_test.py
modules/ducktests/tests/ignitetest/tests/rebalance/util.py
modules/ducktests/tests/ignitetest/tests/self_test.py
modules/ducktests/tests/ignitetest/tests/snapshot_test.py
modules/ducktests/tests/ignitetest/utils/bean.py

* Added more options to configure in IgniteConfiguration. Say cache templaes, affinity, transaction options, and more individual options.
* XML config file generation  refactored a little bit for some beans to reduce code duplication (snake case names of python config classes converted automatically to camel case to be inserted to XML ignite config.
---
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute …

IGNITE-17322 [ducktests] Add ability to configure more options for ignite nodes

---

modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/WALRecord.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/wal/record/delta/ClusterSnapshotRecord.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/CheckpointContextImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/CheckpointListener.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/checkpoint/CheckpointWorkflow.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotFutureTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/serializer/RecordDataV1Serializer.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/IgniteSequentialNodeCrashRecoveryTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
modules/core/src/test/java/org/apache/ignite/testframework/wal/record/RecordUtils.java

For PITR [1] process of recovering based on ClusterSnapshot + archived WALs.
It's required to have a point in WAL which splits whole WAL on 2 areas:
1. Before this point all data changes are contained within ClusterSnapshot, and no need to recover them from WAL archived files.
2. After this point all data need to be recovered from WAL archived files.
It's proposed to write ClusterSnapshotRecord while the checkpoint is running (cp#writeLock has acquired). ClusterSnapshot process guarantees:
1. there is no active transactions (or any data changes) in moment of running checkpoint.
2. ClusterSnapshot contains all data pages that will be persisted within this checkpoint process.
Then every logical record after begin CheckointRecord doesn't belong to ClusterSnapshot. Then it's safe to write …

IGNITE-17215: Write ClusterSnapshotRecord to WAL

---

modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientMessage.java
modules/core/src/test/java/org/apache/ignite/client/ConnectionTest.java

Fixed bug that caused wrong first message reconstruction if it is divided in more than one TCP packet. 
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+G …

IGNITE-17387 Thin: Fix server-side message parsing for big messages

---

modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py

Address changes in property names introduced in  the IGNITE-17322 preventing ducktests (discovery in particular) failure with  error
```AttributeError: 'TcpCommunicationSpi' object has no attribute 'port_range'```
Also add logging of such exceptions occured in async background thread to not miss such problems in the future.
------------
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute- …

IGNITE-17421 [ducktests] Fix drop network functionality

---

modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/IgniteIndexReader.java
modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/PageListsInfo.java
modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/indexreader/ScanContext.java
modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/indexreader/IgniteIndexReaderTest.java

- Eliminate storing errors in list. This leads to OOM on huge files with many issues.
- Instead of progress by index count show progress by pages which shows more fair info.

IGNITE-17391 Minimize stored data while traversing trees for index-reader

---

modules/ducktests/tests/docker/Dockerfile
modules/ducktests/tests/ignitetest/tests/auth_test.py

In docker image update the environment of the program started via the SSH to use the UTF-8 locale instead of the default POSIX one.  In particular the ```LANG=C.UTF-8```  was added into the /home/ducker/.ssh/environment file.
This is needed for example to pass the password with  non-ascii symbols to control.sh
------------
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessa …

IGNITE-17513 [ducktests] Set locale to c.utf-8 in docker image

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/DataStructures/IgniteSetClientTests.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtils.cs

Use `StringAssert.StartsWith` because the full message differs on various platforms.

IGNITE-17559 .NET: Fix TestCopyToInvalidArguments on Windows

---

modules/core/src/main/java/org/apache/ignite/internal/visor/tx/VisorTxInfo.java

Appended units to duration - sec and timeout - ms. The change is required as the execution of control.sh --tx command produces output of matching transactions (below) from which it is unclear that duration is provided in seconds while timeout is in milliseconds.
The result of executing control.sh --tx command is below. The **in bold** change is added in this PR:
Tx: [xid=fdc4d720281-00000000-0fd8-0177-0000-000000000012, label=null, state=ACTIVE, startTime=2022-07-06 05:05:07.432, duration=778 **sec**, isolation=REPEATABLE_READ, concurrency=PESSIMISTIC, topVer=AffinityTopologyVersion [topVer=199, minorTopVer=0], timeout=40000 **ms**, ...].
1) VisorTxInfo class:
https://github.com/apache/ignite/blob/bf9a460eccd07701cacac2a414c65707243350f1/modules/core/src/main/java/org/apache/ignite/interna …

IGNITE-17537 Append units for duration -sec and timeout -sec

---

modules/ducktests/tests/ignitetest/services/utils/control_utility.py

Allow the time units for 'duration' and 'timeout' values in the control.sh --tx output parser. 
To be in sync with the changes done in [IGNITE-17537](https://issues.apache.org/jira/browse/IGNITE-17537)  (' sec' was added after the tx duration and tx timeout values).
-----
the `green visa` attached to the …

IGNITE-17584 [ducktests] Allow time units in the control.sh --tx output parser

---

RELEASE_NOTES.txt

IGNITE-17651 Update Apache Ignite 2.14 release notes

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/CancellationTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtils.cs

Use synchronization primitives instead of relying on `Thread.Sleep`.
https://issues.apache.org/jira/browse/IGNITE-17710

IGNITE-17710 .NET: Fix CancellationTest.TestTask

---

modules/clients/src/test/java/org/apache/ignite/common/NodeSslConnectionMetricTest.java
modules/core/src/main/java/org/apache/ignite/internal/client/impl/connection/GridClientNioTcpConnection.java
modules/core/src/main/java/org/apache/ignite/internal/util/nio/ssl/GridNioSslFilter.java

* Fix `GridClientNioTcpConnection` hang on invalid SSL protocol (same fix as IGNITE-17367).
* Fix `rejectedSesCnt` in `GridNioSslFilter`.
* Improve assertions to show expected and actual.

IGNITE-17785 Fix NodeSslConnectionMetricTest

---

modules/core/src/main/java/org/apache/ignite/internal/client/thin/ReliableChannel.java
modules/core/src/test/java/org/apache/ignite/client/ExceptionRetryPolicy.java
modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/ClientConnectionTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/TestRetryPolicy.cs

Fix API call hang when there is an exception in `RetryPolicy` implementation. Catch exceptions and propagate to the caller.

IGNITE-17815 Java thin: Fix RetryPolicy exception handling, propagate exceptions to API caller

---

modules/core/src/main/java/org/apache/ignite/spi/deployment/local/LocalDeploymentSpi.java
modules/platforms/cpp/thin-client/src/impl/data_router.cpp
modules/urideploy/src/test/java/org/apache/ignite/spi/deployment/uri/GridUriDeploymentConfigSelfTest.java

IGNITE-17922 Fix nullptr access

---

modules/core/src/test/java/org/apache/ignite/platform/PlatformDeployServiceTask.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Services/ServicesTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Services/ServiceProxyInvoker.cs

When resolving service method in `ServiceProxyInvoker`, also check default interface methods.

IGNITE-17796 .NET: Support default interface methods in Services

---

modules/ducktests/tests/ignitetest/services/utils/ignite_aware.py

Use `pgrep` instead of `jcmd` to get pids of java processes.
This is needed to be able to run tests with the `-XX:+PerfDisableSharedMem` JVM option which makes the process invisible for utilities like `jps` and `jcmd`.
-------- …

IGNITE-18014 [ducktests] Use pgrep instead of jcmd to get java pids

---

modules/core/src/test/java/org/apache/ignite/platform/PlatformProcessUtils.java
modules/core/src/test/java/org/apache/ignite/platform/PlatformTestUtils.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Compatibility/ClientServerCompatibilityTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtilsJni.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/ConsoleWriter.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/Env.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/EnvDelegates.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/Jvm.cs

* Add JVM arguments for Java 15+
* Fix `ClientServerCompatibilityTest` 
* Skip old Ignite versions when new JDK is detected.
* Fix error handling in `PlatformProcessUtils.startProcess`
NOTE: The following warning may appear on startup with JDK 17+: `OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0`. It is harmless.
Unfortunately, with JNI there is no way to tell apart Java versions above 10: https://docs.oracle.com/en/java/javase/17/docs/specs/jni/functions.html#getversion. So we have to use a universal set of JVM args for everything Java 9+, which may produce warnings.

IGNITE-18191 .NET: Fix startup on Java 15+

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionDemander.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionSupplier.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridClientPartitionTopology.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/GridDhtPartitionTopologyImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/PartitionsEvictManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotFutureTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsQuickVerifyHandler.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
modules/core/src/main/java/org/apache/ignite/internal/util/lang/GridFunc.java
modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringBuilder.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/dht/topology/EvictPartitionInLogTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/wal/IgniteWalRebalanceLoggingTest.java
modules/core/src/test/java/org/apache/ignite/internal/util/tostring/GridToStringBuilderSelfTest.java

IGNITE-17865 Disable partition ranges in log messages by default

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Common/IgniteProductVersionTests.cs
modules/platforms/dotnet/Apache.Ignite.Core/Common/IgniteProductVersion.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryUtils.cs

- Fixed timestamp part of Ignite version in .NET;
- Added test (needs review).
- [Apache …

IGNITE-18346 .NET: Fix timestamp in IgniteProductVersion

---

modules/core/src/main/java/org/apache/ignite/internal/LongJVMPauseDetector.java

In Long JVM pause detector we warn user that the thread wasn't alive for a threshold
Possible too long JVM pause: 500+ milliseconds.
But it is often treated as a GC pause.
We can change that warning to
Possible too long JVM pause: 500+ milliseconds. (GC pause or hardware temporary freeze)
To enlist possible reasons behind that behaviour
________________
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute …

IGNITE-17945 Change message in case watchdog thread observes freeze

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheMapEntry.java
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Platform/PlatformCachePartialClientConnectionTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Platform/PlatformCacheReadFromBackupTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/Platform/PlatformCacheTest.cs
modules/platforms/dotnet/Apache.Ignite.Core/IIgnite.cs

* Remove platform cache entry when corresponding `GridCacheMapEntry` is not `valid`.
* Add a test where two thick client nodes with near cache connect to different backup server nodes.

IGNITE-18427 .NET: Fix platform cache invalidation on client nodes with near cache

---

docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc

IGNITE-18515 CDC: add documentation about metadata replication

---

docs/_docs/monitoring-metrics/new-metrics.adoc
docs/_docs/monitoring-metrics/system-views.adoc
docs/_docs/tools/control-script.adoc
modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/metric/MetricCommand.java
modules/control-utility/src/main/java/org/apache/ignite/internal/commandline/metric/MetricCommandArg.java
modules/control-utility/src/test/java/org/apache/ignite/util/MetricCommandTest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataRegionMetricsImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/metastorage/persistence/DistributedMetaStorageImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/pool/PoolProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/visor/metric/VisorMetricTask.java
modules/core/src/main/java/org/apache/ignite/internal/visor/metric/VisorMetricTaskArg.java
modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output

IGNITE-18616 control.sh metric configuration added

---

modules/ducktests/tests/ignitetest/services/utils/control_utility.py

Add ability to start/stop/rotate/get status of performance statistics collecting via the control.sh
----
- …

IGNITE-18676 [ducktests] Add ability to control the performance statistics collecting

---

modules/core/src/main/java/org/apache/ignite/internal/IgniteComputeImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/task/TaskExecutionOptions.java
modules/core/src/test/java/org/apache/ignite/internal/processors/compute/IgniteComputeCustomExecutorSelfTest.java

IGNITE-18713 Fixed task options are not applied if placed before withExecutor modifier.

---

modules/ducktests/tests/ignitetest/utils/version.py
modules/ducktests/tests/setup.py

* Fixes the format of the python ducktests module to conform the PEP 440 (setuptools >= 66.0.0 forbids invalid formats)
* Disable implicit detection of the dev-mode testing by the version number.  To be able to test binary distribs built from current version.
-------------------
the `green visa` attached …

IGNITE-18765 [ducktests] Use PEP 440 compatible version number for python module

---

modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/GridEncryptionManager.java
modules/core/src/main/java/org/apache/ignite/internal/managers/encryption/GroupKeyChangeProcess.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
modules/core/src/main/java/org/apache/ignite/internal/util/distributed/DistributedProcess.java
modules/core/src/main/java/org/apache/ignite/internal/util/distributed/FullMessage.java
modules/core/src/main/java/org/apache/ignite/internal/util/distributed/SingleNodeMessage.java
modules/core/src/test/java/org/apache/ignite/internal/util/DistributedProcessErrorHandlingTest.java
modules/core/src/test/java/org/apache/ignite/internal/util/DistributedProcessTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteUtilSelfTestSuite.java

IGNITE-18783 Fix DistributedProcess hangs on AssertionError

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/incremental/IncrementalSnapshotWarnAtomicCachesTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IncrementalSnapshotsTestSuite.java

IGNITE-17650 Write a warning message for atomic caches

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Log/ConsoleLoggerTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Log/ConsoleLogger.cs

Do not omit `nativeErrorInfo`, it can contain important details from Java stack trace.

IGNITE-18887 .NET: Fix TestContextLogger and ConsoleLogger to include exception details

---

modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryContext.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/binary/GridCacheBinaryConfigurationWithAffinityKeyClientReconnectTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBinaryObjectsTestSuite.java

IGNITE-18976 Fix lost affinity key cache configuration after client reconnect

---

modules/ducktests/tests/ignitetest/services/utils/ignite_configuration/__init__.py
modules/ducktests/tests/ignitetest/services/utils/templates/client_configuration_macro.j2
modules/ducktests/tests/ignitetest/tests/auth_test.py
modules/ducktests/tests/ignitetest/tests/thin_client_test.py

Add ability to pass several server nodes addresses to thin client configuration in ducktests. Previousluy the only address may be used.
Also added option to control the partition awareness mode.
------------------- …

IGNITE-19064 [ducktests] Allow several server nodes and partition awareness option in thin client configuration

---

modules/core/src/main/java/org/apache/ignite/internal/PlatformSecurityAwareJob.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformContext.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/PlatformContextImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformAbstractFunc.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformAbstractJob.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformBroadcastingMultiClosureTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformBroadcastingSingleClosureTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformCallable.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformClosureJob.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformCompute.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformFullJob.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformFullTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/compute/PlatformRunnable.java
modules/core/src/main/java/org/apache/ignite/internal/processors/task/GridTaskWorker.java
modules/platforms/cpp/core-test/CMakeLists.txt
modules/platforms/cpp/core-test/config/compute-security.xml
modules/platforms/cpp/core-test/src/compute_security_test.cpp
modules/platforms/cpp/core/include/ignite/impl/compute/compute_impl.h
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Apache.Ignite.Core.Tests.DotNetCore.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/ComputeSecurityPermissionsTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Compute/ComputeSecuritymisionsTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Config/Compute/compute-security.xml
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Compute/Closure/ComputeActionJob.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Compute/Closure/ComputeFuncJob.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Compute/Closure/ComputeOutFuncJob.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Compute/ComputeFunc.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Compute/ComputeImpl.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Compute/ComputeJob.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Compute/ComputeOutFunc.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/IgniteUtils.cs

Added authorization of tasks/closures/callables/runnables that are executed via Compute API in CPP and DotNet platforms implementation. 
DotNet: The FQN of the executable class is used as the task name for authorization.
CPP: The name of the binary class type corresponding to the computed executable is used as the task name for authorization.
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContr …

IGNITE-19030 Platforms: Add authorization of Compute tasks

---

modules/core/src/main/java/org/apache/ignite/configuration/ClientConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientDiscoveryContext.java
modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/AbstractThinClientTest.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/ThinClientEnpointsDiscoveryTest.java

Cluster discovery is always enabled currently, which can be undesirable in some use cases. Add a config property to disable discovery.

IGNITE-19221 Java thin: Add ClientConfiguration.clusterDiscoveryEnabled

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/PartitionAwarenessTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/PartitionAwarenessWithClusterDiscoveryTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cluster/ClientClusterDiscoveryTests.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cluster/ClientClusterDiscoveryTestsBase.cs
modules/platforms/dotnet/Apache.Ignite.Core/Client/IgniteClientConfiguration.cs
modules/platforms/dotnet/Apache.Ignite.Core/IgniteClientConfigurationSection.xsd
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientFailoverSocket.cs

* Add `IgniteClientConfiguration.EnableClusterDiscovery`.
* Allow any combinations of `EnableClusterDiscovery` and `EnablePartitionAwareness`:
* Only `EnablePartitionAwareness`: use configured endpoints to route requests.
* Only `EnableClusterDiscovery`: use discovered endpoints for failover, but maintain only one connection.
* Both enabled: discover all, connect to all.
* Both disabled: maintain one connection, use only configured endpoints for failover.

IGNITE-19222 .NET: Add IgniteClientConfiguration.EnableClusterDiscovery

---

modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java

IGNITE-19415 GridCommandHandlerTest should be runnable at other modules

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/PartitionAwarenessTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/TestKeyWithAffinityBinarizable.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Cache/TestKeyWithUserObjectAffinity.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryHashCodeUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryObjectSchemaHolder.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryWriter.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Client/ClientFailoverSocket.cs

1. Support hash calculation for affinity keys.
2. When partition awareness hash still can't be computed, do not throw an exception; log a warning (once per type) and use the default connection.

IGNITE-19359 .NET: Fix 'Affinity keys are not supported' exception

---

modules/core/src/main/java/org/apache/ignite/spi/metric/MetricExporterSpi.java
modules/core/src/main/java/org/apache/ignite/spi/metric/RegexpMetricFilter.java
modules/spring/src/test/config/metric/regexp-filter-config.xml
modules/spring/src/test/java/org/apache/ignite/internal/metric/RegexpMetricFilterTest.java
modules/spring/src/test/java/org/apache/ignite/testsuites/IgniteSpringTestSuite.java

… Spring XML
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Ru …

IGNITE-19620 Provide ability to configure metric exporter filter from Spring XML

---

modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java

Signature has changed in https://github.com/openjdk/jdk/commit/a56598f5a534cc9223367e7faa8433ea38661db9
- …

IGNITE-19652 Adapt to DirectByteBuffer ctor changes in JDK 21

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxLocalAdapter.java

IGNITE-19875 GridDhtTxLocalAdapter initial cleanup

---

modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientChannel.java

Remove the port limitation to support other dynamic port reverse proxys. Like testcontainers[1]
[1]
https://stackoverflow.com/questions/76746998/why-ignite-tcpclientchannel-port-can-not-larger-than-49151

IGNITE-20026 Java thin: Remove port range limitation

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/GridDistributedTxRemoteAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxLocal.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxLocalAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/store/GridCacheStoreManagerAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxLocalAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/util/lang/GridMetadataAwareAdapter.java

IGNITE-20172 TX code cleanup scope #1 initial common cleanup

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/GridDhtTxPrepareFuture.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/CacheQueryFilterExpiredTest.java

IGNITE-20546 Fix transactions expiration set for reinsert

---

modules/core/src/main/java/org/apache/ignite/configuration/ClientConnectorConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/processors/odbc/ClientListenerProcessor.java
modules/core/src/test/java/org/apache/ignite/internal/processors/odbc/ClientSessionOutboundQueueLimitTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/odbc/ClientSessionOutboundQueueimitTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite.java

IGNITE-20424 Added client session outbound queue size limit.

---

modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/persistence/db/LongDestroyDurableBackgroundTaskTest.java

Removed setting up of `CacheValidateIndexesCommandArg` (former `VisorValidateIndexesTaskArg`) `checkFirst` parameter.
Before [IGNITE-15629](https://issues.apache.org/jira/browse/IGNITE-15629) `VisorValidateIndexesTaskArg` was initialized in `LongDestroyDurableBackgroundTaskTest` via constructor with zero argument for `checkFirst` [1]. Currently, a setter method `CacheValidateIndexesCommandArg#checkFirst` is used and it performs implicit validation, so value of `checkFirst` should be positive.
Under the hood, for `checkFirst` with values less or equal to zero processing is skipped in `ValidateIndexesClosure#processPartIterator`[2, 3] (and in `#processIndex`). Moreover, default value of `checkFirst` is `-1` [4], so we can remove explicit setting up of this parameter in order to pass the …

IGNITE-20758 Fix LongDestroyDurableBackgroundTaskTest

---

modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerTest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/PartitionUpdateCounterDebugWrapper.java

IGNITE-20737: add method equals to PartitionUpdateCounterDebugWrapper

---

RELEASE_NOTES.txt

IGNITE-20926 Added 2.16 release notes.

---

docs/_docs/SQL/JDBC/jdbc-driver.adoc

IGNITE-10268 Remove documentation about "replicatedOnly" flag

---

modules/core/src/main/java/org/apache/ignite/dump/DumpReader.java
modules/core/src/main/java/org/apache/ignite/dump/DumpReaderConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotMetadata.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotOperationRequest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotPartitionsVerifyHandler.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/SnapshotRestoreProcess.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/CreateDumpFutureTask.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/Dump.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/DumpEntrySerializer.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AbstractSnapshotSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/EncryptedSnapshotTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/AbstractCacheDumpTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteCacheDumpSelf2Test.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/dump/IgniteConcurrentCacheDumpTest.java

IGNITE-21013 Support encryption of cache dumps

---

docs/_data/toc.yaml
docs/_docs/SQL/JDBC/error-codes.adoc
docs/_docs/SQL/JDBC/jdbc-driver.adoc
docs/_docs/key-value-api/continuous-queries.adoc

…plete document deletion
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abb …

IGNITE-21067 Clean up documents related to MVCC

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Compatibility/ClientServerCompatibilityTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/JavaServer.cs

Disable `ClientServerCompatibilityTest` test cases for Ignite 2.4.0 and 2.6.0 on JDK 11.

IGNITE-21395 .NET: Fix ClientServerCompatibilityTest on JDK 11

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Client/Compatibility/ClientReconnectCompatibilityTest.cs

Old Ignite versions can't run on newer JDKs.

IGNITE-21417 .NET: Disable TestReconnectToOldNodeDisablesPartitionAwareness on JDK 11+

---

modules/core/src/main/java/org/apache/ignite/internal/cache/query/index/IndexQueryProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/CacheQueryType.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractQuerySelfTest.java

IGNITE-22183 Recording of Index query events added

---

modules/indexing/src/test/java/org/apache/ignite/cache/query/ThinClientIndexQueryTest.java

IGNITE-22215 Fix for ThinClientIndexQueryTest#testPageSize

---

modules/control-utility/src/test/java/org/apache/ignite/internal/commandline/SecurityCommandHandlerPermissionsTest.java
modules/control-utility/src/test/java/org/apache/ignite/util/GridCommandHandlerConsistencyTest.java
modules/core/src/main/java/org/apache/ignite/internal/management/consistency/ConsistencyRepairTask.java

_**Intro:**_
Currently 'Read Repair' task performed for the chosen partitions by control.sh requires CACHE_READ and CACHE PUT permissions in addition to ADMIN_OPS. Thus, to perform the comand `control.sh --consistency repair` the one needs all 3 permissions.
There is no point  to have additional CACHE_READ and CACHE_PUT permissions to perform the operation, as they are useless for the task itself, and introduces security risk, by allowing the user to manipulate the cache in parallel.
The solution would be to substitute user's security context with the context of the cluster node that performs the command. The former is used for the ADMIN_OPS permission check and the latter is used for cache. This will ease the requirement for the users to perform `control.sh --consistency repair` without …

IGNITE-22844 control.sh --consistency repair permissions fixes

---

modules/ducktests/README.md
modules/ducktests/tests/checks/utils/check_ignite_spec.py
modules/ducktests/tests/ignitetest/services/utils/ignite_spec.py
modules/ducktests/tests/ignitetest/services/utils/jvm_utils.py
modules/ducktests/tests/ignitetest/utils/ignite_test.py

- changed default settings for gc log (-Xloggc ->-Xlog:gc)
- added new logs for safepoints
- added new variable to disable safepoints log
- removed UnlockCommercialFeatures because it was used only for jfr, but no longer needed for openjdk11
- changed option in check_boolean_options__go_after_default_ones_and_overwrite_them__if_passed_via_jvm_opt to FlightRecorder
- changed option in check_colon_options__go_after_default_ones_and_overwrite_them__if_passed_via_jvm_opt to -Xlog:gc
The following pattern must be used: `IGNITE-XXXX Change summary` …

IGNITE-23196 [ducktests] Change JVM options to JDK11 ones

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java

IGNITE-23344 Fixed log message in IgniteSnapshotManager::createSnapshot

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/defragmentation/CachePartitionDefragmentationManager.java

The problem was that manager took total size of old index pages after index defragmentation and the size could be zero. Now it takes the size before starting index defragmentation
- [How to …

IGNITE-23451 Fix CachePartitionDefragmentationManager.executeDefragmentation method

---

modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryObjectExImpl.java
modules/core/src/main/java/org/apache/ignite/internal/util/tostring/GridToStringBuilder.java
modules/core/src/test/java/org/apache/ignite/internal/binary/BinaryObjectToStringSelfTest.java

BinaryObjectExImpl::toString shouldn't try to generate large strings for large arrays and respect the IGNITE_TO_STRING_COLLECTION_LIMIT property.
Otherwise errors like **java.lang.OutOfMemoryError: Requested array size exceeds VM limit** errors may occur.
---
the `green visa` attached to the JIRA ticket …

IGNITE-23513 Use limited representation for arrays in BinaryObjectExImpl::toString

---

modules/core/src/main/java/org/apache/ignite/cache/query/SpiQuery.java

IGNITE-23398 Class SpiQuery is marked as DEPRECATED.

---

modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxWithKeyContentionSelfTest.java

IGNITE-23138 Fix TxWithKeyContentionSelfTest (Cache 12 group)

---

docs/_docs/net-specific/net-troubleshooting.adoc

(cherry picked from commit 267862f5413983dbfd920cd6d123a78b5b43329a)

IGNITE-23732 .NET: Document CET crash on .NET 9 (#11677)

---

modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/ExecutionContext.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/IndexScan.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/KeyFilteringCursor.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/TableScan.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/schema/CacheIndexImpl.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/exec/KeyFilteringCursorTest.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/AbstractBasicIntegrationTransactionalTest.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/DataTypesTest.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/KeepBinaryIntegrationTest.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/tx/SqlTransactionsIsolationTest.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/tx/SqlTransactionsUnsupportedModesTest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/TransactionChanges.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/AbstractQueryTransactionIsolationTest.java
modules/core/src/test/java/org/apache/ignite/testframework/SupplierX.java

IGNITE-22733 Introduce TransactionChanges

---

modules/core/src/main/java/org/apache/ignite/logger/java/JavaLogger.java
modules/core/src/test/config/jul-debug.properties
modules/core/src/test/java/org/apache/ignite/logger/java/JavaLoggerTest.java
modules/core/src/test/java/org/apache/ignite/testframework/ListeningTestLogger.java
modules/core/src/test/java/org/apache/ignite/testframework/junits/logger/GridTestLog4jLogger.java
modules/core/src/test/java/org/apache/ignite/testframework/junits/logger/GridTestLog4jLoggerSelfTest.java

JavaLogger.configure method is invoked only once for all instances and it configures cfg field which was not static. Because of that only one instance had correct value and other instances had cfg with null value …

IGNITE-23472 Fix JavaLogger

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/IgniteClientException.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/compute/ClientComputeTask.java
modules/core/src/test/java/org/apache/ignite/internal/client/thin/ComputeTaskTest.java

Added root cause for thrown IgniteClientException when client compute task fails with error. This information was lost when task computation issue happened.
Enhanced IgniteClientException constructor with Throwable argument, which replaced Exception, since task error is Throwable object.
the `green visa` …

IGNITE-23794 Added root cause for thrown IgniteClientException on client compute task failure

---

.github/workflows/sonar-pr-from-fork-build.yml
.github/workflows/sonar-pr-from-fork-scan.yml

`sonar-pr-from-fork-build.yml` and `sonar-pr-from-fork-scan.yml` analyze PRs. `sonar-pr-from-fork-scan.yml` needs privileges to access the `SONARCLOUD_TOKEN` and to update the status of the PR check.
To avoid a malicious PR from accessing those privileges, Ignite requires approval for GitHub Actions, and reviews the PR to catch any malicious code before approving the workflow.
These changes makes sure the privileged workflow is ran against the commit that was approved, and does not pull in any changes that may have been added to the PR after approval.

IGNITE-23820 Run privileged workflow against approved commit

---

docs/_docs/persistence/change-data-capture.adoc
modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcMain.java
modules/core/src/test/java/org/apache/ignite/cdc/AbstractCdcTest.java
modules/core/src/test/java/org/apache/ignite/cdc/CdcSelfTest.java

Within this commit there are 2 metrics implemented:
* EventsConsumptionTime - Time for which this CDC client processed the WAL segment events, in nanoseconds.
* EventsConsumptionTimeTotal - The total time for which this CDC client processed the WAL segments events, in nanoseconds.
It will help to monitor the throughput of the transfered cache entries as well as finish time of the proccess.
(see [the Maintainers …

IGNITE-23168 Event consumption time metric in CDC consumer

---

modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheAffinityCallSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/CacheLateAffinityAssignmentTest.java

IGNITE-23991 Remove setForceServerMode from CacheLateAffinityAssignmentTest

---

docs/_config.yml
docs/_docs/code-snippets/java/pom.xml
modules/checkstyle/pom.xml
modules/core/src/main/resources/ignite.properties
modules/dev-utils/ignite-modules-test/build.gradle
modules/ducktests/tests/ignitetest/__init__.py
modules/platforms/cpp/CMakeLists.txt
modules/platforms/dotnet/SharedAssemblyInfo.cs
parent/pom.xml

IGNITE-23763 Update Ignite version to 2.18.0-SNAPSHOT

---

modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/jdbc/JdbcThinTransactionalSelfTest.java
modules/core/src/main/java/org/apache/ignite/internal/jdbc/thin/JdbcThinConnection.java

IGNITE-24074 Fix createStatement() throws when tx aware queries enabled

---

.github/workflows/sonar-pr-from-fork-build.yml
.github/workflows/sonar-pr-from-fork-scan.yml

Follow-up on 964dc48 which removed the checkout from the pull-request workflow entirely. This should now check out the default rev (which should be the code from the PR as it was when the workflow was approved). …

IGNITE-23820 Restore 'checkout' in `sonar-pr-from-fork-build.yml`

---

RELEASE_NOTES.txt

IGNITE-23760 Update Apache Ignite 2.17 release notes

---

modules/clients/src/test/java/org/apache/ignite/internal/jdbc2/JdbcResultSetSelfTest.java
modules/core/src/test/java/org/apache/ignite/cache/store/jdbc/CacheJdbcPojoStoreTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheEntryProcessorCopySelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheEnumOperationsAbstractTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheStartupInDeploymentModesTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheConditionalDeploymentSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheGroupsTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheReadThroughEvictionsVariationsSuite.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheStoreValueAbstractTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/replicated/preloader/GridCacheReplicatedPreloadSelfTest.java
modules/core/src/test/java/org/apache/ignite/session/GridSessionCheckpointSelfTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/WithKeepBinaryCacheConfigVariationsFullApiTestSuite.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractFieldsQuerySelfTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractInsertSqlQuerySelfTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractQuerySelfTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheAbstractSqlDmlQuerySelfTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/IgniteCacheJoinQueryWithAffinityKeyTest.java

IGNITE-15803 Remove "instanceof BinaryMarshaller" from tests

---

modules/platforms/cpp/network/include/ignite/network/data_buffer.h
modules/platforms/cpp/network/src/network/data_buffer.cpp
modules/platforms/cpp/network/src/network/length_prefix_codec.cpp
modules/platforms/cpp/thin-client-test/CMakeLists.txt
modules/platforms/cpp/thin-client-test/src/network_codec_test.cpp

- Added test;
- Fixed the big.

IGNITE-23598 Fix LengthPrefixCodec issue with 3 byte buffer

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionsExchangeFuture.java

IGNITE-24095 Remove FORCE_ADD_REASSIGNMENT_SINCE

---

modules/core/src/main/java/org/apache/ignite/internal/managers/communication/GridIoMessageFactory.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionSupplier.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionSupplyErrorMessage.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/GridDhtPartitionSupplyMessageV2.java
modules/core/src/main/resources/META-INF/classnames.properties
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheNoAffinityExchangeTest.java

IGNITE-24096 Remove GridDhtPartitionSupplyMessageV2#AVAILABLE_SINCE

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/preloader/latch/ExchangeLatchManager.java

IGNITE-24097 Remove ExchangeLatchManager#VERSION_SINCE

---

modules/core/src/main/java/org/apache/ignite/internal/util/nio/GridNioServer.java
modules/core/src/main/java/org/apache/ignite/internal/util/nio/ssl/GridNioSslFilter.java
modules/core/src/main/java/org/apache/ignite/internal/util/nio/ssl/GridNioSslHandler.java
modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/TcpHandshakeExecutor.java
modules/core/src/test/java/org/apache/ignite/internal/util/nio/TcpCommunicationSpiSslVolatilePayloadTest.java
modules/core/src/test/java/org/apache/ignite/spi/communication/GridAbstractCommunicationSelfTest.java
modules/core/src/test/java/org/apache/ignite/spi/communication/TestVolatilePayloadMessage.java
modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/GridTcpCommunicationSpiAbstractTest.java
modules/core/src/test/java/org/apache/ignite/spi/communication/tcp/GridTcpCommunicationSpiSslSelfTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteSpiCommunicationSelfTestSuite.java

IGNITE-24224 Fixed NIO server broken message serialization with SSL enabled.

---

modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/exp/agg/GroupKey.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/exec/rel/HashAggregateNode.java

IGNITE-24131 Reuse GroupKey.Builder for hash aggregate

---

docs/_docs/monitoring-metrics/new-metrics.adoc
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/DataStorageMetricsImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/wal/FileWriteAheadLogManager.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/IgniteDataStorageMetricsSelfTest.java

With new metric 'LastArchivedSegment' we can track the current index of WAL file
New metrics: 
* LastArchivedSegment - Last archived file absolute index, 0-based.
- [How to …

IGNITE-24157 LastArchivedSegment metric for WAL archive

---

modules/core/src/main/java/org/apache/ignite/internal/processors/datastructures/DataStructuresProcessor.java

IGNITE-24101 Remove SEPARATE_CACHE_PER_NON_COLLOCATED_SET_SINCE

---

modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/CalciteQueryProcessor.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/schema/IgniteSchema.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/schema/SchemaHolderImpl.java
modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/schema/ViewTableMacroImpl.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/OperatorsExtensionIntegrationTest.java
modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/planner/AbstractPlannerTest.java

IGNITE-24348 Provide custom FrameworkConfig to SQL views

---

modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/internal/InboundConnectionHandler.java

IGNITE-24102 Remove VERSION_SINCE_CLIENT_COULD_WAIT_TO_CONNECT

---

modules/core/src/test/java/org/apache/ignite/internal/processors/odbc/ClientSessionOutboundQueueLimitTest.java

IGNITE-24334 Fixed flaky ClientSessionOutboundQueueLimitTest

---

docs/_docs/extensions-and-integrations/change-data-capture-extensions.adoc
docs/_docs/persistence/change-data-capture.adoc
modules/core/src/main/java/org/apache/ignite/cdc/CdcCacheEvent.java
modules/core/src/main/java/org/apache/ignite/cdc/CdcConfiguration.java
modules/core/src/main/java/org/apache/ignite/cdc/CdcConsumer.java
modules/core/src/main/java/org/apache/ignite/cdc/CdcEvent.java
modules/core/src/main/java/org/apache/ignite/cdc/TypeMapping.java
modules/core/src/main/java/org/apache/ignite/configuration/DataRegionConfiguration.java
modules/core/src/main/java/org/apache/ignite/configuration/DataStorageConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/cdc/CdcLoader.java
modules/core/src/main/java/org/apache/ignite/internal/management/IgniteCommandRegistry.java
modules/core/src/main/java/org/apache/ignite/internal/management/cdc/CdcDeleteLostSegmentLinksCommand.java
modules/core/src/main/java/org/apache/ignite/internal/management/cdc/CdcResendCommand.java
modules/core/src/main/java/org/apache/ignite/startup/cmdline/CdcCommandLineStartup.java
modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassTest_help.output
modules/core/src/test/resources/org.apache.ignite.util/GridCommandHandlerClusterByClassWithSSLTest_help.output
modules/spring/src/test/java/org/apache/ignite/cdc/CdcConfigurationTest.java

1) Removed information from the documentation that CDC is experimental feature.
2) Removed the @IgniteExperimental annotation from the CDC code.
3) Fixed tests for checking control.sh help command.
4) Made changes to ignite-extentions https://github.com/apache/ignite-extensions/pull/290
5) Move CdcLoader into internal package
6) Remove link from javadoc in CdcConsumer, CdcConfiguration, CdcEvent to CdcMain
!!! Online CDC still experimental
the `green visa` attached to the JIRA …

IGNITE-23333 СDC is no longer experimental

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheAdapter.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/dht/atomic/GridDhtAtomicCache.java
modules/core/src/main/java/org/apache/ignite/internal/processors/performancestatistics/OperationType.java
modules/core/src/test/java/org/apache/ignite/internal/processors/performancestatistics/PerformanceStatisticsThinClientTest.java
modules/core/src/test/java/org/apache/ignite/internal/util/lang/ConsumerX.java

Performance statisitcs tracking added for the following cache operations:
* #putAllConflict()
* #removeAllConflict() 
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Con …

IGNITE-23901 Add operation time performance statistics for putAllConflict, removeAllConflict

---

docs/_layouts/default.html

IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.9.1)

---

docs/_layouts/default.html

IGNITE-24264 Replace Google Analytics with Matomo (Ignite-2.9-docs)

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheObjectContext.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/binary/CacheObjectBinaryProcessorImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/query/GridCacheQueryMarshallable.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/store/CacheOsStoreManager.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/msg/GridH2DmlRequest.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/msg/GridH2DmlResponse.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/msg/GridH2QueryRequest.java

IGNITE-15803 Remove instanceOf BinaryMarshaller

---

modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/integration/TableDdlIntegrationTest.java
modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAbstractSelfTest.java
modules/core/src/main/java/org/apache/ignite/internal/management/cache/QueryEntity.java
modules/core/src/main/java/org/apache/ignite/internal/pagemem/impl/PageMemoryNoStoreImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/CacheStripedExecutor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/store/GridCacheWriteBehindStore.java
modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
modules/core/src/main/java/org/apache/ignite/spi/communication/tcp/messages/NodeIdMessage.java
modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/internal/DiscoveryDataPacket.java
modules/core/src/test/java/org/apache/ignite/internal/metric/JmxExporterSpiTest.java
modules/core/src/test/java/org/apache/ignite/internal/metric/SystemViewSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/datastructures/partitioned/GridCachePartitionedQueueEntryMoveSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/continuous/ContinuousQueryRemoteFilterMissingInClassPathSelfTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/transactions/TxPartitionCounterStateOnePrimaryTwoBackupsTest.java
modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsSelfTest.java
modules/core/src/test/java/org/apache/ignite/lang/GridSetWrapperSelfTest.java
modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySelfTest.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/H2Utils.java

IGNITE-24941 Remove unused code from IgniteUtils

---

docs/_docs/perf-and-troubleshooting/memory-tuning.adoc

- Fixed documentation: the tuning advice was misleading, since the default limit for direct buffers is already equal to -Xmx.
---
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNIT …

IGNITE-26356 Clarify recommendations for -XX:MaxDirectMemorySize in docs
